class Accessories {
    static Rosagrowbush = class {
        static Name = "Rosa_GrowBush"
        static Cooldown = 260
        static Useeffect = "gadget_activate"
        static Aimguidetype = 1
        static Areaeffect = "BushGrowArea"
        static RowID = 1
    }
    static Crowshield = class {
        static Name = "Crow_Shield"
        static Cooldown = 300
        static Useeffect = "gadget_activate"
        static Shieldpercent = 40
        static Shieldticks = 60
        static RowID = 2
    }
    static Wallyheal = class {
        static Name = "Wally_Heal"
        static Type = "consume_bush"
        static Cooldown = 180
        static Useeffect = "gadget_activate"
        static Aimguidetype = 2
        static Interruptsaction = true
        static Customvalue1 = 30
        static Targettoofartext = "TID_ACCESSORY_BLOCKED_BUSH_TOO_FAR"
        static RowID = 3
    }
    static Rocketgirljump = class {
        static Name = "RocketGirl_Jump"
        static Type = "jump"
        static Cooldown = 300
        static Useeffect = "gadget_activate"
        static Aimguidetype = 1
        static Areaeffect = "RocketJumpExplosion"
        static Interruptsaction = true
        static Customvalue1 = 200
        static RowID = 4
    }
    static Trickshotdudeshootaround = class {
        static Name = "TrickshotDude_ShootAround"
        static Type = "repeat_area"
        static Cooldown = 400
        static Useeffect = "gadget_activate"
        static Activeticks = 20
        static Areaeffect = "TrickshotDudeAccessoryExplosion"
        static Interruptable = true
        static Customvalue1 = 10
        static RowID = 5
    }
    static Cactusshootaround = class {
        static Name = "Cactus_ShootAround"
        static Type = "repeat_area"
        static Cooldown = 280
        static Useeffect = "gadget_activate"
        static Activeticks = 30
        static Areaeffect = "CactusAccessoryExplosion"
        static Interruptable = true
        static Customvalue1 = 10
        static RowID = 6
    }
    static Artillerydudecover = class {
        static Name = "ArtilleryDude_Cover"
        static Type = "spawn"
        static Subtype = 1
        static Cooldown = 360
        static Useeffect = "gadget_activate"
        static Customobject = "ArtilleryDudeCover"
        static Customvalue1 = 35
        static RowID = 7
    }
    static Shamanpetslam = class {
        static Name = "Shaman_PetSlam"
        static Cooldown = 260
        static Useeffect = "gadget_activate"
        static Loopingeffectpet = "gadget_on_loop"
        static Activationdelay = 20
        static Aimguidetype = 3
        static Petareaeffect = "ShamanBearSlam"
        static Requirepetdistance = 12
        static Missingtargettext = "TID_ACCESSORY_BLOCKED_MISSING_BEAR"
        static Targettoofartext = "TID_ACCESSORY_BLOCKED_BEAR_TOO_FAR"
        static RowID = 8
    }
    static Barkeepslow = class {
        static Name = "Barkeep_Slow"
        static Cooldown = 360
        static Useeffect = "gadget_activate"
        static Aimguidetype = 1
        static Areaeffect = "BarkeepSlowPuddle"
        static RowID = 9
    }
    static Mechanicslow = class {
        static Name = "Mechanic_Slow"
        static Cooldown = 300
        static Useeffect = "gadget_activate"
        static Aimguidetype = 3
        static Petareaeffect = "MechanicSlowArea"
        static Requirepetdistance = 12
        static Missingtargettext = "TID_ACCESSORY_BLOCKED_MISSING_TURRET"
        static Targettoofartext = "TID_ACCESSORY_BLOCKED_TURRET_TOO_FAR"
        static RowID = 10
    }
    static Hookdudepush = class {
        static Name = "HookDude_Push"
        static Type = "heal"
        static Subtype = 5
        static Cooldown = 400
        static Useeffect = "gadget_activate"
        static Aimguidetype = 1
        static Areaeffect = "HookDudePushback"
        static Skiptypecondition = true
        static Customvalue1 = 10
        static RowID = 11
    }
    static Clusterbombdudeextramines = class {
        static Name = "ClusterBombDude_ExtraMines"
        static Type = "next_attack_change"
        static Subtype = 8
        static Cooldown = 300
        static Useeffect = "gadget_activate"
        static Loopingeffect = "gadget_on_loop"
        static Activeticks = 100000
        static Customvalue1 = 6
        static RowID = 12
    }
    static Speedydash = class {
        static Name = "Speedy_Dash"
        static Type = "dash"
        static Cooldown = 300
        static Useeffect = "gadget_activate"
        static Loopingeffect = "gadget_max_dash"
        static Activeticks = 8
        static Interruptsaction = true
        static Shieldpercent = 100
        static Shieldticks = 10
        static Customvalue1 = 1000
        static Customvalue2 = 2400
        static RowID = 13
    }
    static Shotgungirldash = class {
        static Name = "ShotgunGirl_Dash"
        static Type = "dash_reload_ammo"
        static Cooldown = 260
        static Useeffect = "gadget_activate"
        static Loopingeffect = "gadget_max_dash"
        static Activeticks = 8
        static Interruptsaction = true
        static Customvalue1 = 1000
        static Customvalue2 = 2000
        static Customvalue3 = 300
        static RowID = 14
    }
    static Drillerspeedboost = class {
        static Name = "Driller_SpeedBoost"
        static Cooldown = 300
        static Useeffect = "gadget_activate"
        static Speedboost = 195
        static Speedboostticks = 80
        static RowID = 15
    }
    static Minigundudeburstheal = class {
        static Name = "MinigunDude_BurstHeal"
        static Cooldown = 240
        static Useeffect = "gadget_activate"
        static Aimguidetype = 3
        static Petareaeffect = "MinigunDudeTowerBurstHeal"
        static Requirepetdistance = 12
        static Missingtargettext = "TID_ACCESSORY_BLOCKED_MISSING_TURRET"
        static Targettoofartext = "TID_ACCESSORY_BLOCKED_TURRET_TOO_FAR"
        static RowID = 16
    }
    static Tntdudespin = class {
        static Name = "TntDude_Spin"
        static Type = "spin_shoot"
        static Cooldown = 240
        static Useeffect = "gadget_activate"
        static Activeticks = 40
        static Interruptsaction = true
        static Interruptable = true
        static Speedboost = 150
        static Speedboostticks = 40
        static Customobject = "TntDudeProjectile"
        static Customvalue1 = 2
        static Customvalue2 = 100
        static Customvalue3 = 150
        static Customvalue4 = 700
        static Customvalue5 = 100
        static RowID = 17
    }
    static Arcadeteleport = class {
        static Name = "Arcade_Teleport"
        static Type = "teleport_to_pet"
        static Cooldown = 360
        static Useeffect = "gadget_activate"
        static Activeticks = 10
        static Stopmovement = true
        static Interruptsaction = true
        static Requirepetdistance = 12
        static Customobject = "ArcadeTeleport"
        static Missingtargettext = "TID_ACCESSORY_BLOCKED_MISSING_TURRET"
        static Targettoofartext = "TID_ACCESSORY_BLOCKED_TURRET_TOO_FAR"
        static RowID = 18
    }
    static Barrelbotspin = class {
        static Name = "BarrelBot_Spin"
        static Type = "spin_shoot"
        static Cooldown = 240
        static Useeffect = "gadget_activate"
        static Loopingeffect = "darryl_def_atk"
        static Activeticks = 15
        static Interruptsaction = true
        static Interruptable = true
        static Customobject = "BarrelBotSpinProjectile"
        static Customvalue1 = 1
        static Customvalue2 = 25
        static Customvalue3 = 125
        static Customvalue4 = 2500
        static Customvalue5 = 0
        static Customvalue6 = 1000
        static RowID = 19
    }
    static Hammerdudeimmunity = class {
        static Name = "HammerDude_Immunity"
        static Type = "cc_immunity"
        static Cooldown = 360
        static Useeffect = "gadget_activate"
        static Loopingeffect = "gadget_frank_headphones"
        static Activeticks = 30
        static Allowstunactivation = true
        static Customvalue1 = 30
        static RowID = 20
    }
    static Whirlwindtrail = class {
        static Name = "Whirlwind_Trail"
        static Type = "next_attack_change"
        static Subtype = 13
        static Cooldown = 340
        static Useeffect = "gadget_activate"
        static Loopingeffect = "gadget_on_loop"
        static Activeticks = 100000
        static Customobject = "WhirlwindTrail"
        static Customvalue1 = 450
        static RowID = 21
    }
    static Bowdudetotem = class {
        static Name = "BowDude_Totem"
        static Type = "spawn"
        static Subtype = 1
        static Cooldown = 400
        static Useeffect = "gadget_activate"
        static Customobject = "BowDudeTotem"
        static RowID = 22
    }
    static Luchadorgrab = class {
        static Name = "Luchador_Grab"
        static Type = "throw_opponent"
        static Cooldown = 280
        static Useeffect = "gadget_activate"
        static Activeticks = 10
        static Stopmovement = true
        static Aimguidetype = 4
        static Interruptsaction = true
        static Interruptable = true
        static Range = 3
        static Requireenemyinrange = true
        static Customvalue1 = 300
        static RowID = 23
    }
    static Undertakerswing = class {
        static Name = "Undertaker_Swing"
        static Type = "spin_shoot"
        static Cooldown = 200
        static Useeffect = "gadget_activate"
        static Activeticks = 8
        static Aimguidetype = 1
        static Areaeffect = "UndertakerSwingDamage"
        static Interruptsaction = true
        static Customvalue1 = 100
        static RowID = 24
    }
    static Blackholevision = class {
        static Name = "BlackHole_Vision"
        static Type = "vision"
        static Cooldown = 400
        static Useeffect = "gadget_activate"
        static Loopingeffect = "gadget_tara_vision"
        static Activeticks = 80
        static Showcountdown = true
        static RowID = 25
    }
    static Deadmariachiregen = class {
        static Name = "DeadMariachi_Regen"
        static Cooldown = 400
        static Useeffect = "gadget_activate"
        static Aimguidetype = 1
        static Areaeffect = "PocoRegenArea"
        static RowID = 26
    }
    static Sniperhandgun = class {
        static Name = "Sniper_HandGun"
        static Type = "repeat_shot"
        static Subtype = 1
        static Cooldown = 360
        static Useeffect = "gadget_activate"
        static Activeticks = 5
        static Animationindex = 1
        static Setattackangle = true
        static Aimguidetype = 4
        static Interruptsaction = true
        static Range = 7
        static Requireenemyinrange = true
        static Customobject = "PiperHandgunProjectile"
        static Customvalue1 = 5
        static Customvalue2 = 5
        static RowID = 27
    }
    static Spawnerdudepromote = class {
        static Name = "SpawnerDude_Promote"
        static Type = "promote_minion"
        static Cooldown = 340
        static Useeffect = "gadget_activate"
        static Requirepetdistance = 12
        static Customvalue1 = 15
        static Customvalue2 = 20
        static Missingtargettext = "TID_ACCESSORY_BLOCKED_NO_PORTERS_IN_RANGE"
        static Targettoofartext = "TID_ACCESSORY_BLOCKED_NO_PORTERS_IN_RANGE"
        static Targetalreadyactivetext = "TID_ACCESSORY_BLOCKED_PORTER_ALREADY_PROMOTED"
        static RowID = 28
    }
    static Sandstormsleep = class {
        static Name = "Sandstorm_Sleep"
        static Type = "heal"
        static Subtype = 1
        static Cooldown = 220
        static Useeffect = "gadget_activate"
        static Loopingeffect = "gadget_sandy_sleep"
        static Activationdelay = 30
        static Showcountdown = true
        static Stopmovement = true
        static Interruptsaction = true
        static Interruptable = true
        static RowID = 29
    }
    static Beesniperslow = class {
        static Name = "BeeSniper_Slow"
        static Type = "spawn"
        static Subtype = 1
        static Cooldown = 400
        static Useeffect = "gadget_activate"
        static Customobject = "BeeSniperSlowPot"
        static RowID = 30
    }
    static Bulldudeheal = class {
        static Name = "BullDude_Heal"
        static Type = "heal"
        static Subtype = 1
        static Cooldown = 240
        static Useeffect = "gadget_activate"
        static Customvalue1 = 20
        static RowID = 31
    }
    static Gunslingerreload = class {
        static Name = "Gunslinger_Reload"
        static Type = "reload"
        static Cooldown = 220
        static Useeffect = "gadget_activate"
        static Customvalue1 = 200
        static RowID = 32
    }
    static Mummypush = class {
        static Name = "Mummy_Push"
        static Cooldown = 360
        static Useeffect = "gadget_activate"
        static Aimguidetype = 1
        static Areaeffect = "MummyAccessoryPushback"
        static RowID = 33
    }
    static Baseballheal = class {
        static Name = "Baseball_Heal"
        static Type = "heal"
        static Subtype = 2
        static Cooldown = 300
        static Useeffect = "gadget_activate"
        static Activeticks = 80
        static Customvalue1 = 10
        static RowID = 34
    }
    static Ninjafake = class {
        static Name = "Ninja_Fake"
        static Type = "spawn"
        static Subtype = 2
        static Cooldown = 260
        static Useeffect = "gadget_activate"
        static Customobject = "NinjaFake"
        static Customvalue1 = 100
        static Customvalue2 = 200
        static RowID = 35
    }
    static Blowertrampoline = class {
        static Name = "Blower_Trampoline"
        static Type = "spawn"
        static Subtype = 3
        static Cooldown = 400
        static Useeffect = "gadget_activate"
        static Customobject = "GaleSpringboard"
        static RowID = 36
    }
    static Controllerexplode = class {
        static Name = "Controller_Explode"
        static Type = "kill_projectile"
        static Cooldown = 260
        static Useeffect = "gadget_activate"
        static Customobject = "ArcadeTeleport"
        static Missingtargettext = "TID_ACCESSORY_BLOCKED_MISSING_GUIDED_PROJECTILE"
        static RowID = 37
    }
    static Powerlevelerblink = class {
        static Name = "PowerLeveler_Blink"
        static Type = "teleport_forward"
        static Cooldown = 400
        static Useeffect = "gadget_activate"
        static Activeticks = 5
        static Stopmovement = true
        static Interruptsaction = true
        static Customobject = "ArcadeTeleport"
        static Customvalue1 = 1000
        static RowID = 38
    }
    static Crowpoisontrigger = class {
        static Name = "Crow_PoisonTrigger"
        static Type = "poison_trigger"
        static Cooldown = 360
        static Useeffect = "gadget_activate"
        static Statuseffectenemy = "CrowPoison"
        static Customvalue1 = 350
        static Customvalue2 = 40
        static RowID = 39
    }
    static Artillerydudebarrage = class {
        static Name = "ArtilleryDude_Barrage"
        static Type = "turret_barrage"
        static Cooldown = 300
        static Useeffect = "gadget_activate"
        static Activeticks = 100
        static Requirepetdistance = 14
        static Range = 40
        static Targetindirect = true
        static Customvalue1 = 5
        static Customvalue2 = 500
        static Missingtargettext = "TID_ACCESSORY_BLOCKED_MISSING_TURRET"
        static Targettoofartext = "TID_ACCESSORY_BLOCKED_TURRET_TOO_FAR"
        static Customblocktext = "TID_ACCESSORY_BLOCKED_RANGE_TO_TURRET"
        static RowID = 40
    }
    static Shotgungirlfocus = class {
        static Name = "ShotgunGirl_Focus"
        static Type = "next_attack_change"
        static Subtype = 1
        static Cooldown = 320
        static Useeffect = "gadget_activate"
        static Loopingeffect = "gadget_on_loop"
        static Activeticks = 100
        static Customvalue1 = 20
        static Customvalue2 = 10
        static Customvalue3 = 1200
        static Targetalreadyactivetext = "TID_ACCESSORY_BLOCKED_ALREADY_ACTIVE"
        static RowID = 41
    }
    static Bowdudeminetrigger = class {
        static Name = "BowDude_MineTrigger"
        static Type = "mine_trigger"
        static Cooldown = 160
        static Useeffect = "gadget_activate"
        static Loopingeffectpet = "bo_002_ulti_trail"
        static Activeticks = 30
        static Missingtargettext = "TID_ACCESSORY_BLOCKED_MISSING_MINES"
        static Targetalreadyactivetext = "TID_ACCESSORY_BLOCKED_ALREADY_ACTIVE"
        static RowID = 42
    }
    static Undertakerreload = class {
        static Name = "Undertaker_Reload"
        static Type = "reload_speed"
        static Cooldown = 320
        static Useeffect = "gadget_activate"
        static Activeticks = 80
        static Usableduringcharge = 1
        static Customvalue1 = 80
        static Customvalue2 = 100
        static RowID = 43
    }
    static Sniperseeker = class {
        static Name = "Sniper_Seeker"
        static Type = "next_attack_change"
        static Subtype = 2
        static Cooldown = 360
        static Useeffect = "gadget_activate"
        static Loopingeffect = "gadget_on_loop"
        static Activeticks = 100000
        static Customobject = "SniperHomingProjectile"
        static Customvalue1 = 0
        static Customvalue2 = 0
        static Targetalreadyactivetext = "TID_ACCESSORY_BLOCKED_ALREADY_ACTIVE"
        static RowID = 44
    }
    static Luchadormeteor = class {
        static Name = "Luchador_Meteor"
        static Type = "spawn"
        static Subtype = 4
        static Cooldown = 260
        static Useeffect = "gadget_activate"
        static Aimguidetype = 4
        static Range = 10
        static Requireenemyinrange = true
        static Targetindirect = true
        static Customobject = "LuchadorMeteorSpawn"
        static Customvalue1 = 400
        static RowID = 45
    }
    static Barkeephealpotion = class {
        static Name = "Barkeep_HealPotion"
        static Type = "repeat_shot"
        static Subtype = 1
        static Cooldown = 340
        static Useeffect = "gadget_activate"
        static Activeticks = 30
        static Setattackangle = true
        static Aimguidetype = 4
        static Interruptsaction = true
        static Interruptable = true
        static Range = 10
        static Targetfriends = true
        static Targetindirect = true
        static Customobject = "BarkeepHealingProjectile"
        static Customvalue1 = 5
        static Customvalue2 = -15
        static Customvalue3 = 3000
        static RowID = 46
    }
    static Tntdudestun = class {
        static Name = "TntDude_Stun"
        static Type = "next_attack_change"
        static Subtype = 3
        static Cooldown = 460
        static Useeffect = "gadget_activate"
        static Loopingeffect = "gadget_on_loop"
        static Activeticks = 100000
        static Customvalue1 = 30
        static Targetalreadyactivetext = "TID_ACCESSORY_BLOCKED_ALREADY_ACTIVE"
        static RowID = 47
    }
    static Mechanicturretbuff = class {
        static Name = "Mechanic_TurretBuff"
        static Type = "pet_attack_speed"
        static Cooldown = 220
        static Useeffect = "gadget_activate"
        static Loopingeffectpet = "gadget_pet_on_loop"
        static Activeticks = 100
        static Showcountdown = true
        static Requirepetdistance = 12
        static Customvalue1 = 3
        static Missingtargettext = "TID_ACCESSORY_BLOCKED_MISSING_TURRET"
        static Targettoofartext = "TID_ACCESSORY_BLOCKED_TURRET_TOO_FAR"
        static RowID = 48
    }
    static Percenterstaticdamage = class {
        static Name = "Percenter_StaticDamage"
        static Type = "next_attack_change"
        static Subtype = 4
        static Cooldown = 200
        static Useeffect = "gadget_activate"
        static Loopingeffect = "gadget_on_loop"
        static Activeticks = 100000
        static Customvalue1 = 75
        static RowID = 49
    }
    static Firedudespill = class {
        static Name = "FireDude_Spill"
        static Type = "trail"
        static Cooldown = 300
        static Useeffect = "gadget_activate"
        static Activeticks = 60
        static Showcountdown = true
        static Areaeffect = "PetrolDistributionGadget"
        static Speedboost = 100
        static Speedboostticks = 60
        static Customobject = "PetrolDistributionTrail"
        static Customvalue1 = 200
        static RowID = 50
    }
    static Bulldudestomp = class {
        static Name = "BullDude_Stomp"
        static Type = "ulti_change"
        static Subtype = 9
        static Cooldown = 280
        static Useeffect = "gadget_activate"
        static Activeticks = 100000
        static Customobject = "BullStunArea"
        static Requiresspecificactiontext = "TID_ACCESSORY_BLOCKED_REQUIRES_BULLDOZER"
        static RowID = 51
    }
    static Speedyrewind = class {
        static Name = "Speedy_Rewind"
        static Type = "rewind"
        static Subtype = 1
        static Cooldown = 200
        static Useeffect = "gadget_activate"
        static Loopingeffect = "gadget_on_loop"
        static Activeticks = 60
        static Showcountdown = true
        static Areaeffect = "SpeedyRewindArea"
        static Customobject = "ArcadeTeleport"
        static Targetalreadyactivetext = "TID_ACCESSORY_BLOCKED_ALREADY_ACTIVE"
        static RowID = 52
    }
    static Beesniperextrabee = class {
        static Name = "BeeSniper_ExtraBee"
        static Type = "repeat_shot"
        static Subtype = 2
        static Cooldown = 480
        static Useeffect = "gadget_bea_circlingBea_active"
        static Activeticks = 16
        static Interruptable = true
        static Customobject = "BeeSniperCirclingProjectile"
        static Customvalue1 = 4
        static Customvalue2 = 75
        static RowID = 53
    }
    static Barrelbotslow = class {
        static Name = "BarrelBot_Slow"
        static Type = "following_area"
        static Cooldown = 300
        static Useeffect = "gadget_activate"
        static Activeticks = 100
        static Customobject = "BarrelBotSlowArea"
        static RowID = 54
    }
    static Shamanshield = class {
        static Name = "Shaman_Shield"
        static Type = "shield_pet"
        static Cooldown = 280
        static Useeffect = "gadget_activate"
        static Activeticks = 60
        static Showcountdown = true
        static Requirepetdistance = 12
        static Customvalue1 = 35
        static Missingtargettext = "TID_ACCESSORY_BLOCKED_MISSING_BEAR"
        static Targettoofartext = "TID_ACCESSORY_BLOCKED_BEAR_TOO_FAR"
        static RowID = 55
    }
    static Wallyreposition = class {
        static Name = "Wally_Reposition"
        static Type = "reposition_wall"
        static Cooldown = 300
        static Useeffect = "gadget_activate"
        static Missingtargettext = "TID_ACCESSORY_BLOCKED_REQUIRES_WALL"
        static RowID = 56
    }
    static Rocketgirlmegarocket = class {
        static Name = "RocketGirl_MegaRocket"
        static Type = "next_attack_change"
        static Subtype = 2
        static Cooldown = 300
        static Useeffect = "gadget_activate"
        static Loopingeffect = "gadget_on_loop"
        static Activeticks = 100000
        static Customobject = "RocketGirlGadgetProjectile"
        static Customvalue1 = 0
        static Customvalue2 = 0
        static Targetalreadyactivetext = "TID_ACCESSORY_BLOCKED_ALREADY_ACTIVE"
        static RowID = 57
    }
    static Whirlwindfly = class {
        static Name = "Whirlwind_Fly"
        static Type = "next_attack_change"
        static Subtype = 5
        static Cooldown = 380
        static Useeffect = "gadget_activate"
        static Loopingeffect = "gadget_on_loop"
        static Activeticks = 100000
        static Targetalreadyactivetext = "TID_ACCESSORY_BLOCKED_ALREADY_ACTIVE"
        static RowID = 58
    }
    static Arcadedouble = class {
        static Name = "Arcade_Double"
        static Type = "next_attack_change"
        static Subtype = 2
        static Cooldown = 220
        static Useeffect = "gadget_activate"
        static Loopingeffect = "gadget_on_loop"
        static Activeticks = 100000
        static Customvalue2 = 1800
        static Targetalreadyactivetext = "TID_ACCESSORY_BLOCKED_ALREADY_ACTIVE"
        static RowID = 59
    }
    static Gunslingerbigbullet = class {
        static Name = "Gunslinger_BigBullet"
        static Type = "next_attack_change"
        static Subtype = 2
        static Cooldown = 280
        static Useeffect = "gadget_activate"
        static Loopingeffect = "gadget_on_loop"
        static Activeticks = 100000
        static Customobject = "GunslingerBigProjectile"
        static Customvalue1 = 100
        static Customvalue2 = 100
        static Targetalreadyactivetext = "TID_ACCESSORY_BLOCKED_ALREADY_ACTIVE"
        static RowID = 60
    }
    static Icedudefreeze = class {
        static Name = "IceDude_Freeze"
        static Cooldown = 360
        static Useeffect = "gadget_activate"
        static Activeticks = 20
        static Stopmovement = true
        static Interruptsaction = true
        static Shieldpercent = 100
        static Shieldticks = 20
        static RowID = 61
    }
    static Snakeoilheal = class {
        static Name = "SnakeOil_Heal"
        static Type = "heal"
        static Subtype = 2
        static Cooldown = 340
        static Useeffect = "gadget_activate"
        static Activeticks = 60
        static Consumesammo = true
        static Customvalue1 = 25
        static RowID = 62
    }
    static Enragersuperboost = class {
        static Name = "Enrager_SuperBoost"
        static Type = "auto_super_load_boost"
        static Cooldown = 420
        static Useeffect = "gadget_activate"
        static Activeticks = 80
        static Customvalue1 = 525
        static RowID = 63
    }
    static Ruffscover = class {
        static Name = "Ruffs_Cover"
        static Type = "spawn"
        static Subtype = 5
        static Cooldown = 320
        static Useeffect = "gadget_activate"
        static Customobject = "RuffsCover"
        static Customvalue1 = 3
        static Customvalue2 = 400
        static Customvalue4 = 35
        static RowID = 64
    }
    static Rosabushcontrol = class {
        static Name = "Rosa_BushControl"
        static Type = "bush_slow"
        static Cooldown = 280
        static Useeffect = "gadget_activate"
        static Activeticks = 5
        static Customvalue1 = 350
        static Customvalue2 = 60
        static Customvalue3 = 30
        static RowID = 65
    }
    static Spawnerdudeextraporter = class {
        static Name = "SpawnerDude_ExtraPorter"
        static Type = "next_attack_change"
        static Subtype = 6
        static Cooldown = 340
        static Useeffect = "gadget_activate"
        static Loopingeffect = "gadget_on_loop"
        static Activeticks = 100000
        static Customobject = "SpawnerPetGadget"
        static RowID = 66
    }
    static Deadmariachicleanse = class {
        static Name = "DeadMariachi_Cleanse"
        static Cooldown = 360
        static Useeffect = "gadget_activate"
        static Aimguidetype = 1
        static Areaeffect = "PocoCleanseArea"
        static RowID = 67
    }
    static Hammerdudepull = class {
        static Name = "HammerDude_Pull"
        static Type = "next_attack_change"
        static Subtype = 7
        static Cooldown = 300
        static Useeffect = "gadget_activate"
        static Loopingeffect = "gadget_on_loop"
        static Activeticks = 100000
        static Customvalue1 = 150
        static Customvalue2 = 50
        static RowID = 68
    }
    static Hookdudehoming = class {
        static Name = "HookDude_Homing"
        static Type = "repeat_shot"
        static Subtype = 1
        static Cooldown = 400
        static Useeffect = "gadget_activate"
        static Loopingeffect = "gadget_on_loop"
        static Activeticks = 100
        static Aimguidetype = 4
        static Interruptable = true
        static Range = 11
        static Requireenemyinrange = true
        static Targetindirect = true
        static Customobject = "GeneHomingProjectile"
        static Customvalue1 = 5
        static Customvalue2 = 80
        static RowID = 69
    }
    static Controllerbounceback = class {
        static Name = "Controller_BounceBack"
        static Type = "return_damage"
        static Cooldown = 340
        static Useeffect = "gadget_activate"
        static Loopingeffect = "gadget_nani_reflect"
        static Activeticks = 40
        static Showcountdown = true
        static Customobject = "NaniBounceProjectile"
        static Customvalue1 = 80
        static Customvalue2 = -1
        static RowID = 70
    }
    static Drillerproto = class {
        static Name = "Driller_Proto"
        static Cooldown = 200
        static Useeffect = "gadget_activate"
        static RowID = 71
    }
    static Clusterbombdudeexplosion = class {
        static Name = "ClusterBombDude_Explosion"
        static Cooldown = 300
        static Useeffect = "gadget_activate"
        static Loopingeffect = "gadget_tick_explosion"
        static Activationdelay = 20
        static Aimguidetype = 1
        static Areaeffect = "TickGadgetExplosion"
        static Shieldpercent = 50
        static Shieldticks = 21
        static RowID = 72
    }
    static Blackholeshadows = class {
        static Name = "BlackHole_Shadows"
        static Type = "spawn"
        static Subtype = 5
        static Cooldown = 340
        static Useeffect = "gadget_activate"
        static Customobject = "BlackHolePetGadget"
        static Customvalue1 = 3
        static Customvalue2 = 400
        static Customvalue3 = 120
        static RowID = 73
    }
    static Baseballproto = class {
        static Name = "Baseball_Proto"
        static Cooldown = 200
        static Useeffect = "gadget_activate"
        static RowID = 74
    }
    static Rollerspeed = class {
        static Name = "Roller_Speed"
        static Type = "spawn"
        static Subtype = 1
        static Cooldown = 400
        static Useeffect = "gadget_activate"
        static Customobject = "SpeedBooster"
        static RowID = 75
    }
    static Electrosnipertrap = class {
        static Name = "ElectroSniper_Trap"
        static Type = "spawn"
        static Subtype = 3
        static Cooldown = 400
        static Useeffect = "gadget_activate"
        static Customobject = "ElectroTrap"
        static Customvalue1 = 30
        static RowID = 76
    }
    static Stickybombrange = class {
        static Name = "StickyBomb_Range"
        static Type = "next_attack_change"
        static Subtype = 2
        static Cooldown = 280
        static Useeffect = "gadget_activate"
        static Loopingeffect = "gadget_on_loop"
        static Activeticks = 100000
        static Customvalue1 = 50
        static Customvalue2 = 0
        static Customvalue3 = 23
        static RowID = 77
    }
    static Crossbombervision = class {
        static Name = "CrossBomber_Vision"
        static Type = "spawn"
        static Subtype = 1
        static Cooldown = 400
        static Useeffect = "gadget_activate"
        static Customobject = "CrossBomberVisionTower"
        static RowID = 78
    }
    static Ropedudeweakulti = class {
        static Name = "RopeDude_WeakUlti"
        static Type = "ulti_change"
        static Subtype = 1
        static Cooldown = 360
        static Useeffect = "gadget_activate"
        static Customvalue5 = 4000
        static Targetalreadyactivetext = "TID_ACCESSORY_BLOCKED_ULTI_ALREADY_CHARGED"
        static RowID = 79
    }
    static Assaultshotgunbomb = class {
        static Name = "AssaultShotgun_Bomb"
        static Type = "repeat_shot"
        static Subtype = 3
        static Cooldown = 320
        static Useeffect = "gadget_activate"
        static Activeticks = 5
        static Interruptsaction = true
        static Customobject = "AssaultShotgunGadgetProjectile"
        static Customvalue1 = 5
        static Customvalue2 = 250
        static RowID = 80
    }
    static Icedudeareafreeze = class {
        static Name = "IceDude_AreaFreeze"
        static Type = "trigger_ulti_area"
        static Cooldown = 360
        static Useeffect = "gadget_activate"
        static Customobject = "IceDudeGadgetActivationArea"
        static Customvalue1 = 50
        static Missingtargettext = "TID_ACCESSORY_BLOCKED_MISSING_LOU_ULTI"
        static Targettoofartext = "TID_ACCESSORY_BLOCKED_MISSING_OPPONENT_IN_AREA"
        static RowID = 81
    }
    static Rollermegastunt = class {
        static Name = "Roller_MegaStunt"
        static Type = "ulti_change"
        static Subtype = 2
        static Cooldown = 320
        static Useeffect = "gadget_activate"
        static Customobject = "RollerGadgetProjectile"
        static Customvalue1 = 20
        static Customvalue2 = 3
        static Customvalue3 = 200
        static Customvalue4 = 2000
        static Missingtargettext = "TID_ACCESSORY_BLOCKED_SUPER_REQUIRED"
        static Targetalreadyactivetext = "TID_ACCESSORY_BLOCKED_ALREADY_ACTIVE"
        static RowID = 82
    }
    static Ruffsairstrike = class {
        static Name = "Ruffs_AirStrike"
        static Type = "spawn"
        static Subtype = 4
        static Cooldown = 300
        static Useeffect = "gadget_activate"
        static Activeticks = 50
        static Aimguidetype = 4
        static Range = 10
        static Requireenemyinrange = true
        static Targetindirect = true
        static Customobject = "RuffsAirStrikeSpawn"
        static Customvalue1 = 100
        static Customvalue2 = 8
        static RowID = 83
    }
    static Enragerprotection = class {
        static Name = "Enrager_Protection"
        static Type = "consumable_shield"
        static Cooldown = 340
        static Useeffect = "gadget_activate"
        static Customvalue1 = 50
        static Customvalue2 = 140
        static Targetalreadyactivetext = "TID_ACCESSORY_BLOCKED_SHIELD_ALREADY_ACTIVE"
        static RowID = 84
    }
    static Minigundudeammosink = class {
        static Name = "MinigunDude_AmmoSink"
        static Type = "next_attack_change"
        static Subtype = 10
        static Cooldown = 340
        static Useeffect = "gadget_activate"
        static Loopingeffect = "gadget_on_loop"
        static Activeticks = 100000
        static Customvalue1 = 25
        static Customvalue2 = 50
        static RowID = 85
    }
    static Sandstormstunsleep = class {
        static Name = "Sandstorm_StunSleep"
        static Type = "next_attack_change"
        static Subtype = 11
        static Cooldown = 360
        static Useeffect = "gadget_activate"
        static Loopingeffect = "gadget_on_loop"
        static Activeticks = 100000
        static Customvalue1 = 20
        static RowID = 86
    }
    static Cactuscover = class {
        static Name = "Cactus_Cover"
        static Type = "spawn"
        static Subtype = 1
        static Cooldown = 280
        static Useeffect = "gadget_activate"
        static Customobject = "CactusCover"
        static Customvalue1 = 50
        static RowID = 87
    }
    static Blowerstopper = class {
        static Name = "Blower_Stopper"
        static Type = "spawn"
        static Subtype = 3
        static Cooldown = 420
        static Useeffect = "gadget_activate"
        static Customobject = "WindWall"
        static RowID = 88
    }
    static Ninjainvisiblearea = class {
        static Name = "Ninja_InvisibleArea"
        static Type = "spawn"
        static Subtype = 1
        static Cooldown = 400
        static Useeffect = "gadget_activate"
        static Customobject = "NinjaInvisibleArea"
        static RowID = 89
    }
    static Trickshotdudebounceheal = class {
        static Name = "TrickshotDude_BounceHeal"
        static Type = "next_attack_change"
        static Subtype = 9
        static Cooldown = 340
        static Useeffect = "gadget_activate"
        static Loopingeffect = "gadget_on_loop"
        static Activeticks = 100000
        static Customvalue1 = 40
        static RowID = 90
    }
    static Knightheal = class {
        static Name = "Knight_Heal"
        static Type = "heal"
        static Subtype = 3
        static Cooldown = 260
        static Useeffect = "gadget_activate"
        static Customvalue1 = 30
        static Targetalreadyactivetext = "TID_ACCESSORY_BLOCKED_REQUIRES_RAGE"
        static RowID = 91
    }
    static Mechadudeheal = class {
        static Name = "MechaDude_Heal"
        static Type = "heal"
        static Subtype = 4
        static Cooldown = 340
        static Useeffect = "gadget_activate"
        static Activeticks = 100
        static Customvalue1 = 7
        static Missingtargettext = "TID_ACCESSORY_BLOCKED_REQUIRES_MECHA"
        static RowID = 92
    }
    static Duplicatorstaticduplicate = class {
        static Name = "Duplicator_StaticDuplicate"
        static Type = "pet_control"
        static Subtype = 1
        static Cooldown = 220
        static Useeffect = "gadget_activate"
        static Loopingeffectpet = "gadget_pet_on_loop"
        static Activeticks = 80
        static Showcountdown = true
        static Requirepetdistance = 12
        static Customvalue1 = 50
        static Missingtargettext = "TID_ACCESSORY_BLOCKED_REQUIRES_DUPLICATE"
        static Targettoofartext = "TID_ACCESSORY_BLOCKED_DUPLICATE_TOO_FAR"
        static RowID = 93
    }
    static Kickerdudemines = class {
        static Name = "KickerDude_Mines"
        static Type = "spin_shoot"
        static Cooldown = 300
        static Useeffect = "gadget_activate"
        static Loopingeffect = "darryl_def_atk"
        static Activeticks = 15
        static Interruptsaction = true
        static Interruptable = true
        static Customobject = "KickerDudeMinesProjectile"
        static Customvalue1 = 2
        static Customvalue2 = 50
        static Customvalue3 = 40
        static Customvalue4 = 1500
        static Customvalue5 = 0
        static Customvalue6 = 0
        static RowID = 94
    }
    static OneOneNined51e112ac047a90d534ac9bf4f7ad52481f51 = class {
        static Name = "119d51e112ac047a90d534ac9bf4f7ad52481f51"
        static Cooldown = 300
        static Useeffect = "gadget_activate"
        static Shieldpercent = 40
        static Shieldticks = 60
        static RowID = 95
    }
    static Fleajump = class {
        static Name = "Flea_Jump"
        static Type = "spawn"
        static Subtype = 6
        static Cooldown = 340
        static Useeffect = "gadget_activate"
        static Customobject = "FleaExtraPet"
        static Customvalue1 = 20
        static Customvalue2 = 200
        static RowID = 96
    }
    static Fleasymbiosis = class {
        static Name = "Flea_Symbiosis"
        static Type = "swap_secondary_pet"
        static Cooldown = 220
        static Useeffect = "gadget_activate"
        static Petuseeffect = "flea_gadget_heal"
        static Activeticks = 20
        static Requirepetdistance = 12
        static Customobject = "FleaHealingPet"
        static Missingtargettext = "TID_ACCESSORY_BLOCKED_MISSING_BIG_EGG"
        static Targettoofartext = "TID_ACCESSORY_BLOCKED_BIG_EGG_TOO_FAR"
        static RowID = 97
    }
    static Duplicatorswap = class {
        static Name = "Duplicator_Swap"
        static Type = "teleport_to_pet"
        static Subtype = 2
        static Cooldown = 340
        static Useeffect = "gadget_activate"
        static Activeticks = 10
        static Stopmovement = true
        static Interruptsaction = true
        static Requirepetdistance = 12
        static Customobject = "DuplicatorSwapEffect"
        static Customvalue1 = 20
        static Missingtargettext = "TID_ACCESSORY_BLOCKED_MISSING_EGO"
        static Targettoofartext = "TID_ACCESSORY_BLOCKED_EGO_TOO_FAR"
        static RowID = 98
    }
    static Percenterlifesteal = class {
        static Name = "Percenter_Lifesteal"
        static Type = "next_attack_change"
        static Subtype = 2
        static Cooldown = 340
        static Useeffect = "gadget_activate"
        static Loopingeffect = "gadget_on_loop"
        static Activeticks = 100
        static Customobject = "PercenterLifestealProjectile"
        static Customvalue1 = 20
        static Customvalue2 = 0
        static Customvalue4 = -1
        static Targetalreadyactivetext = "TID_ACCESSORY_BLOCKED_ALREADY_ACTIVE"
        static RowID = 99
    }
    static Baseballsticky = class {
        static Name = "Baseball_Sticky"
        static Type = "ulti_change"
        static Subtype = 3
        static Cooldown = 200
        static Useeffect = "gadget_activate"
        static Activeticks = 100000
        static Customobject = "BaseballStickyProjectile;BaseballOverchargedUltiProjectileSticky"
        static Customvalue1 = 3
        static Customvalue5 = 0
        static Missingtargettext = "TID_ACCESSORY_BLOCKED_SUPER_REQUIRED"
        static Targetalreadyactivetext = "TID_ACCESSORY_BLOCKED_ALREADY_ACTIVE"
        static RowID = 100
    }
    static Mummyacid = class {
        static Name = "Mummy_Acid"
        static Type = "next_attack_change"
        static Subtype = 2
        static Cooldown = 220
        static Useeffect = "gadget_activate"
        static Loopingeffect = "gadget_on_loop"
        static Activeticks = 100000
        static Customobject = "MummyAcidProjectile"
        static Customvalue1 = -10
        static Customvalue2 = 0
        static Targetalreadyactivetext = "TID_ACCESSORY_BLOCKED_ALREADY_ACTIVE"
        static RowID = 101
    }
    static Crossbomberburst = class {
        static Name = "CrossBomber_Burst"
        static Type = "next_attack_change"
        static Subtype = 2
        static Cooldown = 300
        static Useeffect = "gadget_activate"
        static Loopingeffect = "gadget_on_loop"
        static Activeticks = 100000
        static Customvalue2 = 900
        static Targetalreadyactivetext = "TID_ACCESSORY_BLOCKED_ALREADY_ACTIVE"
        static RowID = 102
    }
    static Snakeoilspread = class {
        static Name = "SnakeOil_Spread"
        static Type = "next_attack_change"
        static Subtype = 14
        static Cooldown = 360
        static Useeffect = "gadget_activate"
        static Loopingeffect = "gadget_on_loop"
        static Activeticks = 100000
        static Statuseffectally = "SnakeOilGadgetHot"
        static Statuseffectenemy = "SnakeOilGadgetDot"
        static Customvalue1 = 3
        static Customvalue2 = 60
        static Targetalreadyactivetext = "TID_ACCESSORY_BLOCKED_ALREADY_ACTIVE"
        static RowID = 103
    }
    static Stickybombvision = class {
        static Name = "StickyBomb_Vision"
        static Type = "next_attack_change"
        static Subtype = 8
        static Cooldown = 400
        static Useeffect = "gadget_activate"
        static Loopingeffect = "gadget_on_loop"
        static Activeticks = 100000
        static Areaeffect = "StickyBombVisionArea"
        static Targetalreadyactivetext = "TID_ACCESSORY_BLOCKED_ALREADY_ACTIVE"
        static RowID = 104
    }
    static Electrosniperbounce = class {
        static Name = "ElectroSniper_Bounce"
        static Type = "next_attack_change"
        static Subtype = 2
        static Cooldown = 280
        static Useeffect = "gadget_activate"
        static Loopingeffect = "gadget_on_loop"
        static Activeticks = 100000
        static Customobject = "ElectroSniperBounceProjectile"
        static Targetalreadyactivetext = "TID_ACCESSORY_BLOCKED_ALREADY_ACTIVE"
        static RowID = 105
    }
    static Kickerdudesweep = class {
        static Name = "KickerDude_Sweep"
        static Type = "spin_shoot"
        static Cooldown = 320
        static Useeffect = "gadget_activate"
        static Activeticks = 8
        static Animationindex = 1
        static Aimguidetype = 1
        static Areaeffect = "KickerDudeSweepStun"
        static Interruptsaction = true
        static Customvalue1 = 100
        static RowID = 106
    }
    static Knightrage = class {
        static Name = "Knight_Rage"
        static Type = "take_damage"
        static Subtype = 2
        static Cooldown = 160
        static Useeffect = "gadget_activate"
        static Customvalue1 = 10
        static Customvalue2 = 40
        static Missingtargettext = "TID_ACCESSORY_BLOCKED_REQUIRES_HEALTH"
        static Targettoofartext = "TID_ACCESSORY_BLOCKED_RAGE_ALREADY_FULL"
        static Targetalreadyactivetext = "TID_ACCESSORY_BLOCKED_ALREADY_ACTIVE"
        static RowID = 107
    }
    static Jetpackgirldamagetower = class {
        static Name = "JetpackGirl_DamageTower"
        static Type = "spawn"
        static Subtype = 1
        static Cooldown = 400
        static Useeffect = "gadget_activate"
        static Customobject = "JetpackGirlDamageTower"
        static RowID = 108
    }
    static Jetpackgirljumpattack = class {
        static Name = "JetpackGirl_JumpAttack"
        static Type = "next_attack_change"
        static Subtype = 15
        static Cooldown = 320
        static Useeffect = "gadget_activate"
        static Loopingeffect = "gadget_on_loop"
        static Activeticks = 100000
        static Customvalue1 = 300
        static Targetalreadyactivetext = "TID_ACCESSORY_BLOCKED_ALREADY_ACTIVE"
        static RowID = 109
    }
    static Cannongirlspeed = class {
        static Name = "CannonGirl_Speed"
        static Type = "movement_speed"
        static Subtype = 1
        static Cooldown = 320
        static Useeffect = "gadget_activate"
        static Activeticks = 100
        static Customvalue1 = 30
        static Customvalue2 = 5
        static Missingtargettext = "TID_ACCESSORY_BLOCKED_REQUIRES_CANNON"
        static Targetalreadyactivetext = "TID_ACCESSORY_BLOCKED_ALREADY_ACTIVE"
        static RowID = 110
    }
    static Cannongirldash = class {
        static Name = "CannonGirl_Dash"
        static Type = "dash"
        static Subtype = 1
        static Cooldown = 200
        static Useeffect = "gadget_activate"
        static Loopingeffect = "gadget_max_dash"
        static Activeticks = 8
        static Interruptsaction = true
        static Customvalue1 = 600
        static Customvalue2 = 2000
        static Customvalue3 = 130
        static Customvalue4 = 200
        static Missingtargettext = "TID_ACCESSORY_BLOCKED_REQUIRES_ASSASSIN"
        static RowID = 111
    }
    static Powerlevelerextralevels = class {
        static Name = "PowerLeveler_ExtraLevels"
        static Type = "extra_power_levels"
        static Cooldown = 300
        static Useeffect = "gadget_activate"
        static Loopingeffect = "gadget_on_loop"
        static Activeticks = 200
        static Showcountdown = true
        static Customvalue1 = 1
        static Targetalreadyactivetext = "TID_ACCESSORY_BLOCKED_ALREADY_MAX_LEVEL"
        static RowID = 112
    }
    static Powerlevelershield = class {
        static Name = "PowerLeveler_Shield"
        static Type = "reload_shield"
        static Cooldown = 340
        static Useeffect = "gadget_activate"
        static Loopingeffect = "gadget_nani_reflect"
        static Activeticks = 40
        static Showcountdown = true
        static Customvalue1 = 50
        static Customvalue2 = 2
        static RowID = 113
    }
    static Drillerrebuild = class {
        static Name = "Driller_Rebuild"
        static Type = "respawn_environment"
        static Cooldown = 220
        static Useeffect = "gadget_activate"
        static Aimguidetype = 5
        static Range = 1
        static Customobject = "DrillerRebuildEffect"
        static Targetalreadyactivetext = "TID_ACCESSORY_BLOCKED_ALREADY_ACTIVE"
        static RowID = 114
    }
    static Assaultshotgunprojectiles = class {
        static Name = "AssaultShotgun_Projectiles"
        static Type = "next_attack_change"
        static Subtype = 2
        static Cooldown = 220
        static Useeffect = "gadget_activate"
        static Loopingeffect = "gadget_on_loop"
        static Activeticks = 100000
        static Customvalue2 = 850
        static Targetalreadyactivetext = "TID_ACCESSORY_BLOCKED_ALREADY_ACTIVE"
        static RowID = 115
    }
    static Firedudeflameshield = class {
        static Name = "FireDude_FlameShield"
        static Type = "repeat_shot"
        static Subtype = 4
        static Cooldown = 280
        static Useeffect = "gadget_activate"
        static Loopingeffect = "gadget_amber_fire"
        static Activeticks = 1
        static Interruptable = true
        static Customobject = "FlameDudeCirclingProjectile"
        static Customvalue1 = 1
        static Customvalue2 = 450
        static Customvalue3 = 3
        static RowID = 116
    }
    static Mechadudereloadtower = class {
        static Name = "MechaDude_ReloadTower"
        static Type = "spawn"
        static Subtype = 1
        static Cooldown = 380
        static Useeffect = "gadget_activate"
        static Customobject = "MechaDudeReloadTower"
        static RowID = 117
    }
    static Ropedudevision = class {
        static Name = "RopeDude_Vision"
        static Type = "vision"
        static Subtype = 1
        static Cooldown = 400
        static Useeffect = "gadget_activate"
        static Loopingeffect = "gadget_on_loop"
        static Activeticks = 240
        static Showcountdown = true
        static Targetalreadyactivetext = "TID_ACCESSORY_BLOCKED_ALREADY_ACTIVE"
        static RowID = 118
    }
    static Silencermine = class {
        static Name = "Silencer_Mine"
        static Type = "ulti_change"
        static Subtype = 4
        static Cooldown = 220
        static Useeffect = "gadget_activate"
        static Activeticks = 100000
        static Customobject = "SilencerHuggerMine"
        static Missingtargettext = "TID_ACCESSORY_BLOCKED_SUPER_REQUIRED"
        static RowID = 119
    }
    static Silencerbigprojectiles = class {
        static Name = "Silencer_BigProjectiles"
        static Type = "next_attack_change"
        static Subtype = 2
        static Cooldown = 340
        static Useeffect = "gadget_activate"
        static Loopingeffect = "gadget_on_loop"
        static Activeticks = 100000
        static Customobject = "SilencerBigProjectile"
        static Customvalue1 = 100
        static Customvalue2 = 150
        static Customvalue4 = 125
        static Targetalreadyactivetext = "TID_ACCESSORY_BLOCKED_ALREADY_ACTIVE"
        static RowID = 120
    }
    static Weaponthrowerpull = class {
        static Name = "WeaponThrower_Pull"
        static Type = "item_area_trigger"
        static Cooldown = 340
        static Useeffect = "gadget_activate"
        static Activeticks = 50
        static Areaeffect = "WeaponThrowerPullArea"
        static Range = 14
        static Missingtargettext = "TID_ACCESSORY_BLOCKED_MISSING_GAUNTLETS"
        static Targettoofartext = "TID_ACCESSORY_BLOCKED_GAUNTLETS_TOO_FAR"
        static Targetalreadyactivetext = "TID_ACCESSORY_BLOCKED_ALREADY_ACTIVE"
        static RowID = 121
    }
    static Weaponthrowerexplode = class {
        static Name = "WeaponThrower_Explode"
        static Type = "ulti_change"
        static Subtype = 5
        static Cooldown = 220
        static Useeffect = "gadget_activate"
        static Activeticks = 50
        static Range = 14
        static Customobject = "WeaponThrowerExplosion"
        static Missingtargettext = "TID_ACCESSORY_BLOCKED_SUPER_REQUIRED"
        static Targetalreadyactivetext = "TID_ACCESSORY_BLOCKED_ALREADY_ACTIVE"
        static Requiresspecificactiontext = "TID_ACCESSORY_BLOCKED_GAUNTLETS_REQUIRED"
        static RowID = 122
    }
    static Soulcollectorexplodesouls = class {
        static Name = "SoulCollector_ExplodeSouls"
        static Type = "explode_souls"
        static Cooldown = 320
        static Useeffect = "gadget_activate"
        static Activeticks = 50
        static Areaeffect = "SoulCollectorSoulExplosion"
        static Range = 14
        static Missingtargettext = "TID_ACCESSORY_BLOCKED_MISSING_SOULS"
        static Targettoofartext = "TID_ACCESSORY_BLOCKED_SOULS_TOO_FAR"
        static Targetalreadyactivetext = "TID_ACCESSORY_BLOCKED_ALREADY_ACTIVE"
        static RowID = 123
    }
    static Soulcollectorselfdamage = class {
        static Name = "SoulCollector_SelfDamage"
        static Type = "take_damage"
        static Subtype = 3
        static Cooldown = 200
        static Useeffect = "gadget_activate"
        static Customvalue1 = 5
        static Customvalue2 = 100
        static Missingtargettext = "TID_ACCESSORY_BLOCKED_REQUIRES_HEALTH"
        static Targettoofartext = "TID_ACCESSORY_BLOCKED_SPIRIT_ALREADY_FULL"
        static Targetalreadyactivetext = "TID_ACCESSORY_BLOCKED_ALREADY_ACTIVE"
        static RowID = 124
    }
    static Shieldtankheal = class {
        static Name = "ShieldTank_Heal"
        static Type = "heal"
        static Subtype = 6
        static Cooldown = 320
        static Useeffect = "gadget_activate"
        static Areaeffect = "ShieldTankHeal"
        static Missingtargettext = "TID_ACCESSORY_BLOCKED_SUPER_REQUIRED"
        static Targetalreadyactivetext = "TID_ACCESSORY_BLOCKED_ALREADY_ACTIVE"
        static RowID = 125
    }
    static Shieldtankpull = class {
        static Name = "ShieldTank_Pull"
        static Type = "next_attack_change"
        static Subtype = 7
        static Cooldown = 340
        static Useeffect = "gadget_activate"
        static Loopingeffect = "gadget_on_loop"
        static Activeticks = 100000
        static Customvalue1 = 150
        static Customvalue3 = 250
        static Targetalreadyactivetext = "TID_ACCESSORY_BLOCKED_ALREADY_ACTIVE"
        static RowID = 126
    }
    static Jesterrerollulti = class {
        static Name = "Jester_ReRollUlti"
        static Type = "random_ulti"
        static Cooldown = 240
        static Useeffect = "gadget_activate"
        static Missingtargettext = "TID_ACCESSORY_BLOCKED_SUPER_REQUIRED"
        static RowID = 127
    }
    static Jesterrandombuff = class {
        static Name = "Jester_RandomBuff"
        static Type = "random_buff"
        static Cooldown = 300
        static Useeffect = "gadget_activate"
        static Customvalue1 = 100
        static Customvalue2 = 25
        static Customvalue3 = 420
        static Customvalue4 = 200
        static Customvalue5 = 150
        static RowID = 128
    }
    static Doormanpuller = class {
        static Name = "DoorMan_Puller"
        static Type = "next_attack_change"
        static Subtype = 17
        static Cooldown = 460
        static Useeffect = "gadget_activate"
        static Loopingeffect = "gadget_on_loop"
        static Activeticks = 100000
        static Range = 14
        static Customobject = "DoorManCaneGadgetProjectile"
        static Targetalreadyactivetext = "TID_ACCESSORY_BLOCKED_ALREADY_ACTIVE"
        static RowID = 129
    }
    static Doormandamagedrop = class {
        static Name = "DoorMan_DamageDrop"
        static Type = "next_attack_change"
        static Subtype = 8
        static Cooldown = 280
        static Useeffect = "gadget_activate"
        static Loopingeffect = "gadget_on_loop"
        static Activeticks = 100000
        static Areaeffect = "DoorManDamageDropWarning"
        static Customvalue2 = 1
        static Targetalreadyactivetext = "TID_ACCESSORY_BLOCKED_ALREADY_ACTIVE"
        static RowID = 130
    }
    static Beamerslow = class {
        static Name = "Beamer_Slow"
        static Type = "next_attack_change"
        static Subtype = 7
        static Cooldown = 260
        static Useeffect = "gadget_activate"
        static Loopingeffect = "gadget_on_loop"
        static Activeticks = 100000
        static Customvalue3 = 350
        static Customvalue4 = 50
        static Customvalue5 = 1
        static Targetalreadyactivetext = "TID_ACCESSORY_BLOCKED_ALREADY_ACTIVE"
        static RowID = 131
    }
    static Beamerpierce = class {
        static Name = "Beamer_Pierce"
        static Type = "next_attack_change"
        static Subtype = 16
        static Cooldown = 320
        static Useeffect = "gadget_activate"
        static Loopingeffect = "gadget_on_loop"
        static Activeticks = 100000
        static Customvalue1 = 1
        static Customvalue2 = 1
        static Targetalreadyactivetext = "TID_ACCESSORY_BLOCKED_ALREADY_ACTIVE"
        static RowID = 132
    }
    static Splitterchargeulti = class {
        static Name = "Splitter_ChargeUlti"
        static Type = "charge_ulti"
        static Cooldown = 400
        static Useeffect = "gadget_activate"
        static Customvalue1 = 100
        static RowID = 133
    }
    static Splittertriggertags = class {
        static Name = "Splitter_TriggerTags"
        static Type = "trigger_tags"
        static Cooldown = 300
        static Useeffect = "gadget_activate"
        static Statuseffectenemy = "SplitterTag"
        static Customobject = "SplitterTagExplosion"
        static RowID = 134
    }
    static Puppeteermoredamage = class {
        static Name = "Puppeteer_MoreDamage"
        static Type = "next_attack_change"
        static Subtype = 18
        static Cooldown = 260
        static Useeffect = "gadget_activate"
        static Loopingeffect = "gadget_on_loop"
        static Activeticks = 100000
        static Areaeffect = "PuppeteerPoisonAlternative"
        static Customvalue1 = 25
        static Targetalreadyactivetext = "TID_ACCESSORY_BLOCKED_ALREADY_ACTIVE"
        static RowID = 135
    }
    static Puppeteerdive = class {
        static Name = "Puppeteer_Dive"
        static Type = "dive"
        static Cooldown = 320
        static Useeffect = "gadget_activate"
        static Activeticks = 40
        static Stopmovement = true
        static Areaeffect = "PuppeteerDive"
        static Interruptsaction = true
        static RowID = 136
    }
    static Maisiedash = class {
        static Name = "Maisie_Dash"
        static Type = "dash"
        static Cooldown = 320
        static Useeffect = "gadget_activate"
        static Loopingeffect = "gadget_max_dash"
        static Activeticks = 8
        static Aimguidetype = 1
        static Areaeffect = "MaisieDashArea"
        static Customvalue1 = 800
        static Customvalue2 = 3000
        static RowID = 137
    }
    static Maisiereloadanddamage = class {
        static Name = "Maisie_ReloadAndDamage"
        static Type = "next_attack_change"
        static Subtype = 19
        static Cooldown = 200
        static Useeffect = "gadget_activate"
        static Loopingeffect = "gadget_on_loop"
        static Activeticks = 100000
        static Customvalue1 = 100
        static Customvalue2 = 30
        static Targetalreadyactivetext = "TID_ACCESSORY_BLOCKED_ALREADY_ACTIVE"
        static RowID = 138
    }
    static Fishtankslow = class {
        static Name = "FishTank_Slow"
        static Type = "next_attack_change"
        static Subtype = 20
        static Cooldown = 220
        static Useeffect = "gadget_activate"
        static Loopingeffect = "gadget_on_loop"
        static Activeticks = 100000
        static Customvalue1 = 60
        static Customvalue2 = 350
        static Targetalreadyactivetext = "TID_ACCESSORY_BLOCKED_ALREADY_ACTIVE"
        static RowID = 139
    }
    static Fishtankshield = class {
        static Name = "FishTank_Shield"
        static Cooldown = 360
        static Useeffect = "gadget_activate"
        static Shieldpercent = 40
        static Shieldticks = 60
        static Targetalreadyactivetext = "TID_ACCESSORY_BLOCKED_ALREADY_ACTIVE"
        static RowID = 140
    }
    static Duelistjump = class {
        static Name = "Duelist_Jump"
        static Type = "jump"
        static Cooldown = 360
        static Useeffect = "gadget_activate"
        static Interruptsaction = true
        static Customvalue1 = 150
        static Customvalue2 = 50
        static RowID = 141
    }
    static Duelistsilence = class {
        static Name = "Duelist_Silence"
        static Type = "next_attack_change"
        static Subtype = 2
        static Cooldown = 360
        static Useeffect = "gadget_activate"
        static Loopingeffect = "gadget_on_loop"
        static Activeticks = 100000
        static Customobject = "DuelistSilenceProjectile"
        static Customvalue2 = 200
        static Targetalreadyactivetext = "TID_ACCESSORY_BLOCKED_ALREADY_ACTIVE"
        static RowID = 142
    }
    static Reviveronlydoubleheal = class {
        static Name = "Reviver_OnlyDoubleHeal"
        static Type = "next_attack_change"
        static Subtype = 21
        static Cooldown = 300
        static Useeffect = "gadget_activate"
        static Loopingeffect = "gadget_on_loop"
        static Activeticks = 100000
        static Customobject = "ReviverDamageAreaDoubleHeal"
        static Targetalreadyactivetext = "TID_ACCESSORY_BLOCKED_ALREADY_ACTIVE"
        static RowID = 143
    }
    static Reviveronlydoubledamage = class {
        static Name = "Reviver_OnlyDoubleDamage"
        static Type = "next_attack_change"
        static Subtype = 21
        static Cooldown = 300
        static Useeffect = "gadget_activate"
        static Loopingeffect = "gadget_on_loop"
        static Activeticks = 100000
        static Customobject = "ReviverDamageAreaDoubleDamage"
        static Targetalreadyactivetext = "TID_ACCESSORY_BLOCKED_ALREADY_ACTIVE"
        static RowID = 144
    }
    static Cookerpoison = class {
        static Name = "Cooker_Poison"
        static Type = "next_attack_change"
        static Subtype = 23
        static Cooldown = 300
        static Useeffect = "gadget_activate"
        static Loopingeffect = "gadget_on_loop"
        static Activeticks = 100000
        static Statuseffectenemy = "CookerGadgetDot"
        static Targetalreadyactivetext = "TID_ACCESSORY_BLOCKED_ALREADY_ACTIVE"
        static RowID = 145
    }
    static Cookerhealing = class {
        static Name = "Cooker_Healing"
        static Type = "next_attack_change"
        static Subtype = 24
        static Cooldown = 220
        static Useeffect = "gadget_activate"
        static Loopingeffect = "gadget_on_loop"
        static Activeticks = 100000
        static Statuseffectally = "CookerGadgetHot"
        static Targetalreadyactivetext = "TID_ACCESSORY_BLOCKED_ALREADY_ACTIVE"
        static RowID = 146
    }
    static Conductorremovesign = class {
        static Name = "Conductor_RemoveSign"
        static Type = "remove_item_and_ulti"
        static Subtype = 1
        static Cooldown = 200
        static Useeffect = "gadget_activate"
        static Customvalue1 = 100
        static Missingtargettext = "TID_ACCESSORY_BLOCKED_MISSING_SIGN"
        static Targetalreadyactivetext = "TID_ACCESSORY_BLOCKED_ULTI_ALREADY_CHARGED"
        static RowID = 147
    }
    static Conductorpasswalls = class {
        static Name = "Conductor_PassWalls"
        static Type = "ulti_change"
        static Subtype = 7
        static Cooldown = 340
        static Useeffect = "gadget_activate"
        static Activeticks = 50
        static Missingtargettext = "TID_ACCESSORY_BLOCKED_SUPER_REQUIRED"
        static Targetalreadyactivetext = "TID_ACCESSORY_BLOCKED_ALREADY_ACTIVE"
        static RowID = 148
    }
    static Cocoonerspawnpets = class {
        static Name = "Cocooner_SpawnPets"
        static Type = "spawn"
        static Subtype = 5
        static Cooldown = 400
        static Useeffect = "gadget_activate"
        static Customobject = "CocoonerPet"
        static Customvalue1 = 3
        static Customvalue2 = 350
        static RowID = 149
    }
    static Cocoonercocoonself = class {
        static Name = "Cocooner_CocoonSelf"
        static Type = "cocoon_self"
        static Cooldown = 300
        static Useeffect = "gadget_activate"
        static Activeticks = 40
        static Stopmovement = true
        static Interruptsaction = true
        static Customobject = "CocoonerCocoon"
        static Customvalue1 = 50
        static Customvalue2 = 100
        static Targetalreadyactivetext = "TID_ACCESSORY_BLOCKED_ALREADY_COCOONED"
        static RowID = 150
    }
    static Leapershotgun = class {
        static Name = "Leaper_Shotgun"
        static Type = "repeat_shot"
        static Subtype = 5
        static Cooldown = 300
        static Useeffect = "gadget_activate"
        static Activeticks = 5
        static Animationindex = 1
        static Setattackangle = true
        static Aimguidetype = 4
        static Range = 9
        static Requireenemyinrange = true
        static Customobject = "LeaperShotgunProjectile"
        static Customvalue1 = 5
        static Customvalue2 = 25
        static Customvalue3 = 3
        static Customvalue4 = 40
        static RowID = 151
    }
    static Leaperlongerjump = class {
        static Name = "Leaper_LongerJump"
        static Type = "next_attack_change"
        static Subtype = 25
        static Cooldown = 280
        static Useeffect = "gadget_activate"
        static Activeticks = 100000
        static Customvalue1 = 34
        static Targetalreadyactivetext = "TID_ACCESSORY_BLOCKED_ALREADY_ACTIVE"
        static RowID = 152
    }
    static Attachercardboardbox = class {
        static Name = "Attacher_Cardboardbox"
        static Type = "invisible"
        static Subtype = 1
        static Cooldown = 400
        static Useeffect = "kit_def_gadget"
        static Loopingeffect = "kit_def_gadget_loop"
        static Activeticks = 60
        static Animationindex = 1
        static Customvalue1 = 100
        static Targetalreadyactivetext = "TID_ACCESSORY_BLOCKED_ALREADY_ACTIVE"
        static RowID = 153
    }
    static Attachercheeseburger = class {
        static Name = "Attacher_Cheeseburger"
        static Type = "heal_attached_and_self"
        static Cooldown = 300
        static Useeffect = "gadget_activate"
        static Customvalue1 = 30
        static Missingtargettext = "TID_ACCESSORY_BLOCKED_NOT_ATTACHED"
        static RowID = 154
    }
    static Twinsswapskill = class {
        static Name = "Twins_SwapSkill"
        static Type = "swap_skill_with_pet"
        static Cooldown = 240
        static Useeffect = "gadget_activate"
        static Missingtargettext = "TID_ACCESSORY_BLOCKED_MISSING_TWIN"
        static RowID = 155
    }
    static Twinsdash = class {
        static Name = "Twins_Dash"
        static Type = "dash"
        static Subtype = 2
        static Cooldown = 340
        static Useeffect = "gadget_activate"
        static Loopingeffect = "gadget_max_dash"
        static Activeticks = 8
        static Customvalue1 = 800
        static Customvalue2 = 3000
        static Customvalue3 = 25
        static Missingtargettext = "TID_ACCESSORY_BLOCKED_MISSING_TWIN"
        static RowID = 156
    }
    static Axejugglerprojectilespeed = class {
        static Name = "AxeJuggler_ProjectileSpeed"
        static Type = "chained_proj_speed"
        static Cooldown = 280
        static Useeffect = "gadget_activate"
        static Loopingeffect = "gadget_on_loop"
        static Activeticks = 100
        static Customvalue1 = 25
        static Customvalue2 = 60
        static Missingtargettext = "TID_AXE_JUGGLER_ACCESSORY_BLOCKED_MISSING_NOTES"
        static Targetalreadyactivetext = "TID_ACCESSORY_BLOCKED_ALREADY_ACTIVE"
        static RowID = 157
    }
    static Axejugglershield = class {
        static Name = "AxeJuggler_Shield"
        static Type = "consumable_shield"
        static Subtype = 1
        static Cooldown = 380
        static Useeffect = "gadget_activate"
        static Customvalue1 = 10
        static Customvalue2 = 140
        static Missingtargettext = "TID_AXE_JUGGLER_ACCESSORY_BLOCKED_MISSING_NOTES"
        static Targetalreadyactivetext = "TID_ACCESSORY_BLOCKED_SHIELD_ALREADY_ACTIVE"
        static RowID = 158
    }
    static Insectmanfly = class {
        static Name = "InsectMan_Fly"
        static Type = "activate_skill"
        static Cooldown = 360
        static Useeffect = "gadget_activate"
        static Loopingeffect = "gadget_on_loop"
        static Activeticks = 20
        static Customobject = "InsectManChargeGadget"
        static Targetalreadyactivetext = "TID_ACCESSORY_BLOCKED_ALREADY_ACTIVE"
        static RowID = 159
    }
    static Insectmanpierce = class {
        static Name = "InsectMan_Pierce"
        static Type = "next_attack_change"
        static Subtype = 16
        static Cooldown = 360
        static Useeffect = "gadget_activate"
        static Loopingeffect = "gadget_on_loop"
        static Activeticks = 100000
        static Customvalue1 = 1
        static Customvalue2 = 1
        static Targetalreadyactivetext = "TID_ACCESSORY_BLOCKED_ALREADY_ACTIVE"
        static RowID = 160
    }
    static Dragonriderknockup = class {
        static Name = "DragonRider_KnockUp"
        static Type = "next_attack_change"
        static Subtype = 27
        static Cooldown = 220
        static Useeffect = "gadget_activate"
        static Loopingeffect = "gadget_on_loop"
        static Activeticks = 100000
        static Range = 7
        static Customvalue1 = 20
        static Customvalue2 = 50
        static Targetalreadyactivetext = "TID_ACCESSORY_BLOCKED_ALREADY_ACTIVE"
        static RowID = 161
    }
    static Dragonriderlaststand = class {
        static Name = "DragonRider_LastStand"
        static Type = "give_buff_to_self"
        static Cooldown = 440
        static Useeffect = "gadget_activate"
        static Activeticks = 40
        static Customvalue1 = 21
        static RowID = 162
    }
    static Ambushershadowrealm = class {
        static Name = "Ambusher_ShadowRealm"
        static Type = "shadowrealm_transfer_self"
        static Cooldown = 440
        static Useeffect = "gadget_activate"
        static Activeticks = 5
        static Interruptsaction = true
        static Customvalue1 = 60
        static RowID = 163
    }
    static Ambusherteleportgrenade = class {
        static Name = "Ambusher_TeleportGrenade"
        static Type = "ulti_change"
        static Subtype = 8
        static Cooldown = 200
        static Useeffect = "gadget_activate"
        static Activeticks = 100000
        static Customobject = "AmbusherUlti2"
        static Missingtargettext = "TID_ACCESSORY_BLOCKED_SUPER_REQUIRED"
        static Targetalreadyactivetext = "TID_ACCESSORY_BLOCKED_ALREADY_ACTIVE"
        static RowID = 164
    }
    static Painterpush = class {
        static Name = "Painter_Push"
        static Type = "spin_shoot"
        static Cooldown = 340
        static Useeffect = "gadget_activate"
        static Activeticks = 8
        static Animationindex = 1
        static Aimguidetype = 1
        static Areaeffect = "PainterAccessoryArea"
        static Interruptsaction = true
        static Customvalue1 = 100
        static RowID = 165
    }
    static Painterareaduration = class {
        static Name = "Painter_AreaDuration"
        static Type = "next_attack_change"
        static Subtype = 28
        static Cooldown = 240
        static Useeffect = "gadget_activate"
        static Loopingeffect = "gadget_on_loop"
        static Activeticks = 100000
        static Customvalue1 = 100
        static Targetalreadyactivetext = "TID_ACCESSORY_BLOCKED_ALREADY_ACTIVE"
        static RowID = 166
    }
    static Crabdoubletokens = class {
        static Name = "Crab_DoubleTokens"
        static Type = "give_buff_to_self"
        static Cooldown = 300
        static Useeffect = "gadget_activate"
        static Activeticks = 100
        static Customvalue1 = 22
        static Customvalue2 = 2
        static Targetalreadyactivetext = "TID_ACCESSORY_BLOCKED_ALREADY_MAX_LEVEL"
        static RowID = 167
    }
    static Crabdash = class {
        static Name = "Crab_Dash"
        static Type = "dash"
        static Subtype = 3
        static Cooldown = 320
        static Useeffect = "gadget_activate"
        static Loopingeffect = "gadget_max_dash"
        static Activeticks = 8
        static Interruptsaction = true
        static Customvalue1 = 1000
        static Customvalue2 = 3000
        static Customvalue3 = 100
        static RowID = 168
    }
    static Diggertreasure = class {
        static Name = "Digger_Treasure"
        static Type = "give_buff_to_self"
        static Cooldown = 260
        static Useeffect = "digger_dig_treasure"
        static Activeticks = 100
        static Customvalue1 = 17
        static Customvalue2 = 50
        static Missingtargettext = "TID_ACCESSORY_BLOCKED_CANT_BE_DRILL"
        static RowID = 169
    }
    static Diggerdash = class {
        static Name = "Digger_Dash"
        static Type = "dash"
        static Subtype = 4
        static Cooldown = 320
        static Useeffect = "gadget_activate"
        static Loopingeffect = "gadget_max_dash"
        static Activeticks = 8
        static Interruptsaction = true
        static Customvalue1 = 1000
        static Customvalue2 = 2000
        static Customvalue3 = 100
        static Missingtargettext = "TID_ACCESSORY_BLOCKED_MUST_BE_DRILL"
        static RowID = 170
    }
    static Samuraioneattackonly = class {
        static Name = "Samurai_OneAttackOnly"
        static Type = "give_buff_to_self"
        static Cooldown = 300
        static Useeffect = "gadget_activate"
        static Activeticks = 60
        static Customvalue1 = 26
        static RowID = 171
    }
    static Samuraihealdamagetaken = class {
        static Name = "Samurai_HealDamageTaken"
        static Type = "heal_damage_taken"
        static Cooldown = 340
        static Useeffect = "samurai_def_gadget2"
        static Customvalue1 = 60
        static Customvalue2 = 50
        static RowID = 172
    }
    static Ghostincreasedrange = class {
        static Name = "Ghost_IncreasedRange"
        static Type = "next_attack_change"
        static Subtype = 25
        static Cooldown = 300
        static Useeffect = "gadget_activate"
        static Loopingeffect = "gadget_on_loop"
        static Activeticks = 100000
        static Customvalue1 = 50
        static RowID = 173
    }
    static Ghostspooky = class {
        static Name = "Ghost_Spooky"
        static Cooldown = 180
        static Useeffect = "gadget_activate"
        static Areaeffect = "GhostSpookyArea"
        static Customvalue1 = 60
        static Customvalue2 = 75
        static RowID = 174
    }
    static Voodooallbuffsattack = class {
        static Name = "Voodoo_AllBuffsAttack"
        static Type = "swap_weapon_skill"
        static Cooldown = 280
        static Useeffect = "gadget_activate"
        static Loopingeffect = "gadget_on_loop"
        static Activeticks = 100000
        static Customobject = "VoodooWeaponAll"
        static Customvalue6 = 1
        static Targetalreadyactivetext = "TID_ACCESSORY_BLOCKED_ALREADY_ACTIVE"
        static RowID = 175
    }
    static Voodooselfbuff = class {
        static Name = "Voodoo_SelfBuff"
        static Type = "voodoo_self_buff"
        static Cooldown = 340
        static Useeffect = "gadget_activate"
        static Activeticks = 60
        static Showcountdown = true
        static Customvalue1 = 60
        static Targetalreadyactivetext = "TID_ACCESSORY_BLOCKED_ALREADY_ACTIVE"
        static RowID = 176
    }
    static Lightyearaccessory = class {
        static Name = "Lightyear_Accessory"
        static Type = "dash"
        static Cooldown = 200
        static Useeffect = "gadget_activate"
        static Loopingeffect = "gadget_max_dash"
        static Activeticks = 8
        static Interruptsaction = true
        static Customvalue1 = 1300
        static Customvalue2 = 3000
        static RowID = 177
    }
    static Skaterjump = class {
        static Name = "Skater_Jump"
        static Type = "dash"
        static Subtype = 5
        static Cooldown = 400
        static Useeffect = "ollie_def_ulti_trail"
        static Statuseffectenemy = "SkaterGadgetJumpTaunt"
        static Customobject = "SkaterGadgetTaunt"
        static Customvalue1 = 1100
        static Customvalue2 = 3500
        static RowID = 178
    }
    static Skaterprojectiletaunt = class {
        static Name = "Skater_ProjectileTaunt"
        static Type = "next_attack_change"
        static Subtype = 2
        static Cooldown = 300
        static Useeffect = "gadget_activate"
        static Loopingeffect = "gadget_on_loop"
        static Activeticks = 100000
        static Statuseffectenemy = "SkaterGadgetProjectileTaunt"
        static Customobject = "SkaterProjectileTaunt"
        static Targetalreadyactivetext = "TID_ACCESSORY_BLOCKED_ALREADY_ACTIVE"
        static RowID = 179
    }
    static Meeplewallattack = class {
        static Name = "Meeple_WallAttack"
        static Type = "swap_weapon_skill"
        static Cooldown = 440
        static Useeffect = "gadget_activate"
        static Loopingeffect = "gadget_on_loop"
        static Activeticks = 100000
        static Customobject = "MeepleWallWeapon"
        static Customvalue6 = 1
        static Targetalreadyactivetext = "TID_ACCESSORY_BLOCKED_ALREADY_ACTIVE"
        static RowID = 180
    }
    static Meepleragequit = class {
        static Name = "Meeple_RageQuit"
        static Cooldown = 360
        static Useeffect = "gadget_activate"
        static Areaeffect = "MeepleRageQuitArea"
        static RowID = 181
    }
    static Morningstarfire = class {
        static Name = "Morningstar_Fire"
        static Type = "spawn"
        static Subtype = 7
        static Cooldown = 280
        static Useeffect = "gadget_activate"
        static Areaeffect = "MorningstarFireGadgetArea"
        static Customvalue1 = 2
        static RowID = 182
    }
    static Morningstarice = class {
        static Name = "Morningstar_Ice"
        static Type = "spawn"
        static Subtype = 7
        static Cooldown = 460
        static Useeffect = "gadget_activate"
        static Areaeffect = "MorningstarIceGadgetArea"
        static Customvalue1 = 2
        static RowID = 183
    }
    static Chronomancertime = class {
        static Name = "Chronomancer_Time"
        static Type = "rewind"
        static Subtype = 2
        static Cooldown = 360
        static Useeffect = "gadget_activate"
        static Interruptsaction = true
        static Customobject = "FinxTeleport;ChronomancerTimeRewindLocation"
        static Customvalue1 = 60
        static RowID = 184
    }
    static Chronomancerprojectilestasis = class {
        static Name = "Chronomancer_ProjectileStasis"
        static Type = "next_attack_change"
        static Subtype = 2
        static Cooldown = 340
        static Useeffect = "gadget_activate"
        static Loopingeffect = "gadget_on_loop"
        static Activeticks = 100000
        static Statuseffectenemy = "ChronomancerGadgetProjectileStasis"
        static Customobject = "ChronomancerProjectileStasis"
        static Targetalreadyactivetext = "TID_ACCESSORY_BLOCKED_ALREADY_ACTIVE"
        static RowID = 185
    }
    static Alternatordamagemode = class {
        static Name = "Alternator_DamageMode"
        static Type = "swap_weapon_skill"
        static Subtype = 1
        static Cooldown = 300
        static Useeffect = "gadget_activate"
        static Loopingeffect = "gadget_on_loop"
        static Activeticks = 100
        static Areaeffect = "AlternatorDamageAura"
        static Customobject = "AlternatorWeaponDamage"
        static Targetalreadyactivetext = "TID_ACCESSORY_BLOCKED_ALREADY_ACTIVE"
        static RowID = 186
    }
    static Alternatorslowmode = class {
        static Name = "Alternator_SlowMode"
        static Type = "swap_weapon_skill"
        static Subtype = 1
        static Cooldown = 300
        static Useeffect = "gadget_activate"
        static Loopingeffect = "gadget_on_loop"
        static Activeticks = 100
        static Areaeffect = "AlternatorSlowAura"
        static Customobject = "AlternatorWeaponSlow"
        static Targetalreadyactivetext = "TID_ACCESSORY_BLOCKED_ALREADY_ACTIVE"
        static RowID = 187
    }
    static Geishagadget0 = class {
        static Name = "Geisha_Gadget_0"
        static Type = "change_character"
        static Subtype = 0
        static Cooldown = 120
        static Useeffect = "gadget_activate"
        static Areaeffect = "GeishaTransformEffect"
        static Interruptsaction = true
        static Customobject = "Geisha;GeishaTransformed"
        static RowID = 188
    }
    static Geishagadget1 = class {
        static Name = "Geisha_Gadget_1"
        static Type = "change_character"
        static Subtype = 1
        static Cooldown = 120
        static Useeffect = "gadget_activate"
        static Statuseffectally = "GeishaTransformSpeedBoost"
        static Areaeffect = "GeishaTransformEffect"
        static Interruptsaction = true
        static Customobject = "Geisha;GeishaTransformed"
        static Customvalue1 = 30
        static RowID = 189
    }
    static Geishagadget2 = class {
        static Name = "Geisha_Gadget_2"
        static Type = "change_character"
        static Subtype = 2
        static Cooldown = 120
        static Useeffect = "gadget_activate"
        static Statuseffectally = "GeishaTransformInvisibility"
        static Areaeffect = "GeishaTransformEffect"
        static Interruptsaction = true
        static Customobject = "Geisha;GeishaTransformed"
        static Customvalue1 = 1000
        static Customvalue2 = 3000
        static Customvalue3 = 100
        static RowID = 190
    }
    static Stalkerlifesteal = class {
        static Name = "Stalker_Lifesteal"
        static Type = "next_attack_change"
        static Subtype = 29
        static Cooldown = 200
        static Useeffect = "gadget_activate"
        static Loopingeffect = "gadget_on_loop"
        static Activeticks = 100000
        static Customvalue1 = 100
        static RowID = 191
    }
    static Stalkerbloodhuntoverride = class {
        static Name = "Stalker_BloodhuntOverride"
        static Type = "override_bloodhunt_hp_trigger"
        static Cooldown = 280
        static Useeffect = "gadget_activate"
        static Loopingeffect = "gadget_on_loop"
        static Activeticks = 80
        static Customvalue1 = 100
        static Customvalue2 = 80
        static RowID = 192
    }
    static Domainarea = class {
        static Name = "Domain_Area"
        static Cooldown = 140
        static Useeffect = "gadget_activate"
        static Areaeffect = "DomainOwnedAreaBig"
        static RowID = 193
    }
    static Domaininversedamage = class {
        static Name = "Domain_InverseDamage"
        static Type = "give_status_effect"
        static Cooldown = 320
        static Useeffect = "gadget_activate"
        static Statuseffectally = "DomainInverseDamageGadget"
        static RowID = 194
    }
    static Dancerblockprojectiles = class {
        static Name = "Dancer_BlockProjectiles"
        static Type = "spawn"
        static Subtype = 0
        static Cooldown = 360
        static Useeffect = "gadget_activate"
        static Areaeffect = "DancerBlockProjectiles"
        static RowID = 195
    }
    static Dancerrechargeulti = class {
        static Name = "Dancer_RechargeUlti"
        static Type = "ulti_change"
        static Subtype = 10
        static Cooldown = 360
        static Useeffect = "gadget_activate"
        static Loopingeffect = "gadget_on_loop"
        static Activeticks = 100000
        static Missingtargettext = "TID_ACCESSORY_BLOCKED_ULTI_NOT_CHARGED"
        static RowID = 196
    }
    static Furyfakeattack = class {
        static Name = "Fury_FakeAttack"
        static Type = "fake_main_attack"
        static Cooldown = 260
        static Useeffect = "gadget_activate"
        static Loopingeffect = "gadget_on_loop"
        static Activeticks = 100
        static Animationindex = 1
        static Setattackangle = true
        static Interruptable = true
        static Range = 22
        static Requireenemyinrange = true
        static Targetindirect = true
        static Customvalue1 = 20
        static RowID = 197
    }
    static Furyteleport = class {
        static Name = "Fury_Teleport"
        static Type = "next_attack_change"
        static Subtype = 30
        static Cooldown = 260
        static Useeffect = "gadget_activate"
        static Loopingeffect = "gadget_on_loop"
        static Activeticks = 100000
        static Areaeffect = "FuryGadgetTeleport"
        static Customvalue1 = 1
        static RowID = 198
    }
}

export default Accessories;