class Carryables {
    static Laserball = class {
        static Name = "LaserBall"
        static Throwoverwalls = false
        static Throwfromgroundlevel = false
        static Maxz = 500
        static Throwskill = "DummySkillForLaserBall"
        static Throwskillulti = "DummyUltiSkillForLaserBall"
        static Shouldroll = true
        static Bouncing = true
        static Usearc = true
        static Minscale = 495
        static Maxscale = 495
        static Zoffset = 140
        static Allowownteampickup = true
        static Minheightforgrab = -1
        static RowID = 1
    }
    static Captureflag = class {
        static Name = "CaptureFlag"
        static Throwoverwalls = true
        static Throwfromgroundlevel = true
        static Maxz = 1500
        static Throwskill = "DummySkillForCTF"
        static Throwskillulti = "DummyUltiSkillForCTF"
        static Usearc = true
        static Minscale = 270
        static Maxscale = 270
        static Showteamcircle = true
        static Preventpickupintargetbase = true
        static Minheightforgrab = 300
        static RowID = 2
    }
    static Holdingball = class {
        static Name = "HoldingBall"
        static Throwoverwalls = true
        static Throwfromgroundlevel = true
        static Maxz = 1500
        static Throwskill = "DummySkillForCTF"
        static Throwskillulti = "DummyUltiSkillForCTF"
        static Usearc = true
        static Minscale = 400
        static Maxscale = 400
        static Allowownteampickup = true
        static Minheightforgrab = 300
        static RowID = 3
    }
    static Volleyball = class {
        static Name = "VolleyBall"
        static Throwoverwalls = true
        static Throwfromgroundlevel = false
        static Maxz = 3500
        static Throwskill = "DummySkillForCTF"
        static Throwskillulti = "DummyUltiSkillForCTF"
        static Shouldroll = true
        static Usearc = true
        static Minscale = 600
        static Maxscale = 800
        static Preventpickupfromlasttouchingteam = true
        static Throwontouch = true
        static Minheightforgrab = 500
        static RowID = 4
    }
    static Basketball = class {
        static Name = "BasketBall"
        static Throwoverwalls = true
        static Throwfromgroundlevel = true
        static Maxz = 2000
        static Throwskill = "DummySkillForBasketBrawl"
        static Throwskillulti = "DummyUltiSkillForBasketBrawl"
        static Shouldroll = true
        static Bouncing = true
        static Usearc = true
        static Minscale = 400
        static Maxscale = 700
        static Allowownteampickup = true
        static Minheightforgrab = 300
        static RowID = 5
    }
    static Paintball = class {
        static Name = "PaintBall"
        static Throwoverwalls = false
        static Throwfromgroundlevel = false
        static Maxz = 500
        static Throwskill = "DummySkillForLaserBall"
        static Throwskillulti = "DummyUltiSkillForLaserBall"
        static Shouldroll = true
        static Bouncing = true
        static Usearc = true
        static Flyeffect = "paint_ball_fly"
        static Flyeffectulti = "paint_ball_fly_ulti"
        static Minscale = 400
        static Maxscale = 400
        static Zoffset = 140
        static Showteamcolor = true
        static Allowownteampickup = true
        static Minheightforgrab = -1
        static RowID = 6
    }
    static Airdisc = class {
        static Name = "AirDisc"
        static Throwoverwalls = false
        static Throwfromgroundlevel = false
        static Maxz = 500
        static Throwskill = "DummySkillForAirDisc"
        static Throwskillulti = "DummySkillForAirDisc"
        static Shouldroll = true
        static Bouncing = true
        static Throwdistancesubtiles = 96
        static Throwforce = 130
        static Statetonormalmovementpromille = 960
        static Throwforceulti = 175
        static Flyeffect = "airhockey_trail"
        static Flyeffectulti = "airhockey_ulti_trail"
        static Minscale = 495
        static Maxscale = 495
        static Zoffset = 140
        static Showteamcolor = true
        static Allowownteampickup = true
        static Minheightforgrab = -1
        static RowID = 7
    }
    static Unocard = class {
        static Name = "UNOCard"
        static Throwoverwalls = false
        static Throwfromgroundlevel = false
        static Maxz = 500
        static Throwskill = "DummySkillForLaserBall"
        static Throwskillulti = "DummyUltiSkillForLaserBall"
        static Shouldroll = true
        static Bouncing = true
        static Throwdistancesubtiles = 24
        static Throwdistanceultisubtiles = 36
        static Throwforce = 150
        static Throwforceulti = 200
        static Flyeffect = "uno_card_trail"
        static Flyeffectulti = "uno_card_ulti_trail"
        static Minscale = 300
        static Maxscale = 300
        static Zoffset = 200
        static Minheightforgrab = -1
        static RowID = 8
    }
    static Dodgeball = class {
        static Name = "DodgeBall"
        static Throwoverwalls = false
        static Throwfromgroundlevel = false
        static Maxz = 500
        static Throwskill = "DummySkillForDodgeBall"
        static Throwskillulti = "DummyUltiSkillForDodgeBall"
        static Shouldroll = true
        static Bouncing = true
        static Usearc = true
        static Throwdistancesubtiles = 32
        static Throwdistanceultisubtiles = 41
        static Throwforce = 180
        static Statetonormalmovementpromille = 900
        static Throwforceulti = 240
        static Flyeffect = "laser_ball_fly_dodge"
        static Flyeffectulti = "laser_ball_fly_dodge_ulti"
        static Minscale = 495
        static Maxscale = 495
        static Zoffset = 140
        static Showteamcolor = true
        static Minheightforgrab = -1
        static RowID = 9
    }
}

export default Carryables;