class Clubpiggytypes {
    static Defaultclubpiggy = class {
        static Name = "DefaultClubPiggy"
        static Wintracktype = 0
        static Isdefaulttypepiggy = true
        static Rewardcontainer = "ClubPiggyBank"
        static Nexteventtid = "TID_CLUB_PIGGY_BANK_NEXT_EVENT_TIME"
        static Eventovertid = "TID_CLUB_PIGGY_BANK_EVENT_ENDED_TITLE"
        static Smashtid = "TID_CLUB_PIGGY_BANK_EVENT_ENDED_SMASH_TITLE"
        static Leaderboardtabtid = "TID_CLUB_INFO_TAB_PIGGY_BANK"
        static Contributedwinstid = "TID_CLUB_PIGGY_CONTRIBUTED_WINS"
        static Notcontributedwinstid = "TID_CLUB_PIGGY_BANK_NOT_CONTRIBUTED"
        static Tickettooltiptid = "TID_CLUB_PIGGY_BANK_HOMESCREEN_TICKET_TOOLTIP"
        static Eventnametid = "TID_CLUB_PIGGY_BANK_EVENT_NAME"
        static Eventendinboxtid = "TID_NOTIFICATION_CLUB_PIGGY_EVENT_END"
        static Eventendnounclaimedrewardsinboxtid = "TID_NOTIFICATION_CLUB_PIGGY_EVENT_END"
        static Componenttypes = "PROGRESS_VALIGN"
        static Componentvalues = "TOP"
        static Newticketstid = "TID_CLUB_PIGGY_MORE_TICKETS"
        static Winstonextdroptid = "TID_CLUB_PIGGY_EVENT_WINS_TO_NEXT_DROP"
        static Winstonextdroppopuptid = "TID_CLUB_PIGGY_EVENT_WINS_TO_NEXT_DROP_POPUP"
        static Winstonextdropgradient = "ClubPiggyGold"
        static Levelcountertid = "TID_CLUB_PIGGY_LEVEL_COUNTER"
        static RowID = 1
    }
    static Row2 = class {
        static Componenttypes = "CONTRIBUTIONS_VALIGN"
        static Componentvalues = "BOTTOM"
        static RowID = 2
    }
    static Xmastree = class {
        static Name = "XmasTree"
        static Wintracktype = 1
        static Droptype = "PRESENT"
        static Nexteventtid = "TID_CLUB_XMAS_NEXT_EVENT_TIME"
        static Reskinassetid = "ClubPiggyXmasReskinSc"
        static Customintroflow = "ClubPiggyXmasReskinInfo"
        static Eventovertid = "TID_CLUB_XMAS_EVENT_ENDED_TITLE"
        static Smashtid = "TID_CLUB_XMAS_EVENT_ENDED_SMASH_TITLE"
        static Leaderboardtabtid = "TID_CLUB_INFO_TAB_XMAS_TREE"
        static Contributedwinstid = "TID_CLUB_XMAS_CONTRIBUTED_WINS"
        static Notcontributedwinstid = "TID_CLUB_XMAS_NOT_CONTRIBUTED"
        static Tickettooltiptid = "TID_CLUB_XMAS_HOMESCREEN_TICKET_TOOLTIP"
        static Eventnametid = "TID_CLUB_XMAS_EVENT_NAME"
        static Eventendinboxtid = "TID_NOTIFICATION_CLUB_XMAS_EVENT_END"
        static Eventendnounclaimedrewardsinboxtid = "TID_NOTIFICATION_CLUB_XMAS_EVENT_END"
        static Rewardsrootclippath = "scene/tree"
        static Rewardclipprefix = "gift_"
        static Removeallexceptoneclipwithprefix = "gary_"
        static Maxscalewinpips = 25
        static Newticketstid = "TID_CLUB_PIGGY_XMAS_MORE_TICKETS"
        static Winstonextdroptid = "TID_CLUB_PIGGY_EVENT_XMAS_WINS_TO_NEXT_DROP"
        static Winstonextdroppopuptid = "TID_CLUB_PIGGY_EVENT_XMAS_WINS_TO_NEXT_DROP_POPUP"
        static Winstonextdropgradient = "ClubPiggyGold"
        static Levelcountertid = "TID_CLUB_XMAS_LEVEL_COUNTER"
        static Levelcounteroverridetidformat = "TID_CLUB_XMAS_LEVEL_COUNTER_<NUM>"
        static RowID = 3
    }
    static Tuna = class {
        static Name = "Tuna"
        static Wintracktype = 2
        static Droptype = "SUSHI"
        static Useperplayerrewards = true
        static Claimablemidevent = true
        static Skipsummaryafterrewards = true
        static Nexteventtid = "TID_CLUB_TUNA_NEXT_EVENT_TIME"
        static Reskinassetid = "ClubPiggyTunaSC"
        static Customintroflow = "ClubPiggyTunaInfo"
        static Eventovertid = "TID_CLUB_TUNA_EVENT_ENDED_TITLE"
        static Smashtid = "TID_CLUB_TUNA_EVENT_ENDED_SMASH_TITLE"
        static Leaderboardtabtid = "TID_CLUB_INFO_TAB_TUNA"
        static Contributedwinstid = "TID_CLUB_TUNA_CONTRIBUTED_WINS"
        static Notcontributedwinstid = "TID_CLUB_TUNA_NOT_CONTRIBUTED"
        static Tickettooltiptid = "TID_CLUB_TUNA_HOMESCREEN_TICKET_TOOLTIP"
        static Eventnametid = "TID_CLUB_TUNA_EVENT_NAME"
        static Eventendinboxtid = "TID_NOTIFICATION_CLUB_SUSHI_EVENT_END"
        static Eventendnounclaimedrewardsinboxtid = "TID_NOTIFICATION_CLUB_SUSHI_EVENT_END_NO_UNCLAIMED"
        static Rewardsrootclippath = "scene/sushi"
        static Rewardclipprefix = "sushi_"
        static Claimedrewardsrootclippath = "scene/plates"
        static Claimedrewardclipprefix = "plate_"
        static Claimbuttonclippath = "scene/sushi/claim"
        static Noninteractiveitempaths = "light_rays"
        static Soundplayerclippaths = "mega_drop"
        static Newticketstid = "TID_CLUB_TUNA_MORE_TICKETS"
        static Winstonextdroptid = "TID_CLUB_PIGGY_SUSHI_PROGRESS_BAR"
        static Winstonextdroppopuptid = "TID_CLUB_PIGGY_SUSHI_PROGRESS_BAR"
        static Levelcountertid = "TID_CLUB_TUNA_LEVEL_COUNTER"
        static RowID = 4
    }
    static Row5 = class {
        static Noninteractiveitempaths = "particles"
        static RowID = 5
    }
    static Row6 = class {
        static Noninteractiveitempaths = "spotlight_loop"
        static RowID = 6
    }
    static Subway = class {
        static Name = "Subway"
        static Wintracktype = 3
        static Droptype = "COLLAB_SCORE"
        static Useperplayerrewards = true
        static Claimablemidevent = true
        static Skipsummaryafterrewards = true
        static Nexteventtid = "TID_CLUB_COLLAB_TEASER_TIME"
        static Reskinassetid = "ClubPiggySubwaySC"
        static Customintroflow = "ClubPiggySubwayInfo"
        static Eventovertid = "TID_CLUB_COLLAB_EVENT_ENDED_TITLE"
        static Smashtid = "TID_CLUB_COLLAB_EVENT_ENDED_SMASH_TITLE"
        static Leaderboardtabtid = "TID_CLUB_SUBWAY_EVENT_NAME"
        static Contributedwinstid = "TID_CLUB_PIGGY_CONTRIBUTED_WINS"
        static Notcontributedwinstid = "TID_CLUB_PIGGY_BANK_NOT_CONTRIBUTED"
        static Tickettooltiptid = "TID_CLUB_COLLAB_HOMESCREEN_TICKET_TOOLTIP"
        static Eventnametid = "TID_CLUB_SUBWAY_EVENT_NAME"
        static Eventendinboxtid = "TID_NOTIFICATION_CLUB_COLLAB_REWARD"
        static Eventendnounclaimedrewardsinboxtid = "TID_NOTIFICATION_CLUB_COLLAB_EVENT_END"
        static Rewardsrootclippath = "scene"
        static Rewardclipprefix = "sushi_"
        static Claimedrewardsrootclippath = "scene/plates"
        static Claimedrewardclipprefix = "plate_"
        static Claimbuttonclippath = "scene/claim"
        static Noninteractiveitempaths = "light_rays"
        static Soundplayerclippaths = "mega_drop"
        static Newticketstid = "TID_CLUB_COLLAB_MORE_TICKETS"
        static Winstonextdroptid = "TID_CLUB_COLLAB_PROGRESS_BAR"
        static Winstonextdroppopuptid = "TID_CLUB_COLLAB_PROGRESS_BAR"
        static Levelcountertid = "TID_CLUB_COLLAB_LEVEL_COUNTER"
        static RowID = 7
    }
    static Row8 = class {
        static Noninteractiveitempaths = "particles"
        static RowID = 8
    }
    static Row9 = class {
        static Noninteractiveitempaths = "spotlight_loop"
        static RowID = 9
    }
    static Sixticketclubpiggy = class {
        static Name = "6TicketClubPiggy"
        static Wintracktype = 4
        static Isdefaulttypepiggy = true
        static Rewardcontainer = "ClubPiggyBank"
        static Nexteventtid = "TID_CLUB_PIGGY_BANK_NEXT_EVENT_TIME"
        static Eventovertid = "TID_CLUB_PIGGY_BANK_EVENT_ENDED_TITLE"
        static Smashtid = "TID_CLUB_PIGGY_BANK_EVENT_ENDED_SMASH_TITLE"
        static Leaderboardtabtid = "TID_CLUB_INFO_TAB_PIGGY_BANK"
        static Contributedwinstid = "TID_CLUB_PIGGY_CONTRIBUTED_WINS"
        static Notcontributedwinstid = "TID_CLUB_PIGGY_BANK_NOT_CONTRIBUTED"
        static Tickettooltiptid = "TID_CLUB_PIGGY_BANK_HOMESCREEN_TICKET_TOOLTIP"
        static Eventnametid = "TID_CLUB_PIGGY_BANK_EVENT_NAME"
        static Eventendinboxtid = "TID_NOTIFICATION_CLUB_PIGGY_EVENT_END"
        static Eventendnounclaimedrewardsinboxtid = "TID_NOTIFICATION_CLUB_PIGGY_EVENT_END"
        static Componenttypes = "PROGRESS_VALIGN"
        static Componentvalues = "TOP"
        static Newticketstid = "TID_CLUB_PIGGY_MORE_TICKETS"
        static Winstonextdroptid = "TID_CLUB_PIGGY_EVENT_WINS_TO_NEXT_DROP"
        static Winstonextdroppopuptid = "TID_CLUB_PIGGY_EVENT_WINS_TO_NEXT_DROP_POPUP"
        static Winstonextdropgradient = "ClubPiggyGold"
        static Levelcountertid = "TID_CLUB_PIGGY_LEVEL_COUNTER"
        static RowID = 10
    }
    static Row11 = class {
        static Componenttypes = "CONTRIBUTIONS_VALIGN"
        static Componentvalues = "BOTTOM"
        static RowID = 11
    }
}

export default Clubpiggytypes;