class Items {
    static Health = class {
        static Name = "Health"
        static Filename = "sc/effects.sc"
        static Exportname = "soul"
        static Exportnameenemy = "soul"
        static Groundglowexportname = "pickup_glow_green"
        static Loopingeffect = "Health_fx"
        static Value = 16000
        static Triggerrangesubtiles = 4
        static Canbepickedup = true
        static Spawneffect = "Spawn_plasmoid"
        static Layer = "Above"
        static RowID = 1
    }
    static Speed = class {
        static Name = "Speed"
        static Filename = "sc/effects.sc"
        static Exportname = "red_pickup"
        static Exportnameenemy = "red_pickup"
        static Groundglowexportname = "pickup_glow_green"
        static Loopingeffect = "Health_fx"
        static Value = 300
        static Triggerrangesubtiles = 4
        static Canbepickedup = true
        static Spawneffect = "Spawn_plasmoid"
        static Layer = "Above"
        static RowID = 2
    }
    static Damageandspeed = class {
        static Name = "DamageAndSpeed"
        static Filename = "sc/effects.sc"
        static Groundglowexportname = "pickup_glow_green"
        static Loopingeffect = "power_up_bottle_sparkle"
        static Value = 100
        static Value2 = 200
        static Triggerrangesubtiles = 4
        static Canbepickedup = true
        static Spawneffect = "Spawn_buff"
        static Scw = "sc3d/item_power_up_bottle.scw"
        static Scwenemy = "sc3d/item_power_up_bottle.scw"
        static Usegeneratedshadow = true
        static Layer = "Above"
        static RowID = 3
    }
    static Point = class {
        static Name = "Point"
        static Filename = "sc/effects.sc"
        static Exportname = "blob_pickup"
        static Exportnameenemy = "blob_pickup"
        static Groundglowexportname = "pickup_glow"
        static Loopingeffect = "Blob_fx"
        static Triggerrangesubtiles = 4
        static Canbepickedup = true
        static Spawneffect = "Spawn_plasmoid"
        static Layer = "Above"
        static RowID = 4
    }
    static Corpse = class {
        static Name = "Corpse"
        static Filename = "sc/effects.sc"
        static Exportname = "soul"
        static Exportnameenemy = "soul"
        static Groundglowexportname = "pickup_glow_green"
        static Loopingeffect = "Health_fx"
        static Value = 800
        static Triggerrangesubtiles = 4
        static Canbepickedup = true
        static Spawneffect = "Spawn_plasmoid"
        static Layer = "Above"
        static RowID = 5
    }
    static Orbspawner = class {
        static Name = "OrbSpawner"
        static Spawneffect = "Spawn_plasmoid"
        static Scw = "sc3d/default_gem_spawn_geo.glb"
        static Scwenemy = "sc3d/default_gem_spawn_geo.glb"
        static Usegeneratedshadow = true
        static Layer = "GroundLow"
        static RowID = 6
    }
    static Mine = class {
        static Name = "Mine"
        static Filename = "sc/effects_brawler.sc"
        static Exportname = "bo_def_mine_blue"
        static Exportnameenemy = "bo_def_mine_red"
        static Value = 800
        static Value2 = 1150
        static Triggerrangesubtiles = 3
        static Triggerareaeffect = "Bo_def_ulti2_area"
        static Canbepickedup = true
        static Spawneffect = "bo_def_ulti2_spawn"
        static Layer = "Above"
        static RowID = 7
    }
    static Supplycrate = class {
        static Name = "SupplyCrate"
        static Filename = "sc/effects.sc"
        static Exportname = "red_pickup"
        static Exportnameenemy = "red_pickup"
        static Groundglowexportname = "pickup_glow_green"
        static Spawneffect = "Spawn_plasmoid"
        static Layer = "Above"
        static RowID = 8
    }
    static Boxofmines = class {
        static Name = "BoxOfMines"
        static Filename = "sc/effects.sc"
        static Groundglowexportname = "pickup_glow_green"
        static Value = 3
        static Value2 = 6
        static Spawneffect = "Spawn_plasmoid"
        static Layer = "Above"
        static RowID = 9
    }
    static Battleroyalebuff = class {
        static Name = "BattleRoyaleBuff"
        static Filename = "sc/effects.sc"
        static Shadowexportname = "projectile_shadow"
        static Loopingeffect = "powerup_fx"
        static Value = 10
        static Value2 = 400
        static Triggerrangesubtiles = 4
        static Canbepickedup = true
        static Spawneffect = "Spawn_plasmoid"
        static Scw = "sc3d/item_showdown_boost.scw"
        static Scwenemy = "sc3d/item_showdown_boost.scw"
        static Usegeneratedshadow = true
        static Layer = "Above"
        static RowID = 10
    }
    static Money = class {
        static Name = "Money"
        static Filename = "sc/effects.sc"
        static Exportname = "wanted_star_pickup"
        static Exportnameenemy = "wanted_star_pickup"
        static Groundglowexportname = "pickup_glow_gold"
        static Loopingeffect = "Blob_fx"
        static Value = 1
        static Triggerrangesubtiles = 4
        static Canbepickedup = true
        static Spawneffect = "Spawn_plasmoid"
        static Layer = "Above"
        static RowID = 11
    }
    static Boxofbombs = class {
        static Name = "BoxOfBombs"
        static Filename = "sc/effects.sc"
        static Groundglowexportname = "pickup_glow_green"
        static Value = 4
        static Value2 = 8
        static Spawneffect = "Spawn_plasmoid"
        static Layer = "Above"
        static RowID = 12
    }
    static Bomb = class {
        static Name = "Bomb"
        static Filename = "sc/effects.sc"
        static Exportname = "grenade_01"
        static Exportnameenemy = "grenade_01_red"
        static Shadowexportname = "projectile_shadow"
        static Value = 800
        static Value2 = 300
        static Triggerrangesubtiles = 200
        static Triggerareaeffect = "SniperBombExplosion"
        static Canbepickedup = true
        static Spawneffect = "Spawn_sniper_bomb"
        static Layer = "Above"
        static RowID = 13
    }
    static Boxofselfdestructbombs = class {
        static Name = "BoxOfSelfDestructBombs"
        static Filename = "sc/effects.sc"
        static Exportname = "red_pickup"
        static Exportnameenemy = "red_pickup"
        static Groundglowexportname = "pickup_glow_green"
        static Value = 4
        static Value2 = 40
        static Spawneffect = "Spawn_plasmoid"
        static Layer = "Above"
        static RowID = 14
    }
    static Selfdestructbomb = class {
        static Name = "SelfDestructBomb"
        static Filename = "sc/effects.sc"
        static Exportname = "cannon_projectile_blue"
        static Exportnameenemy = "cannon_projectile_red"
        static Shadowexportname = "projectile_shadow"
        static Value = 800
        static Value2 = 1300
        static Triggerrangesubtiles = 200
        static Triggerareaeffect = "SelfDestructExplosion"
        static Canbepickedup = true
        static Spawneffect = "artillery_dude_turret_attack"
        static Layer = "Above"
        static RowID = 15
    }
    static Scrap = class {
        static Name = "Scrap"
        static Filename = "sc/effects.sc"
        static Groundglowexportname = "pickup_glow_green"
        static Loopingeffect = "power_up_bottle_sparkle"
        static Triggerrangesubtiles = 4
        static Canbepickedup = true
        static Spawneffect = "Spawn_buff"
        static Scw = "sc3d/item_bolt.scw"
        static Scwenemy = "sc3d/item_bolt.scw"
        static Usegeneratedshadow = true
        static Layer = "Above"
        static RowID = 16
    }
    static Springboardleft = class {
        static Name = "SpringBoardLeft"
        static Aligntotiles = true
        static Value = 600
        static Triggerrangesubtiles = 3
        static Spawneffect = "Spawn_plasmoid"
        static Scw = "sc3d/spring_board.scw"
        static Scwenemy = "sc3d/spring_board.scw"
        static Usegeneratedshadow = true
        static Layer = "GroundTop"
        static RowID = 17
    }
    static Springboardright = class {
        static Name = "SpringBoardRight"
        static Aligntotiles = true
        static Value = 600
        static Triggerrangesubtiles = 3
        static Spawneffect = "Spawn_plasmoid"
        static Scw = "sc3d/spring_board.scw"
        static Scwenemy = "sc3d/spring_board.scw"
        static Usegeneratedshadow = true
        static Layer = "GroundTop"
        static RowID = 18
    }
    static Springboardup = class {
        static Name = "SpringBoardUp"
        static Aligntotiles = true
        static Value = 600
        static Triggerrangesubtiles = 3
        static Spawneffect = "Spawn_plasmoid"
        static Scw = "sc3d/spring_board.scw"
        static Scwenemy = "sc3d/spring_board.scw"
        static Usegeneratedshadow = true
        static Layer = "GroundTop"
        static RowID = 19
    }
    static Springboarddown = class {
        static Name = "SpringBoardDown"
        static Aligntotiles = true
        static Value = 600
        static Triggerrangesubtiles = 3
        static Spawneffect = "Spawn_plasmoid"
        static Scw = "sc3d/spring_board.scw"
        static Scwenemy = "sc3d/spring_board.scw"
        static Usegeneratedshadow = true
        static Layer = "GroundTop"
        static RowID = 20
    }
    static Springboardupleft = class {
        static Name = "SpringBoardUpLeft"
        static Aligntotiles = true
        static Value = 600
        static Triggerrangesubtiles = 3
        static Spawneffect = "Spawn_plasmoid"
        static Scw = "sc3d/spring_board_diagonal.scw"
        static Scwenemy = "sc3d/spring_board_diagonal.scw"
        static Usegeneratedshadow = true
        static Layer = "GroundTop"
        static RowID = 21
    }
    static Springboardupright = class {
        static Name = "SpringBoardUpRight"
        static Aligntotiles = true
        static Value = 600
        static Triggerrangesubtiles = 3
        static Spawneffect = "Spawn_plasmoid"
        static Scw = "sc3d/spring_board_diagonal.scw"
        static Scwenemy = "sc3d/spring_board_diagonal.scw"
        static Usegeneratedshadow = true
        static Layer = "GroundTop"
        static RowID = 22
    }
    static Springboarddownleft = class {
        static Name = "SpringBoardDownLeft"
        static Aligntotiles = true
        static Value = 600
        static Triggerrangesubtiles = 3
        static Spawneffect = "Spawn_plasmoid"
        static Scw = "sc3d/spring_board_diagonal.scw"
        static Scwenemy = "sc3d/spring_board_diagonal.scw"
        static Usegeneratedshadow = true
        static Layer = "GroundTop"
        static RowID = 23
    }
    static Springboarddownright = class {
        static Name = "SpringBoardDownRight"
        static Aligntotiles = true
        static Value = 600
        static Triggerrangesubtiles = 3
        static Spawneffect = "Spawn_plasmoid"
        static Scw = "sc3d/spring_board_diagonal.scw"
        static Scwenemy = "sc3d/spring_board_diagonal.scw"
        static Usegeneratedshadow = true
        static Layer = "GroundTop"
        static RowID = 24
    }
    static Trainspawner = class {
        static Name = "TrainSpawner"
        static Layer = "Above"
        static RowID = 25
    }
    static Clustermine = class {
        static Name = "ClusterMine"
        static Filename = "sc/effects_brawler.sc"
        static Exportname = "tick_def_atk2"
        static Exportnameenemy = "tick_def_atk2_red"
        static Shadowexportname = "shadow_normal_circle"
        static Value = 800
        static Value2 = 2000
        static Triggerrangesubtiles = 200
        static Triggerareaeffect = "ClusterBombExplosion2"
        static Canbepickedup = true
        static Showalways = true
        static Layer = "Above"
        static RowID = 26
    }
    static Tick002mine = class {
        static Name = "Tick002Mine"
        static Parentitemforskin = "ClusterMine"
        static Filename = "sc/effects_brawler.sc"
        static Exportname = "tick_002_atk2"
        static Exportnameenemy = "tick_002_atk2_red"
        static Shadowexportname = "shadow_normal_circle"
        static Value = 800
        static Value2 = 2000
        static Triggerrangesubtiles = 200
        static Triggerareaeffect = "ClusterBombExplosion2"
        static Canbepickedup = true
        static Showalways = true
        static Layer = "Above"
        static RowID = 27
    }
    static Tick003mine = class {
        static Name = "Tick003Mine"
        static Parentitemforskin = "ClusterMine"
        static Filename = "sc/effects_brawler.sc"
        static Exportname = "tick_003_atk2"
        static Exportnameenemy = "tick_003_atk2_red"
        static Shadowexportname = "shadow_normal_circle"
        static Value = 800
        static Value2 = 2000
        static Triggerrangesubtiles = 200
        static Triggerareaeffect = "Tick003Explosion2"
        static Canbepickedup = true
        static Showalways = true
        static Layer = "Above"
        static RowID = 28
    }
    static Tick004mine = class {
        static Name = "Tick004Mine"
        static Parentitemforskin = "ClusterMine"
        static Filename = "sc/effects_brawler.sc"
        static Exportname = "tick_004_atk2"
        static Exportnameenemy = "tick_004_atk2_red"
        static Value = 800
        static Value2 = 2000
        static Triggerrangesubtiles = 200
        static Triggerareaeffect = "Tick004Explosion2"
        static Canbepickedup = true
        static Showalways = true
        static Randomstartframe = 2
        static Layer = "Above"
        static RowID = 29
    }
    static Tick005mine = class {
        static Name = "Tick005Mine"
        static Parentitemforskin = "ClusterMine"
        static Filename = "sc/effects_brawler.sc"
        static Exportname = "tick_005_atk2"
        static Exportnameenemy = "tick_005_atk2_red"
        static Shadowexportname = "shadow_normal_circle"
        static Loopingeffect = "tick_005_atk2"
        static Value = 800
        static Value2 = 2000
        static Triggerrangesubtiles = 200
        static Triggerareaeffect = "Tick005Explosion2"
        static Canbepickedup = true
        static Showalways = true
        static Randomstartframe = 2
        static Layer = "Above"
        static RowID = 30
    }
    static Tick006mine = class {
        static Name = "Tick006Mine"
        static Parentitemforskin = "ClusterMine"
        static Filename = "sc/effects_brawler.sc"
        static Exportname = "tick_006_atk2_projectile"
        static Exportnameenemy = "tick_006_atk2_projectile_red"
        static Shadowexportname = "shadow_normal_circle"
        static Loopingeffect = "gen_no_hit"
        static Value = 800
        static Value2 = 2000
        static Triggerrangesubtiles = 200
        static Triggerareaeffect = "Tick006Explosion2"
        static Canbepickedup = true
        static Showalways = true
        static Randomstartframe = 2
        static Layer = "Above"
        static RowID = 31
    }
    static Tick007mine = class {
        static Name = "Tick007Mine"
        static Parentitemforskin = "ClusterMine"
        static Filename = "sc/effects_brawler.sc"
        static Exportname = "tick_007_atk2_projectile"
        static Exportnameenemy = "tick_007_atk2_projectile_red"
        static Loopingeffect = "gen_no_hit"
        static Value = 800
        static Value2 = 2000
        static Triggerrangesubtiles = 200
        static Triggerareaeffect = "Tick007Explosion2"
        static Canbepickedup = true
        static Showalways = true
        static Randomstartframe = 2
        static Layer = "Above"
        static RowID = 32
    }
    static Tick009mine = class {
        static Name = "Tick009Mine"
        static Parentitemforskin = "ClusterMine"
        static Filename = "sc/effects_brawler_tick.sc"
        static Exportname = "tick_009_atk2_projectile"
        static Exportnameenemy = "tick_009_atk2_projectile_red"
        static Loopingeffect = "gen_no_hit"
        static Value = 800
        static Value2 = 2000
        static Triggerrangesubtiles = 200
        static Triggerareaeffect = "Tick009Explosion2"
        static Canbepickedup = true
        static Showalways = true
        static Randomstartframe = 2
        static Layer = "Above"
        static RowID = 33
    }
    static Minemecha = class {
        static Name = "MineMecha"
        static Parentitemforskin = "Mine"
        static Filename = "sc/effects_brawler.sc"
        static Exportname = "bo_002_mine_blue"
        static Exportnameenemy = "bo_002_mine_red"
        static Triggerareaeffect = "Bo_def_ulti2_area"
        static Spawneffect = "bo_def_ulti2_spawn"
        static Layer = "Above"
        static RowID = 34
    }
    static Piperdefbomb = class {
        static Name = "PiperdefBomb"
        static Parentitemforskin = "Bomb"
        static Filename = "sc/effects_brawler.sc"
        static Exportname = "piper_def_ulti_projectile"
        static Exportnameenemy = "piper_def_ulti_projectile_red"
        static Shadowexportname = "shadow_normal_circle_big"
        static Triggerareaeffect = "Piper_def_ulti"
        static Spawneffect = "bo_def_ulti2_spawn"
        static Randomstartframe = 2
        static Layer = "Above"
        static RowID = 35
    }
    static Piper002bomb = class {
        static Name = "Piper002Bomb"
        static Parentitemforskin = "Bomb"
        static Filename = "sc/effects_brawler.sc"
        static Exportname = "piper_002_ulti_projectile"
        static Exportnameenemy = "piper_002_ulti_projectile_red"
        static Shadowexportname = "shadow_normal_circle_big"
        static Triggerareaeffect = "Bo_def_ulti2_area"
        static Spawneffect = "bo_def_ulti2_spawn"
        static Layer = "Above"
        static RowID = 36
    }
    static Piper003bomb = class {
        static Name = "Piper003Bomb"
        static Parentitemforskin = "Bomb"
        static Filename = "sc/effects_brawler.sc"
        static Exportname = "piper_003_ulti_projectile"
        static Exportnameenemy = "piper_003_ulti_projectile_red"
        static Shadowexportname = "shadow_normal_circle_big"
        static Triggerareaeffect = "Piper_003_ulti"
        static Spawneffect = "bo_def_ulti2_spawn"
        static Randomstartframe = 2
        static Layer = "Above"
        static RowID = 37
    }
    static Piper004bomb = class {
        static Name = "Piper004Bomb"
        static Parentitemforskin = "Bomb"
        static Filename = "sc/effects_brawler.sc"
        static Exportname = "piper_004_ulti_projectile"
        static Exportnameenemy = "piper_004_ulti_projectile_red"
        static Shadowexportname = "shadow_normal_circle_big"
        static Triggerareaeffect = "Piper_004_ulti"
        static Spawneffect = "bo_def_ulti2_spawn"
        static Randomstartframe = 2
        static Layer = "Above"
        static RowID = 38
    }
    static Piper005bomb = class {
        static Name = "Piper005Bomb"
        static Parentitemforskin = "Bomb"
        static Filename = "sc/effects_brawler.sc"
        static Exportname = "piper_005_ulti_projectile"
        static Exportnameenemy = "piper_005_ulti_projectile_red"
        static Shadowexportname = "shadow_normal_circle_big"
        static Triggerareaeffect = "Piper_005_ulti"
        static Spawneffect = "bo_def_ulti2_spawn"
        static Layer = "Above"
        static RowID = 39
    }
    static Piper006bomb = class {
        static Name = "Piper006Bomb"
        static Parentitemforskin = "Bomb"
        static Filename = "sc/effects_brawler.sc"
        static Exportname = "piper_006_ulti_projectile"
        static Exportnameenemy = "piper_006_ulti_projectile_red"
        static Shadowexportname = "shadow_normal_circle_big"
        static Triggerareaeffect = "Piper_006_ulti"
        static Spawneffect = "bo_def_ulti2_spawn"
        static Randomstartframe = 2
        static Layer = "Above"
        static RowID = 40
    }
    static Piper007bomb = class {
        static Name = "Piper007Bomb"
        static Parentitemforskin = "Bomb"
        static Filename = "sc/effects_brawler.sc"
        static Exportname = "piper_007_ulti_projectile"
        static Exportnameenemy = "piper_007_ulti_projectile_red"
        static Shadowexportname = "shadow_normal_circle_big"
        static Triggerareaeffect = "Piper_007_ulti"
        static Spawneffect = "bo_def_ulti2_spawn"
        static Layer = "Above"
        static RowID = 41
    }
    static Piper008bomb = class {
        static Name = "Piper008Bomb"
        static Parentitemforskin = "Bomb"
        static Filename = "sc/effects_brawler.sc"
        static Exportname = "piper_008_ulti_projectile"
        static Exportnameenemy = "piper_008_ulti_projectile_red"
        static Shadowexportname = "shadow_normal_circle_big"
        static Triggerareaeffect = "Piper_008_ulti"
        static Spawneffect = "bo_def_ulti2_spawn"
        static Randomstartframe = 2
        static Layer = "Above"
        static RowID = 42
    }
    static Piper009bomb = class {
        static Name = "Piper009Bomb"
        static Parentitemforskin = "Bomb"
        static Filename = "sc/effects_brawler_piper.sc"
        static Exportname = "piper_009_ulti_projectile"
        static Exportnameenemy = "piper_009_ulti_projectile_red"
        static Shadowexportname = "shadow_normal_circle_big"
        static Triggerareaeffect = "Piper_009_ulti"
        static Spawneffect = "bo_def_ulti2_spawn"
        static Randomstartframe = 2
        static Layer = "Above"
        static RowID = 43
    }
    static Minehorus = class {
        static Name = "MineHorus"
        static Parentitemforskin = "Mine"
        static Filename = "sc/effects_brawler.sc"
        static Exportname = "bo_003_mine_blue"
        static Exportnameenemy = "bo_003_mine_red"
        static Triggerareaeffect = "Bo_def_ulti2_area"
        static Spawneffect = "bo_def_ulti2_spawn"
        static Layer = "Above"
        static RowID = 44
    }
    static Minedemon = class {
        static Name = "MineDemon"
        static Parentitemforskin = "Mine"
        static Filename = "sc/effects_brawler.sc"
        static Exportname = "bo_004_mine_blue"
        static Exportnameenemy = "bo_004_mine_red"
        static Triggerareaeffect = "Bo_def_ulti2_area"
        static Spawneffect = "bo_def_ulti2_spawn"
        static Randomstartframe = 2
        static Layer = "Above"
        static RowID = 45
    }
    static Minegift = class {
        static Name = "MineGift"
        static Parentitemforskin = "Mine"
        static Filename = "sc/effects_brawler.sc"
        static Exportname = "bo_005_mine"
        static Exportnameenemy = "bo_005_mine_red"
        static Triggerareaeffect = "Bo_005_ulti2_area"
        static Spawneffect = "bo_def_ulti2_spawn"
        static Randomstartframe = 2
        static Layer = "Above"
        static RowID = 46
    }
    static Minewasp = class {
        static Name = "MineWasp"
        static Parentitemforskin = "Mine"
        static Filename = "sc/effects_brawler.sc"
        static Exportname = "bo_006_mine_blue"
        static Exportnameenemy = "bo_006_mine_red"
        static Triggerareaeffect = "Bo_006_ulti2_area"
        static Spawneffect = "bo_def_ulti2_spawn"
        static Randomstartframe = 2
        static Layer = "Above"
        static RowID = 47
    }
    static Minelotus = class {
        static Name = "MineLotus"
        static Parentitemforskin = "Mine"
        static Filename = "sc/effects_brawler.sc"
        static Exportname = "bo_007_mine"
        static Exportnameenemy = "bo_007_mine_red"
        static Triggerareaeffect = "Bo_007_ulti2_area"
        static Spawneffect = "bo_def_ulti2_spawn"
        static Layer = "Above"
        static RowID = 48
    }
    static Minechoco = class {
        static Name = "MineChoco"
        static Parentitemforskin = "Mine"
        static Filename = "sc/effects_brawler.sc"
        static Exportname = "bo_008_mine"
        static Exportnameenemy = "bo_008_mine_red"
        static Triggerareaeffect = "Bo_008_ulti2_area"
        static Spawneffect = "bo_def_ulti2_spawn"
        static Randomstartframe = 2
        static Layer = "Above"
        static RowID = 49
    }
    static Minehelmet = class {
        static Name = "MineHelmet"
        static Parentitemforskin = "Mine"
        static Filename = "sc/effects_brawler_bo.sc"
        static Exportname = "bo_009_mine"
        static Exportnameenemy = "bo_009_mine_red"
        static Triggerareaeffect = "Bo_009_ulti2_area"
        static Spawneffect = "bo_def_ulti2_spawn"
        static Randomstartframe = 2
        static Layer = "Above"
        static RowID = 50
    }
    static Scorepole = class {
        static Name = "ScorePole"
        static Spawneffect = "Spawn_plasmoid"
        static Usegeneratedshadow = true
        static Layer = "Above"
        static RowID = 51
    }
    static Scoreflag = class {
        static Name = "ScoreFlag"
        static Spawneffect = "Spawn_plasmoid"
        static Usegeneratedshadow = true
        static Layer = "Above"
        static RowID = 52
    }
    static Scoreflaghoisted = class {
        static Name = "ScoreFlagHoisted"
        static Loopingeffect = "mode_koh_complete"
        static Spawneffect = "mode_koh_captured"
        static Usegeneratedshadow = true
        static Layer = "Above"
        static RowID = 53
    }
    static Fivedce5f478110256c30c89d84664a5acf3ec9e9f0 = class {
        static Name = "5dce5f478110256c30c89d84664a5acf3ec9e9f0"
        static Disabled = true
        static Filename = "sc/effects.sc"
        static Groundglowexportname = "pickup_glow_green"
        static Loopingeffect = "power_up_bottle_sparkle"
        static Value = 100
        static Value2 = 200
        static Triggerrangesubtiles = 4
        static Canbepickedup = true
        static Spawneffect = "Spawn_buff"
        static Scw = "sc3d/item_power_up_bottle.scw"
        static Scwenemy = "sc3d/item_power_up_bottle.scw"
        static Usegeneratedshadow = true
        static Layer = "Above"
        static RowID = 54
    }
    static Springboardleftgale = class {
        static Name = "SpringBoardLeft_Gale"
        static Value = 300
        static Triggerrangesubtiles = 3
        static Spawneffect = "Spawn_plasmoid"
        static Scw = "sc3d/spring_board_gale.scw"
        static Scwenemy = "sc3d/spring_board_gale.scw"
        static Usegeneratedshadow = true
        static Layer = "GroundTop"
        static RowID = 55
    }
    static Springboardrightgale = class {
        static Name = "SpringBoardRight_Gale"
        static Value = 300
        static Triggerrangesubtiles = 3
        static Spawneffect = "Spawn_plasmoid"
        static Scw = "sc3d/spring_board_gale.scw"
        static Scwenemy = "sc3d/spring_board_gale.scw"
        static Usegeneratedshadow = true
        static Layer = "GroundTop"
        static RowID = 56
    }
    static Springboardupgale = class {
        static Name = "SpringBoardUp_Gale"
        static Value = 300
        static Triggerrangesubtiles = 3
        static Spawneffect = "Spawn_plasmoid"
        static Scw = "sc3d/spring_board_gale.scw"
        static Scwenemy = "sc3d/spring_board_gale.scw"
        static Usegeneratedshadow = true
        static Layer = "GroundTop"
        static RowID = 57
    }
    static Springboarddowngale = class {
        static Name = "SpringBoardDown_Gale"
        static Value = 300
        static Triggerrangesubtiles = 3
        static Spawneffect = "Spawn_plasmoid"
        static Scw = "sc3d/spring_board_gale.scw"
        static Scwenemy = "sc3d/spring_board_gale.scw"
        static Usegeneratedshadow = true
        static Layer = "GroundTop"
        static RowID = 58
    }
    static Springboardupleftgale = class {
        static Name = "SpringBoardUpLeft_Gale"
        static Value = 300
        static Triggerrangesubtiles = 3
        static Spawneffect = "Spawn_plasmoid"
        static Scw = "sc3d/spring_board_diagonal_gale.scw"
        static Scwenemy = "sc3d/spring_board_diagonal_gale.scw"
        static Usegeneratedshadow = true
        static Layer = "GroundTop"
        static RowID = 59
    }
    static Springboarduprightgale = class {
        static Name = "SpringBoardUpRight_Gale"
        static Value = 300
        static Triggerrangesubtiles = 3
        static Spawneffect = "Spawn_plasmoid"
        static Scw = "sc3d/spring_board_diagonal_gale.scw"
        static Scwenemy = "sc3d/spring_board_diagonal_gale.scw"
        static Usegeneratedshadow = true
        static Layer = "GroundTop"
        static RowID = 60
    }
    static Springboarddownleftgale = class {
        static Name = "SpringBoardDownLeft_Gale"
        static Value = 300
        static Triggerrangesubtiles = 3
        static Spawneffect = "Spawn_plasmoid"
        static Scw = "sc3d/spring_board_diagonal_gale.scw"
        static Scwenemy = "sc3d/spring_board_diagonal_gale.scw"
        static Usegeneratedshadow = true
        static Layer = "GroundTop"
        static RowID = 61
    }
    static Springboarddownrightgale = class {
        static Name = "SpringBoardDownRight_Gale"
        static Value = 300
        static Triggerrangesubtiles = 3
        static Spawneffect = "Spawn_plasmoid"
        static Scw = "sc3d/spring_board_diagonal_gale.scw"
        static Scwenemy = "sc3d/spring_board_diagonal_gale.scw"
        static Usegeneratedshadow = true
        static Layer = "GroundTop"
        static RowID = 62
    }
    static Teleport1 = class {
        static Name = "Teleport1"
        static Value = 1
        static Triggerrangesubtiles = 3
        static Spawneffect = "Spawn_plasmoid"
        static Scw = "sc3d/teleport_tile_geo.glb"
        static Scwenemy = "sc3d/teleport_tile_geo.glb"
        static Scwtoplayer = "sc3d/teleport_effect.scw"
        static Usegeneratedshadow = true
        static Layer = "GroundTop"
        static RowID = 63
    }
    static Teleport2 = class {
        static Name = "Teleport2"
        static Value = 2
        static Triggerrangesubtiles = 3
        static Spawneffect = "Spawn_plasmoid"
        static Scw = "sc3d/teleport_tile_2_geo.glb"
        static Scwenemy = "sc3d/teleport_tile_2_geo.glb"
        static Scwtoplayer = "sc3d/teleport_effect_2.scw"
        static Usegeneratedshadow = true
        static Layer = "GroundTop"
        static RowID = 64
    }
    static Teleport3 = class {
        static Name = "Teleport3"
        static Value = 3
        static Triggerrangesubtiles = 3
        static Spawneffect = "Spawn_plasmoid"
        static Scw = "sc3d/teleport_tile_3_geo.glb"
        static Scwenemy = "sc3d/teleport_tile_3_geo.glb"
        static Scwtoplayer = "sc3d/teleport_effect_3.scw"
        static Usegeneratedshadow = true
        static Layer = "GroundTop"
        static RowID = 65
    }
    static Teleport4 = class {
        static Name = "Teleport4"
        static Value = 4
        static Triggerrangesubtiles = 3
        static Spawneffect = "Spawn_plasmoid"
        static Scw = "sc3d/teleport_tile_4_geo.glb"
        static Scwenemy = "sc3d/teleport_tile_4_geo.glb"
        static Scwtoplayer = "sc3d/teleport_effect_4.scw"
        static Usegeneratedshadow = true
        static Layer = "GroundTop"
        static RowID = 66
    }
    static Ruffsbuff = class {
        static Name = "RuffsBuff"
        static Filename = "sc/effects_brawler.sc"
        static Loopingeffect = "ruffs_def_ulti_item"
        static Value = 20
        static Value2 = 700
        static Triggerrangesubtiles = 4
        static Canbepickedup = true
        static Spawneffect = "Spawn_buff"
        static Scw = "sc3d/ruffs_buff_geo.scw"
        static Scwenemy = "sc3d/ruffs_buff_geo.scw"
        static Layer = "Above"
        static RowID = 67
    }
    static Ruffsoverchargedbuff = class {
        static Name = "RuffsOverchargedBuff"
        static Filename = "sc/effects_brawler.sc"
        static Loopingeffect = "ruffs_overcharged_ulti_item"
        static Value = 20
        static Value2 = 700
        static Triggerrangesubtiles = 4
        static Canbepickedup = true
        static Spawneffect = "Spawn_buff"
        static Scw = "sc3d/ruffs_buff_geo.scw"
        static Scwenemy = "sc3d/ruffs_buff_geo.scw"
        static Layer = "Above"
        static RowID = 68
    }
    static Stickybomb = class {
        static Name = "StickyBomb"
        static Filename = "sc/effects_brawler.sc"
        static Exportname = "sticky_def_atk_reached"
        static Exportnameenemy = "sticky_def_atk_reached_red"
        static Value = 800
        static Value2 = 1150
        static Triggerrangesubtiles = 3
        static Triggerareaeffect = "StickyBombExplosion"
        static Spawneffect = "Spawn_buff"
        static Activateeffect = "sticky_def_atk_hit"
        static Showalways = true
        static Layer = "Above"
        static RowID = 69
    }
    static Stickybombulti = class {
        static Name = "StickyBombUlti"
        static Filename = "sc/effects_brawler.sc"
        static Exportname = "sticky_def_ulti_reached"
        static Exportnameenemy = "sticky_def_ulti_reached_red"
        static Value = 800
        static Value2 = 1150
        static Triggerrangesubtiles = 3
        static Triggerareaeffect = "StickyBombUltiExplosion"
        static Spawneffect = "Spawn_buff"
        static Activateeffect = "sticky_def_atk_hit"
        static Showalways = true
        static Layer = "Above"
        static RowID = 70
    }
    static Sticky002bomb = class {
        static Name = "Sticky002Bomb"
        static Parentitemforskin = "StickyBomb"
        static Filename = "sc/effects_brawler.sc"
        static Exportname = "sticky_002_atk_reached"
        static Exportnameenemy = "sticky_002_atk_reached_red"
        static Value = 800
        static Value2 = 1150
        static Triggerrangesubtiles = 3
        static Triggerareaeffect = "StickyBombExplosion"
        static Spawneffect = "Spawn_buff"
        static Activateeffect = "sticky_def_atk_hit"
        static Showalways = true
        static Layer = "Above"
        static RowID = 71
    }
    static Sticky002bombulti = class {
        static Name = "Sticky002BombUlti"
        static Parentitemforskin = "StickyBombUlti"
        static Filename = "sc/effects_brawler.sc"
        static Exportname = "sticky_002_ulti_reached"
        static Exportnameenemy = "sticky_002_ulti_reached_red"
        static Value = 800
        static Value2 = 1150
        static Triggerrangesubtiles = 3
        static Triggerareaeffect = "StickyBombUltiExplosion"
        static Spawneffect = "Spawn_buff"
        static Showalways = true
        static Layer = "Above"
        static RowID = 72
    }
    static Sticky003bomb = class {
        static Name = "Sticky003Bomb"
        static Parentitemforskin = "StickyBomb"
        static Filename = "sc/effects_brawler.sc"
        static Exportname = "squeak_003_atk_reached"
        static Exportnameenemy = "squeak_003_atk_reached_red"
        static Value = 800
        static Value2 = 1150
        static Triggerrangesubtiles = 3
        static Triggerareaeffect = "Squeak003BombExplosion"
        static Spawneffect = "Spawn_buff"
        static Activateeffect = "squeak_003_atk_hit"
        static Showalways = true
        static Layer = "Above"
        static RowID = 73
    }
    static Sticky003bombulti = class {
        static Name = "Sticky003BombUlti"
        static Parentitemforskin = "StickyBombUlti"
        static Filename = "sc/effects_brawler.sc"
        static Exportname = "squeak_003_ulti_reached"
        static Exportnameenemy = "squeak_003_ulti_reached_red"
        static Value = 800
        static Value2 = 1150
        static Triggerrangesubtiles = 3
        static Triggerareaeffect = "Squeak003UltiExplosion"
        static Spawneffect = "Spawn_buff"
        static Activateeffect = "squeak_003_atk_hit"
        static Showalways = true
        static Layer = "Above"
        static RowID = 74
    }
    static Sticky004bomb = class {
        static Name = "Sticky004Bomb"
        static Parentitemforskin = "StickyBomb"
        static Filename = "sc/effects_brawler.sc"
        static Exportname = "squeak_004_atk_reached"
        static Exportnameenemy = "squeak_004_atk_reached_red"
        static Value = 800
        static Value2 = 1150
        static Triggerrangesubtiles = 3
        static Triggerareaeffect = "Squeak004BombExplosion"
        static Spawneffect = "Spawn_buff"
        static Activateeffect = "squeak_004_atk_hit"
        static Showalways = true
        static Layer = "Above"
        static RowID = 75
    }
    static Sticky004bombulti = class {
        static Name = "Sticky004BombUlti"
        static Parentitemforskin = "StickyBombUlti"
        static Filename = "sc/effects_brawler.sc"
        static Exportname = "squeak_004_ulti_reached"
        static Exportnameenemy = "squeak_004_ulti_reached_red"
        static Value = 800
        static Value2 = 1150
        static Triggerrangesubtiles = 3
        static Triggerareaeffect = "Squeak004UltiExplosion"
        static Spawneffect = "Spawn_buff"
        static Activateeffect = "squeak_004_ulti_hit"
        static Showalways = true
        static Layer = "Above"
        static RowID = 76
    }
    static Sticky005bomb = class {
        static Name = "Sticky005Bomb"
        static Parentitemforskin = "StickyBomb"
        static Filename = "sc/effects_brawler.sc"
        static Exportname = "squeak_005_atk_reached"
        static Exportnameenemy = "squeak_005_atk_reached_red"
        static Value = 800
        static Value2 = 1150
        static Triggerrangesubtiles = 3
        static Triggerareaeffect = "Squeak005BombExplosion"
        static Spawneffect = "Spawn_buff"
        static Activateeffect = "squeak_005_atk_hit"
        static Showalways = true
        static Layer = "Above"
        static RowID = 77
    }
    static Sticky005bombulti = class {
        static Name = "Sticky005BombUlti"
        static Parentitemforskin = "StickyBombUlti"
        static Filename = "sc/effects_brawler.sc"
        static Exportname = "squeak_005_ulti_reached"
        static Exportnameenemy = "squeak_005_ulti_reached_red"
        static Value = 800
        static Value2 = 1150
        static Triggerrangesubtiles = 3
        static Triggerareaeffect = "Squeak005UltiExplosion"
        static Spawneffect = "Spawn_buff"
        static Activateeffect = "squeak_005_ulti_hit"
        static Showalways = true
        static Layer = "Above"
        static RowID = 78
    }
    static Sticky006bomb = class {
        static Name = "Sticky006Bomb"
        static Parentitemforskin = "StickyBomb"
        static Filename = "sc/effects_brawler.sc"
        static Exportname = "squeak_006_atk_timer"
        static Exportnameenemy = "squeak_006_atk_timer_red"
        static Value = 800
        static Value2 = 1150
        static Triggerrangesubtiles = 3
        static Triggerareaeffect = "Squeak006BombExplosion"
        static Spawneffect = "Spawn_buff"
        static Showalways = true
        static Layer = "Above"
        static RowID = 79
    }
    static Sticky006bombulti = class {
        static Name = "Sticky006BombUlti"
        static Parentitemforskin = "StickyBombUlti"
        static Filename = "sc/effects_brawler.sc"
        static Exportname = "squeak_006_ulti_timer"
        static Exportnameenemy = "squeak_006_ulti_timer_red"
        static Value = 800
        static Value2 = 1150
        static Triggerrangesubtiles = 3
        static Triggerareaeffect = "Squeak006UltiExplosion"
        static Spawneffect = "Spawn_buff"
        static Showalways = true
        static Layer = "Above"
        static RowID = 80
    }
    static Sticky007bomb = class {
        static Name = "Sticky007Bomb"
        static Parentitemforskin = "StickyBomb"
        static Filename = "sc/effects_brawler.sc"
        static Exportname = "squeak_007_atk_reached"
        static Exportnameenemy = "squeak_007_atk_reached_red"
        static Value = 800
        static Value2 = 1150
        static Triggerrangesubtiles = 3
        static Triggerareaeffect = "Squeak007BombExplosion"
        static Spawneffect = "Spawn_buff"
        static Showalways = true
        static Layer = "Above"
        static RowID = 81
    }
    static Sticky007bombulti = class {
        static Name = "Sticky007BombUlti"
        static Parentitemforskin = "StickyBombUlti"
        static Filename = "sc/effects_brawler.sc"
        static Exportname = "squeak_007_ulti_reached"
        static Exportnameenemy = "squeak_007_ulti_reached_red"
        static Value = 800
        static Value2 = 1150
        static Triggerrangesubtiles = 3
        static Triggerareaeffect = "Squeak007UltiExplosion"
        static Spawneffect = "Spawn_buff"
        static Showalways = true
        static Layer = "Above"
        static RowID = 82
    }
    static Electrotrap = class {
        static Name = "ElectroTrap"
        static Filename = "sc/effects_brawler.sc"
        static Exportname = "belle_gadget_trap"
        static Exportnameenemy = "belle_gadget_trap_red"
        static Value = 0
        static Value2 = 1
        static Triggerrangesubtiles = 3
        static Triggerareaeffect = "ElectroTrapExplosion"
        static Canbepickedup = true
        static Spawneffect = "bo_def_ulti2_spawn"
        static Layer = "Above"
        static RowID = 83
    }
    static Basketbrawlhoop = class {
        static Name = "BasketBrawlHoop"
        static Spawneffect = "Spawn_plasmoid"
        static Scw = "sc3d/basketball_hoop.scw"
        static Scwenemy = "sc3d/basketball_hoop.scw"
        static Showalways = true
        static Layer = "Above"
        static RowID = 84
    }
    static Healing = class {
        static Name = "Healing"
        static Aligntotiles = true
        static Value = 500
        static Triggerrangesubtiles = 3
        static Spawneffect = "Spawn_plasmoid"
        static Scw = "sc3d/healing_tile.scw"
        static Scwenemy = "sc3d/healing_tile.scw"
        static Usegeneratedshadow = true
        static Layer = "GroundLow"
        static RowID = 85
    }
    static Windwall = class {
        static Name = "WindWall"
        static Filename = "sc/effects.sc"
        static Loopingeffect = "gadget_gale_windwall"
        static Value = 600
        static Lifetime = 100
        static Spawneffect = "Spawn_plasmoid"
        static Showalways = true
        static Layer = "Above"
        static RowID = 86
    }
    static Kickerdudemine = class {
        static Name = "KickerDudeMine"
        static Filename = "sc/effects_brawler.sc"
        static Exportname = "fang_gadget_projectile"
        static Exportnameenemy = "fang_gadget_projectile_red"
        static Shadowexportname = "shadow_normal_circle"
        static Value = 800
        static Value2 = 2000
        static Triggerrangesubtiles = 200
        static Triggerareaeffect = "KickerDudeMineExplosion"
        static Canbepickedup = true
        static Showalways = true
        static Layer = "Above"
        static RowID = 87
    }
    static Kickerdudemineoc = class {
        static Name = "KickerDudeMineOC"
        static Filename = "sc/effects_brawler.sc"
        static Exportname = "fang_def_oc_popcorn"
        static Exportnameenemy = "fang_def_oc_popcorn_red"
        static Shadowexportname = "shadow_normal_circle"
        static Value = 800
        static Value2 = 2000
        static Triggerrangesubtiles = 200
        static Triggerareaeffect = "KickerDudeMineExplosionOC"
        static Canbepickedup = true
        static Showalways = true
        static Layer = "Above"
        static RowID = 88
    }
    static Spray = class {
        static Name = "Spray"
        static Aligntotiles = true
        static Scw = "sc3d/spray_2x2.scw"
        static Scwenemy = "sc3d/spray_2x2.scw"
        static Layer = "GroundLow"
        static RowID = 89
    }
    static Invasiontoken = class {
        static Name = "InvasionToken"
        static Filename = "sc/effects.sc"
        static Groundglowexportname = "pickup_glow_green"
        static Loopingeffect = "power_up_bottle_sparkle"
        static Triggerrangesubtiles = 4
        static Canbepickedup = true
        static Spawneffect = "Spawn_buff"
        static Scw = "sc3d/item_bolt.scw"
        static Scwenemy = "sc3d/item_bolt.scw"
        static Usegeneratedshadow = true
        static Layer = "Above"
        static RowID = 90
    }
    static Invasionbase = class {
        static Name = "InvasionBase"
        static Lifetime = 200
        static Scw = "sc3d/drop_pod_platform_present_geo.glb"
        static Scwenemy = "sc3d/drop_pod_platform_present_geo.glb"
        static Scwtoplayer = "sc3d/drop_pod_present_geo.glb"
        static Usegeneratedshadow = true
        static Layer = "GroundTop"
        static RowID = 91
    }
    static Silencerhugger = class {
        static Name = "SilencerHugger"
        static Filename = "sc/effects_brawler.sc"
        static Exportname = "otto_def_ulti_hugger_starfish"
        static Exportnameenemy = "otto_def_ulti_hugger_starfish_red"
        static Lifetime = 60
        static Spawneffect = "otto_def_ulti_hugger_hit"
        static Activateeffect = "sticky_def_atk_hit"
        static Showalways = true
        static Randomstartframe = 2
        static Layer = "Above"
        static RowID = 92
    }
    static Silencerhuggermine = class {
        static Name = "SilencerHuggerMine"
        static Filename = "sc/effects_brawler.sc"
        static Exportname = "otto_def_gajet_mine"
        static Exportnameenemy = "otto_def_gajet_mine_red"
        static Shadowexportname = "shadow_normal_circle"
        static Value2 = 1
        static Triggerrangesubtiles = 3
        static Triggerareaeffect = "HuggerMineExplosion"
        static Canbepickedup = true
        static Layer = "Above"
        static RowID = 93
    }
    static Silencerhuggeroc = class {
        static Name = "SilencerHuggerOC"
        static Parentitemforskin = "SilencerHugger"
        static Filename = "sc/effects_brawler.sc"
        static Exportname = "otis_def_oc_ulti_hugger_starfish"
        static Exportnameenemy = "otis_def_oc_ulti_hugger_starfish_red"
        static Lifetime = 60
        static Spawneffect = "otis_def_oc_ulti_hugger_hit"
        static Showalways = true
        static Randomstartframe = 2
        static Layer = "Above"
        static RowID = 94
    }
    static Otto002hugger = class {
        static Name = "Otto002Hugger"
        static Parentitemforskin = "SilencerHugger"
        static Filename = "sc/effects_brawler.sc"
        static Exportname = "otto_002_ulti_hugger_bug"
        static Exportnameenemy = "otto_002_ulti_hugger_bug_red"
        static Loopingeffect = "otto_002_ulti_hugger_loop"
        static Lifetime = 60
        static Spawneffect = "otto_002_ulti_hugger_hit"
        static Activateeffect = "sticky_def_atk_hit"
        static Showalways = true
        static Randomstartframe = 2
        static Layer = "Above"
        static RowID = 95
    }
    static Otto002huggermine = class {
        static Name = "Otto002HuggerMine"
        static Parentitemforskin = "SilencerHuggerMine"
        static Filename = "sc/effects_brawler.sc"
        static Exportname = "otto_002_gajet_mine"
        static Exportnameenemy = "otto_002_gajet_mine_red"
        static Shadowexportname = "shadow_normal_circle"
        static Value2 = 1
        static Triggerrangesubtiles = 3
        static Triggerareaeffect = "Otto002MineExplosion"
        static Canbepickedup = true
        static Randomstartframe = 2
        static Layer = "Above"
        static RowID = 96
    }
    static Otis003hugger = class {
        static Name = "Otis003Hugger"
        static Parentitemforskin = "SilencerHugger"
        static Filename = "sc/effects_brawler.sc"
        static Exportname = "otis_003_ulti_stick_starfish"
        static Exportnameenemy = "otis_003_ulti_stick_starfish_red"
        static Loopingeffect = "otto_002_ulti_hugger_loop"
        static Lifetime = 60
        static Spawneffect = "otis_003_ulti_hit"
        static Activateeffect = "sticky_def_atk_hit"
        static Showalways = true
        static Randomstartframe = 2
        static Layer = "Above"
        static RowID = 97
    }
    static Otis003huggermine = class {
        static Name = "Otis003HuggerMine"
        static Parentitemforskin = "SilencerHuggerMine"
        static Filename = "sc/effects_brawler.sc"
        static Exportname = "otis_003_ulti_mine"
        static Exportnameenemy = "otis_003_ulti_mine_red"
        static Shadowexportname = "shadow_normal_circle"
        static Value2 = 1
        static Triggerrangesubtiles = 3
        static Triggerareaeffect = "Otto002MineExplosion"
        static Canbepickedup = true
        static Randomstartframe = 2
        static Layer = "Above"
        static RowID = 98
    }
    static Otis004hugger = class {
        static Name = "Otis004Hugger"
        static Parentitemforskin = "SilencerHugger"
        static Filename = "sc/effects_brawler.sc"
        static Exportname = "otis_004_ulti_hugger"
        static Exportnameenemy = "otis_004_ulti_hugger_red"
        static Loopingeffect = "otto_002_ulti_hugger_loop"
        static Lifetime = 60
        static Spawneffect = "otis_004_ulti_hugger_hit"
        static Activateeffect = "sticky_def_atk_hit"
        static Showalways = true
        static Randomstartframe = 2
        static Layer = "Above"
        static RowID = 99
    }
    static Otis004huggermine = class {
        static Name = "Otis004HuggerMine"
        static Parentitemforskin = "SilencerHuggerMine"
        static Filename = "sc/effects_brawler.sc"
        static Exportname = "otis_004_gadget_mine"
        static Exportnameenemy = "otis_004_gadget_mine_red"
        static Shadowexportname = "shadow_normal_circle"
        static Value2 = 1
        static Triggerrangesubtiles = 3
        static Triggerareaeffect = "Otto002MineExplosion"
        static Canbepickedup = true
        static Randomstartframe = 2
        static Layer = "Above"
        static RowID = 100
    }
    static Otis005hugger = class {
        static Name = "Otis005Hugger"
        static Parentitemforskin = "SilencerHugger"
        static Filename = "sc/effects_brawler.sc"
        static Exportname = "otis_005_ulti_hugger_starfish"
        static Exportnameenemy = "otis_005_ulti_hugger_starfish_red"
        static Lifetime = 60
        static Spawneffect = "otis_005_ulti_hugger_hit"
        static Activateeffect = "sticky_def_atk_hit"
        static Showalways = true
        static Randomstartframe = 2
        static Layer = "Above"
        static RowID = 101
    }
    static Otis005huggermine = class {
        static Name = "Otis005HuggerMine"
        static Parentitemforskin = "SilencerHuggerMine"
        static Filename = "sc/effects_brawler.sc"
        static Exportname = "otis_005_gajet_mine"
        static Exportnameenemy = "otis_005_gajet_mine_red"
        static Shadowexportname = "shadow_normal_circle"
        static Value2 = 1
        static Triggerrangesubtiles = 3
        static Triggerareaeffect = "Otto002MineExplosion"
        static Canbepickedup = true
        static Randomstartframe = 2
        static Layer = "Above"
        static RowID = 102
    }
    static Turret = class {
        static Name = "Turret"
        static Usegeneratedshadow = true
        static Layer = "Above"
        static RowID = 103
    }
    static Weaponthrowerweapon = class {
        static Name = "WeaponThrowerWeapon"
        static Filename = "sc/effects_brawler.sc"
        static Exportname = "bronson_def_ulti_gauntlet"
        static Exportnameenemy = "bronson_def_ulti_gauntlet_red"
        static Loopingeffect = "otto_002_ulti_hugger_loop"
        static Triggerrangesubtiles = 3
        static Canbepickedup = true
        static Spawneffect = "Spawn_plasmoid"
        static Layer = "Above"
        static RowID = 104
    }
    static Weaponthroweroverchargedweapon = class {
        static Name = "WeaponThrowerOverchargedWeapon"
        static Parentitemforskin = "WeaponThrowerWeapon"
        static Filename = "sc/effects_brawler.sc"
        static Exportname = "bronson_def_oc_ulti_gauntlet"
        static Exportnameenemy = "bronson_def_oc_ulti_gauntlet_red"
        static Loopingeffect = "otto_002_ulti_hugger_loop"
        static Triggerrangesubtiles = 3
        static Canbepickedup = true
        static Spawneffect = "Spawn_plasmoid"
        static Layer = "Above"
        static RowID = 105
    }
    static Bronson002weapon = class {
        static Name = "Bronson002Weapon"
        static Parentitemforskin = "WeaponThrowerWeapon"
        static Filename = "sc/effects_brawler.sc"
        static Exportname = "bronson_002_ulti_reached_ryan"
        static Exportnameenemy = "bronson_002_ulti_reached_ryan_red"
        static Shadowexportname = "bronson_002_ulti_reached_ryan_shadow"
        static Triggerrangesubtiles = 3
        static Canbepickedup = true
        static Spawneffect = "bo_def_ulti2_spawn"
        static Layer = "Above"
        static RowID = 106
    }
    static Bronson003weapon = class {
        static Name = "Bronson003Weapon"
        static Parentitemforskin = "WeaponThrowerWeapon"
        static Filename = "sc/effects_brawler.sc"
        static Exportname = "bronson_003_ulti_reached_proj"
        static Exportnameenemy = "bronson_003_ulti_reached_proj_red"
        static Shadowexportname = "bronson_003_ulti_reached_shadow"
        static Triggerrangesubtiles = 3
        static Canbepickedup = true
        static Spawneffect = "bo_def_ulti2_spawn"
        static Layer = "Above"
        static RowID = 107
    }
    static Bronson004weapon = class {
        static Name = "Bronson004Weapon"
        static Parentitemforskin = "WeaponThrowerWeapon"
        static Filename = "sc/effects_brawler.sc"
        static Exportname = "bronson_004_ulti_reached_gauntlet"
        static Exportnameenemy = "bronson_004_ulti_reached_gauntlet_red"
        static Shadowexportname = "bronson_004_ulti_reached_gauntlet_shadow"
        static Triggerrangesubtiles = 3
        static Canbepickedup = true
        static Spawneffect = "bo_def_ulti2_spawn"
        static Layer = "Above"
        static RowID = 108
    }
    static Bronson005weapon = class {
        static Name = "Bronson005Weapon"
        static Parentitemforskin = "WeaponThrowerWeapon"
        static Filename = "sc/effects_brawler.sc"
        static Exportname = "bronson_005_ulti_reached_gauntlet"
        static Exportnameenemy = "bronson_005_ulti_reached_gauntlet_red"
        static Triggerrangesubtiles = 3
        static Canbepickedup = true
        static Spawneffect = "bo_def_ulti2_spawn"
        static Layer = "Above"
        static RowID = 109
    }
    static Soulcollectorsoul = class {
        static Name = "SoulCollectorSoul"
        static Filename = "sc/effects_brawler.sc"
        static Exportname = "gus_def_atk_spirit"
        static Exportnameenemy = "gus_def_atk_spirit_red"
        static Loopingeffect = "gus_def_spirit_loop"
        static Value = 800
        static Triggerrangesubtiles = 3
        static Triggerareaeffect = "SoulCollectorSoulExplosion"
        static Canbepickedup = true
        static Spawneffect = "gus_def_spirit_active"
        static Randomstartframe = 2
        static Layer = "Above"
        static RowID = 110
    }
    static Gus002soul = class {
        static Name = "Gus002Soul"
        static Parentitemforskin = "SoulCollectorSoul"
        static Filename = "sc/effects_brawler.sc"
        static Exportname = "gus_002_atk_spirit"
        static Exportnameenemy = "gus_002_atk_spirit_red"
        static Loopingeffect = "gus_def_spirit_loop"
        static Value = 800
        static Triggerrangesubtiles = 3
        static Triggerareaeffect = "SoulCollectorSoulExplosion"
        static Canbepickedup = true
        static Spawneffect = "gus_def_spirit_active"
        static Randomstartframe = 2
        static Layer = "Above"
        static RowID = 111
    }
    static Gus003soul = class {
        static Name = "Gus003Soul"
        static Parentitemforskin = "SoulCollectorSoul"
        static Filename = "sc/effects_brawler.sc"
        static Exportname = "gus_003_atk_spirit"
        static Exportnameenemy = "gus_003_atk_spirit_red"
        static Loopingeffect = "gus_def_spirit_loop"
        static Value = 800
        static Triggerrangesubtiles = 3
        static Triggerareaeffect = "SoulCollectorSoulExplosion"
        static Canbepickedup = true
        static Spawneffect = "gus_def_spirit_active"
        static Randomstartframe = 2
        static Layer = "Above"
        static RowID = 112
    }
    static Gus004soul = class {
        static Name = "Gus004Soul"
        static Parentitemforskin = "SoulCollectorSoul"
        static Filename = "sc/effects_brawler.sc"
        static Exportname = "gus_004_atk_spirit"
        static Exportnameenemy = "gus_004_atk_spirit_red"
        static Loopingeffect = "gus_def_spirit_loop"
        static Value = 800
        static Triggerrangesubtiles = 3
        static Triggerareaeffect = "SoulCollectorSoulExplosion"
        static Canbepickedup = true
        static Spawneffect = "gus_def_spirit_active"
        static Randomstartframe = 2
        static Layer = "Above"
        static RowID = 113
    }
    static Gus005soul = class {
        static Name = "Gus005Soul"
        static Parentitemforskin = "SoulCollectorSoul"
        static Filename = "sc/effects_brawler_gus.sc"
        static Exportname = "gus_005_atk_spirit"
        static Exportnameenemy = "gus_005_atk_spirit_red"
        static Loopingeffect = "gus_005_spirit_loop"
        static Value = 800
        static Triggerrangesubtiles = 3
        static Triggerareaeffect = "SoulCollectorSoulExplosion"
        static Canbepickedup = true
        static Spawneffect = "gus_def_spirit_active"
        static Randomstartframe = 2
        static Layer = "Above"
        static RowID = 114
    }
    static Laststandcoin = class {
        static Name = "LastStandCoin"
        static Filename = "sc/effects.sc"
        static Groundglowexportname = "pickup_glow_gold"
        static Loopingeffect = "laststand_coin_twinkle"
        static Value = 100
        static Triggerrangesubtiles = 4
        static Canbepickedup = true
        static Spawneffect = "Spawn_plasmoid"
        static Scw = "sc3d/item_last_stand_coin.scw"
        static Scwenemy = "sc3d/item_last_stand_coin.scw"
        static Usegeneratedshadow = true
        static Layer = "Above"
        static RowID = 115
    }
    static Doorhorizontal = class {
        static Name = "DoorHorizontal"
        static Aligntotiles = true
        static Usegeneratedshadow = true
        static Layer = "Object"
        static RowID = 116
    }
    static Doorvertical = class {
        static Name = "DoorVertical"
        static Aligntotiles = true
        static Usegeneratedshadow = true
        static Layer = "Object"
        static RowID = 117
    }
    static Buttonpress = class {
        static Name = "ButtonPress"
        static Aligntotiles = true
        static Triggerrangesubtiles = 2
        static Usegeneratedshadow = true
        static Layer = "GroundLow"
        static RowID = 118
    }
    static Buttonhold = class {
        static Name = "ButtonHold"
        static Aligntotiles = true
        static Triggerrangesubtiles = 2
        static Usegeneratedshadow = true
        static Layer = "GroundLow"
        static RowID = 119
    }
    static Portal = class {
        static Name = "Portal"
        static Filename = "sc/effects_brawler_gray.sc"
        static Value = 1
        static Triggerrangesubtiles = 3
        static Layer = "GroundTop"
        static Customareaeffect1 = "DoorManPortalLeave"
        static Customareaeffect2 = "DoorManPortalArrive"
        static RowID = 120
    }
    static Gray003portal = class {
        static Name = "Gray003Portal"
        static Parentitemforskin = "Portal"
        static Exportname = "gray_003_ulti_start"
        static Exportnameenemy = "gray_003_ulti_start_red"
        static Value = 1
        static Triggerrangesubtiles = 3
        static Activateeffect = "gray_003_ulti_active"
        static Layer = "GroundTop"
        static RowID = 121
    }
    static Gray004portal = class {
        static Name = "Gray004Portal"
        static Parentitemforskin = "Portal"
        static Exportname = "gray_004_ulti_start"
        static Exportnameenemy = "gray_004_ulti_start_red"
        static Value = 1
        static Triggerrangesubtiles = 3
        static Activateeffect = "gray_004_ulti_active"
        static Layer = "GroundTop"
        static RowID = 122
    }
    static Eventcollecttoken = class {
        static Name = "EventCollectToken"
        static Filename = "sc/effects.sc"
        static Groundglowexportname = "pickup_glow_gold"
        static Loopingeffect = "laststand_coin_twinkle"
        static Value = 100
        static Triggerrangesubtiles = 4
        static Canbepickedup = true
        static Spawneffect = "Spawn_plasmoid"
        static Scw = "sc3d/item_skull_coin_geo.glb"
        static Scwenemy = "sc3d/item_skull_coin_geo.glb"
        static Usegeneratedshadow = true
        static Layer = "Above"
        static RowID = 123
    }
    static Healthpack = class {
        static Name = "HealthPack"
        static Filename = "sc/effects.sc"
        static Shadowexportname = "projectile_shadow"
        static Value = 3000
        static Triggerrangesubtiles = 4
        static Canbepickedup = true
        static Spawneffect = "Spawn_buff"
        static Scw = "sc3d/item_health_boost_geo.glb"
        static Scwenemy = "sc3d/item_health_boost_geo.glb"
        static Usegeneratedshadow = true
        static Layer = "Above"
        static RowID = 124
    }
    static Shadowmushroom = class {
        static Name = "ShadowMushroom"
        static Filename = "sc/effects.sc"
        static Shadowexportname = "projectile_shadow"
        static Loopingeffect = "Blob_fx"
        static Statuseffectally = "ShadowMushroomHot"
        static Statuseffectenemy = "ShadowMushroomDot"
        static Triggerrangesubtiles = 4
        static Canbepickedup = true
        static Spawneffect = "Spawn_buff"
        static Scw = "sc3d/item_cordelius_shroom_blue_geo.glb"
        static Scwenemy = "sc3d/item_cordelius_shroom_red_geo.glb"
        static Usegeneratedshadow = true
        static Layer = "Above"
        static RowID = 125
    }
    static Shadowrealmmarker = class {
        static Name = "ShadowRealmMarker"
        static Filename = "sc/effects_brawler.sc"
        static Exportname = "cordelius_def_realm_indicator"
        static Exportnameenemy = "cordelius_def_realm_indicator"
        static Loopingeffect = "cordelius_def_indicator"
        static Layer = "GroundTop"
        static RowID = 126
    }
    static Conductorsign = class {
        static Name = "ConductorSign"
        static Loopingeffect = "conductor_def_sign_warning"
        static Triggerareaeffect = "ConductorSignArea"
        static Destroyareaeffect = "ConductorSignAreaDestroy"
        static Activateeffect = "conductor_def_sign_active"
        static Scw = "sc3d/item_chochosign_blue_geo.glb"
        static Scwenemy = "sc3d/item_chochosign_red_geo.glb"
        static Usegeneratedshadow = true
        static Layer = "Object"
        static RowID = 127
    }
    static Conductor002sign = class {
        static Name = "Conductor002Sign"
        static Parentitemforskin = "ConductorSign"
        static Loopingeffect = "conductor_def_sign_warning"
        static Triggerareaeffect = "Conductor002SignArea"
        static Destroyareaeffect = "Conductor002SignAreaDestroy"
        static Activateeffect = "conductor_def_sign_active"
        static Scw = "sc3d/item_pincer_chochosign_blue_geo.glb"
        static Scwenemy = "sc3d/item_pincer_chochosign_red_geo.glb"
        static Usegeneratedshadow = true
        static Layer = "Object"
        static RowID = 128
    }
    static Conductor003sign = class {
        static Name = "Conductor003Sign"
        static Parentitemforskin = "ConductorSign"
        static Loopingeffect = "conductor_def_sign_warning"
        static Triggerareaeffect = "Conductor003SignArea"
        static Destroyareaeffect = "Conductor003SignAreaDestroy"
        static Activateeffect = "conductor_def_sign_active"
        static Scw = "sc3d/item_electrolord_chochosign_blue_geo.glb"
        static Scwenemy = "sc3d/item_electrolord_chochosign_red_geo.glb"
        static Usegeneratedshadow = true
        static Layer = "Object"
        static RowID = 129
    }
    static Extractionzone = class {
        static Name = "ExtractionZone"
        static Triggerrangesubtiles = 5
        static Triggerareaeffect = "TeleportTileLeave"
        static Spawneffect = "Spawn_plasmoid"
        static Scw = "sc3d/extraction_teleport_tile_geo.glb"
        static Scwenemy = "sc3d/extraction_teleport_tile_geo.glb"
        static Scwtoplayer = "sc3d/extraction_teleport_effect_geo.glb"
        static Usegeneratedshadow = true
        static Layer = "GroundTop"
        static RowID = 130
    }
    static Extractionpoint = class {
        static Name = "ExtractionPoint"
        static Filename = "sc/effects.sc"
        static Shadowexportname = "projectile_shadow_mid"
        static Groundglowexportname = "pickup_glow"
        static Loopingeffect = "item_extraction_trophy"
        static Triggerrangesubtiles = 4
        static Canbepickedup = true
        static Spawneffect = "Spawn_plasmoid"
        static Scw = "sc3d/item_extraction_trophy_geo.glb"
        static Scwenemy = "sc3d/item_extraction_trophy_geo.glb"
        static Usegeneratedshadow = true
        static Layer = "Above"
        static RowID = 131
    }
    static Hypercharge = class {
        static Name = "Hypercharge"
        static Filename = "sc/effects.sc"
        static Shadowexportname = "projectile_shadow"
        static Loopingeffect = "item_hypercharge"
        static Value = 10
        static Value2 = 400
        static Triggerrangesubtiles = 4
        static Canbepickedup = true
        static Spawneffect = "Spawn_plasmoid"
        static Scw = "sc3d/item_hypercharge_geo.glb"
        static Scwenemy = "sc3d/item_hypercharge_geo.glb"
        static Usegeneratedshadow = true
        static Layer = "Above"
        static RowID = 132
    }
    static Clusteroverchargedmine = class {
        static Name = "ClusterOverchargedMine"
        static Filename = "sc/effects_brawler.sc"
        static Exportname = "tick_def_oc_mine"
        static Exportnameenemy = "tick_def_oc_mine_red"
        static Shadowexportname = "shadow_normal_circle"
        static Value = 800
        static Value2 = 2000
        static Triggerrangesubtiles = 200
        static Triggerareaeffect = "ClusterBombOverchargedExplosion2"
        static Canbepickedup = true
        static Showalways = true
        static Randomstartframe = 2
        static Layer = "Above"
        static RowID = 133
    }
    static Godzillatransform = class {
        static Name = "GodzillaTransform"
        static Filename = "sc/effects.sc"
        static Shadowexportname = "projectile_shadow"
        static Groundglowexportname = "pickup_glow_green"
        static Loopingeffect = "powerup_fx_blue"
        static Value = 10
        static Value2 = 400
        static Triggerrangesubtiles = 4
        static Canbepickedup = true
        static Spawneffect = "Spawn_plasmoid"
        static Scw = "sc3d/item_monster_geo.glb"
        static Scwenemy = "sc3d/item_bolt.scw"
        static Layer = "Above"
        static RowID = 134
    }
    static Overchargedboxofbombs = class {
        static Name = "OverchargedBoxOfBombs"
        static Filename = "sc/effects.sc"
        static Groundglowexportname = "pickup_glow_green"
        static Value = 6
        static Value2 = 8
        static Spawneffect = "Spawn_plasmoid"
        static Layer = "Above"
        static RowID = 135
    }
    static Overchargedbomb = class {
        static Name = "OverchargedBomb"
        static Filename = "sc/effects_brawler.sc"
        static Exportname = "piper_def_oc_ulti_projectile"
        static Exportnameenemy = "piper_def_oc_ulti_projectile_red"
        static Shadowexportname = "shadow_normal_circle_big"
        static Value = 800
        static Value2 = 300
        static Triggerrangesubtiles = 200
        static Triggerareaeffect = "SniperOverchargedBombExplosion"
        static Canbepickedup = true
        static Spawneffect = "Spawn_sniper_bomb"
        static Randomstartframe = 2
        static Layer = "Above"
        static RowID = 136
    }
    static Dogtag = class {
        static Name = "DogTag"
        static Filename = "sc/effects.sc"
        static Shadowexportname = "projectile_shadow"
        static Groundglowexportname = "pickup_glow_gold"
        static Loopingeffect = "dog_tag_glow"
        static Value = 14
        static Lifetime = 214
        static Disappearingtime = 60
        static Triggerrangesubtiles = 4
        static Canbepickedup = true
        static Spawneffect = "dog_tag_spawn"
        static Activateeffect = "dog_tag_highlight"
        static Scw = "sc3d/item_angelsdemons_blue_geo.glb"
        static Scwenemy = "sc3d/item_angelsdemons_red_geo.glb"
        static Layer = "Above"
        static RowID = 137
    }
    static Controllerarchetypemine = class {
        static Name = "ControllerArchetypeMine"
        static Filename = "sc/effects_brawler.sc"
        static Exportname = "sb_controller_bubble"
        static Exportnameenemy = "sb_controller_bubble_red"
        static Shadowexportname = "shadow_normal_circle"
        static Value = 800
        static Value2 = 20
        static Lifetime = 60
        static Triggerrangesubtiles = 3
        static Triggerareaeffect = "ClusterBombExplosion_SB"
        static Destroyareaeffect = "SbcontrollerAreaDestroy"
        static Canbepickedup = true
        static Showalways = true
        static Randomstartframe = 2
        static Layer = "Above"
        static RowID = 138
    }
    static Cash = class {
        static Name = "Cash"
        static Filename = "sc/effects.sc"
        static Shadowexportname = "projectile_shadow_mid"
        static Groundglowexportname = "pickup_glow_green"
        static Loopingeffect = "trash_pickup_item_fx"
        static Value = 10
        static Value2 = 400
        static Triggerrangesubtiles = 4
        static Canbepickedup = true
        static Spawneffect = "Spawn_buff"
        static Scw = "sc3d/item_trash_pickup_geo.glb"
        static Scwenemy = "sc3d/item_trash_pickup_geo.glb"
        static Usegeneratedshadow = true
        static Layer = "Above"
        static RowID = 139
    }
    static Stickybomboverchargedulti = class {
        static Name = "StickyBombOverchargedUlti"
        static Parentitemforskin = "StickyBombUlti"
        static Filename = "sc/effects_brawler.sc"
        static Exportname = "sticky_def_oc_ulti_reached"
        static Exportnameenemy = "sticky_def_oc_ulti_reached_red"
        static Value = 800
        static Value2 = 1150
        static Triggerrangesubtiles = 3
        static Triggerareaeffect = "StickyBombOverchargedUltiExplosion"
        static Spawneffect = "Spawn_buff"
        static Activateeffect = "sticky_def_oc_atk_hit"
        static Showalways = true
        static Layer = "Above"
        static RowID = 140
    }
    static Petwars = class {
        static Name = "PetWars"
        static Filename = "sc/effects.sc"
        static Shadowexportname = "projectile_shadow"
        static Groundglowexportname = "pickup_glow_green"
        static Loopingeffect = "petwars_item_glow"
        static Triggerrangesubtiles = 4
        static Canbepickedup = true
        static Spawneffect = "petwars_item_spawn"
        static Scw = "sc3d/item_petwars_geo.glb"
        static Scwenemy = "sc3d/item_petwars_geo.glb"
        static Layer = "Above"
        static RowID = 141
    }
    static Overchargedportal = class {
        static Name = "OverChargedPortal"
        static Parentitemforskin = "Portal"
        static Filename = "sc/effects_brawler2.sc"
        static Exportname = "gray_def_oc_ulti_start"
        static Exportnameenemy = "gray_def_oc_ulti_start_red"
        static Loopingeffect = "gray_def_oc_ulti_start_finger"
        static Value = 1
        static Triggerrangesubtiles = 3
        static Activateeffect = "gray_def_oc_ulti_active"
        static Layer = "GroundTop"
        static Itemclip = "gray_def_oc_ulti_ready"
        static Itemreadyeffect = "gray_def_oc_ulti_ready"
        static Customareaeffect1 = "DoorManPortalOverchargedLeave"
        static Customareaeffect2 = "DoorManPortalOverchargedArrive"
        static RowID = 142
    }
    static Overchargedmine = class {
        static Name = "OverchargedMine"
        static Filename = "sc/effects_brawler.sc"
        static Exportname = "bo_def_oc_ulti_mine"
        static Exportnameenemy = "bo_def_oc_ulti_mine_red"
        static Value = 800
        static Value2 = 1150
        static Triggerrangesubtiles = 3
        static Triggerareaeffect = "Bo_def_overcharged_ulti2_area"
        static Canbepickedup = true
        static Spawneffect = "bo_def_ulti2_spawn"
        static Randomstartframe = 2
        static Layer = "Above"
        static RowID = 143
    }
    static Boxofoverchargedmines = class {
        static Name = "BoxOfOverchargedMines"
        static Filename = "sc/effects.sc"
        static Groundglowexportname = "pickup_glow_green"
        static Value = 5
        static Value2 = 7
        static Spawneffect = "Spawn_plasmoid"
        static Layer = "Above"
        static RowID = 144
    }
    static Morningstargroundedweapon = class {
        static Name = "MorningstarGroundedWeapon"
        static Filename = "sc/effects_brawler_lumi.sc"
        static Exportname = "lumi_def_atk_morningstar"
        static Exportnameenemy = "lumi_def_atk_morningstar_red"
        static Loopingeffect = "lumi_def_atk_still_morningstar_loop"
        static Followsourcedimension = true
        static Spawneffect = "Spawn_plasmoid"
        static Layer = "Above"
        static RowID = 145
    }
    static Morningstar002groundedweapon = class {
        static Name = "Morningstar002GroundedWeapon"
        static Parentitemforskin = "MorningstarGroundedWeapon"
        static Filename = "sc/effects_brawler_lumi.sc"
        static Exportname = "lumi_002_atk_morningstar"
        static Exportnameenemy = "lumi_002_atk_morningstar_red"
        static Loopingeffect = "lumi_002_atk_still_morningstar_loop"
        static Followsourcedimension = true
        static Spawneffect = "Spawn_plasmoid"
        static Randomstartframe = 2
        static Layer = "Above"
        static RowID = 146
    }
    static Unodeck = class {
        static Name = "UNODeck"
        static Filename = "sc/effects_brawler.sc"
        static Triggerrangesubtiles = 5
        static Scw = "sc3d/item_token_toss_base_geo.glb"
        static Scwenemy = "sc3d/item_token_toss_base_geo.glb"
        static Scwtoplayer = "sc3d/item_token_toss_base_top_geo.glb"
        static Usegeneratedshadow = true
        static Layer = "GroundLow"
        static Customareaeffect1 = "DoorManPortalLeave"
        static Customareaeffect2 = "DoorManPortalArrive"
        static RowID = 147
    }
    static Treasurespawner = class {
        static Name = "TreasureSpawner"
        static Triggerrangesubtiles = 4
        static Spawneffect = "Spawn_plasmoid"
        static Activateeffect = "treasure_plate_trigger"
        static Scw = "sc3d/item_treasure_spawner_geo.glb"
        static Scwenemy = "sc3d/item_treasure_spawner_geo.glb"
        static Usegeneratedshadow = true
        static Layer = "GroundLow"
        static Itemreadyeffect = "treasure_plate_reset"
        static RowID = 148
    }
    static Treasure = class {
        static Name = "Treasure"
        static Filename = "sc/effects.sc"
        static Groundglowexportname = "pickup_glow_gold"
        static Loopingeffect = "treasure_hunt_pickup"
        static Triggerrangesubtiles = 4
        static Canbepickedup = true
        static Spawneffect = "Spawn_treasure"
        static Scw = "sc3d/item_treasure_geo.glb"
        static Scwenemy = "sc3d/item_treasure_geo.glb"
        static Layer = "Above"
        static RowID = 149
    }
    static Samuraipoint = class {
        static Name = "SamuraiPoint"
        static Filename = "sc/effects.sc"
        static Shadowexportname = "projectile_shadow"
        static Groundglowexportname = "pickup_glow_gold"
        static Value2 = 1
        static Lifetime = 4200
        static Triggerrangesubtiles = 4
        static Destroyareaeffect = "SamuraiItemPickup"
        static Canbepickedup = true
        static Activateeffect = "golden_pickup_glow"
        static Scw = "sc3d/item_samurai_smash_pickup_regular_geo.glb"
        static Scwenemy = "sc3d/item_samurai_smash_pickup_transparent_geo.glb"
        static Layer = "Above"
        static RowID = 150
    }
    static Trailwaypoint = class {
        static Name = "TrailWaypoint"
        static Triggerrangesubtiles = 6
        static Triggerareaeffect = "ConductorSignArea"
        static Destroyareaeffect = "ConductorSignAreaDestroy"
        static Activateeffect = "conductor_def_sign_active"
        static Scw = "sc3d/default_goal_radius_geo.glb"
        static Scwenemy = "sc3d/default_goal_radius_geo.glb"
        static Scwtoplayer = "sc3d/default_goal_pole_geo.glb"
        static Usegeneratedshadow = true
        static Layer = "Above"
        static RowID = 151
    }
    static Megatickmine = class {
        static Name = "MegaTickMine"
        static Parentitemforskin = "ClusterMine"
        static Filename = "sc/effects_brawler_tick.sc"
        static Exportname = "tick_009_atk2_projectile"
        static Exportnameenemy = "tick_009_atk2_projectile_red"
        static Loopingeffect = "gen_no_hit"
        static Value = 800
        static Value2 = 2000
        static Triggerrangesubtiles = 200
        static Triggerareaeffect = "Tick009Explosion2"
        static Canbepickedup = true
        static Showalways = true
        static Randomstartframe = 2
        static Layer = "Above"
        static RowID = 152
    }
}

export default Items;