class Playerframes {
    static Battlecardframerankedbronzebg = class {
        static Name = "battle_card_frame_ranked_bronze_bg"
        static Iconswf = "sc/ui.sc"
        static Iconexportname = "battle_card_frame_ranked_bronze_bg"
        static Iconexportnamefront = "battle_card_frame_ranked_bronze_front"
        static Iconexportnamelevels = "battle_card_frame_ranked_bronze_levels"
        static Banner = "battle_card_frame_ranked_bronze_2024_ui"
        static Tier = 1
        static Season = 1
        static Frametype = "Ranked"
        static Delaymilliseconds = 200
        static Descriptiontid = "TID_BATTLE_CARD_NAME_BRONZE_2024"
        static RowID = 1
    }
    static Battlecardframerankedsilverbg = class {
        static Name = "battle_card_frame_ranked_silver_bg"
        static Iconswf = "sc/ui.sc"
        static Iconexportname = "battle_card_frame_ranked_silver_bg"
        static Iconexportnamefront = "battle_card_frame_ranked_silver_front"
        static Iconexportnamelevels = "battle_card_frame_ranked_silver_levels"
        static Banner = "battle_card_frame_ranked_silver_2024_ui"
        static Tier = 2
        static Season = 1
        static Frametype = "Ranked"
        static Delaymilliseconds = 200
        static Descriptiontid = "TID_BATTLE_CARD_NAME_SILVER_2024"
        static RowID = 2
    }
    static Battlecardframerankedgoldbg = class {
        static Name = "battle_card_frame_ranked_gold_bg"
        static Iconswf = "sc/ui.sc"
        static Iconexportname = "battle_card_frame_ranked_gold_bg"
        static Iconexportnamefront = "battle_card_frame_ranked_gold_front"
        static Iconexportnamelevels = "battle_card_frame_ranked_gold_levels"
        static Banner = "battle_card_frame_ranked_gold_2024_ui"
        static Tier = 3
        static Season = 1
        static Frametype = "Ranked"
        static Delaymilliseconds = 200
        static Descriptiontid = "TID_BATTLE_CARD_NAME_GOLD_2024"
        static RowID = 3
    }
    static Battlecardframerankeddiamondbg = class {
        static Name = "battle_card_frame_ranked_diamond_bg"
        static Iconswf = "sc/ui.sc"
        static Iconexportname = "battle_card_frame_ranked_diamond_bg"
        static Iconexportnamefront = "battle_card_frame_ranked_diamond_front"
        static Iconexportnamelevels = "battle_card_frame_ranked_diamond_levels"
        static Banner = "battle_card_frame_ranked_diamond_2024_ui"
        static Tier = 4
        static Season = 1
        static Frametype = "Ranked"
        static Delaymilliseconds = 200
        static Descriptiontid = "TID_BATTLE_CARD_NAME_DIAMOND_2024"
        static RowID = 4
    }
    static Battlecardframerankedmythicbg = class {
        static Name = "battle_card_frame_ranked_mythic_bg"
        static Iconswf = "sc/ui.sc"
        static Iconexportname = "battle_card_frame_ranked_mythic_bg"
        static Iconexportnamefront = "battle_card_frame_ranked_mythic_front"
        static Iconexportnamelevels = "battle_card_frame_ranked_mythic_levels"
        static Banner = "battle_card_frame_ranked_mythic_2024_ui"
        static Tier = 5
        static Season = 1
        static Frametype = "Ranked"
        static Delaymilliseconds = 200
        static Descriptiontid = "TID_BATTLE_CARD_NAME_MYTHIC_2024"
        static RowID = 5
    }
    static Battlecardframerankedlegendarybg = class {
        static Name = "battle_card_frame_ranked_legendary_bg"
        static Iconswf = "sc/ui.sc"
        static Iconexportname = "battle_card_frame_ranked_legendary_bg"
        static Iconexportnamefront = "battle_card_frame_ranked_legendary_front"
        static Iconexportnamelevels = "battle_card_frame_ranked_legendary_levels"
        static Banner = "battle_card_frame_ranked_legendary_2024_ui"
        static Tier = 6
        static Season = 1
        static Frametype = "Ranked"
        static Delaymilliseconds = 200
        static Descriptiontid = "TID_BATTLE_CARD_NAME_LEGENDARY_2024"
        static RowID = 6
    }
    static Battlecardframerankedmastersbg = class {
        static Name = "battle_card_frame_ranked_masters_bg"
        static Iconswf = "sc/ui.sc"
        static Iconexportname = "battle_card_frame_ranked_masters_bg"
        static Iconexportnamefront = "battle_card_frame_ranked_masters_front"
        static Iconexportnamelevels = "battle_card_frame_ranked_masters_levels"
        static Banner = "battle_card_frame_ranked_masters_2024_ui"
        static Tier = 7
        static Season = 1
        static Frametype = "Ranked"
        static Delaymilliseconds = 200
        static Descriptiontid = "TID_BATTLE_CARD_NAME_MASTERS_2024"
        static RowID = 7
    }
    static Globalframe = class {
        static Name = "globalFrame"
        static Iconswf = "sc/ui.sc"
        static Iconexportname = "battle_card_frame_fame_earth_bg"
        static Banner = "battle_card_frame_fame_earth_ui"
        static Iconontop = "fame_big_tier_1"
        static Tier = 1
        static Frametype = "Fame"
        static Unlockedbyfame = "Global1"
        static Delaymilliseconds = 900
        static Descriptiontid = "TID_BATTLE_CARD_NAME_GLOBAL_FAME"
        static RowID = 8
    }
    static Lunarframe = class {
        static Name = "lunarFrame"
        static Iconswf = "sc/ui.sc"
        static Iconexportname = "battle_card_frame_fame_moon_bg"
        static Banner = "battle_card_frame_fame_moon_ui"
        static Iconontop = "fame_big_tier_2"
        static Tier = 2
        static Frametype = "Fame"
        static Unlockedbyfame = "Lunar1"
        static Delaymilliseconds = 900
        static Descriptiontid = "TID_BATTLE_CARD_NAME_LUNAR_FAME"
        static RowID = 9
    }
    static Martialframe = class {
        static Name = "martialFrame"
        static Iconswf = "sc/ui.sc"
        static Iconexportname = "battle_card_frame_fame_mars_bg"
        static Banner = "battle_card_frame_fame_mars_ui"
        static Iconontop = "fame_big_tier_3"
        static Tier = 3
        static Frametype = "Fame"
        static Unlockedbyfame = "Martial1"
        static Delaymilliseconds = 900
        static Descriptiontid = "TID_BATTLE_CARD_NAME_MARTIAN_FAME"
        static RowID = 10
    }
    static Saturnalframe = class {
        static Name = "saturnalFrame"
        static Iconswf = "sc/ui.sc"
        static Iconexportname = "battle_card_frame_fame_saturn_bg"
        static Banner = "battle_card_frame_fame_saturn_ui"
        static Iconontop = "fame_big_tier_4"
        static Tier = 4
        static Frametype = "Fame"
        static Unlockedbyfame = "Saturnal1"
        static Delaymilliseconds = 900
        static Descriptiontid = "TID_BATTLE_CARD_NAME_SATURNAL_FAME"
        static RowID = 11
    }
    static Solarframe = class {
        static Name = "solarFrame"
        static Iconswf = "sc/ui.sc"
        static Iconexportname = "battle_card_frame_fame_sun_bg"
        static Banner = "battle_card_frame_fame_sun_ui"
        static Iconontop = "fame_big_tier_5"
        static Tier = 5
        static Frametype = "Fame"
        static Unlockedbyfame = "Solar1"
        static Delaymilliseconds = 900
        static Descriptiontid = "TID_BATTLE_CARD_NAME_SOLAR_FAME"
        static RowID = 12
    }
    static Meteorframe = class {
        static Name = "meteorFrame"
        static Iconswf = "sc/ui.sc"
        static Iconexportname = "battle_card_frame_fame_meteor_bg"
        static Banner = "battle_card_frame_fame_meteor_ui"
        static Iconontop = "fame_big_tier_6"
        static Tier = 6
        static Frametype = "Fame"
        static Unlockedbyfame = "Meteor1"
        static Delaymilliseconds = 900
        static Descriptiontid = "TID_BATTLE_CARD_NAME_METEORIC_FAME"
        static RowID = 13
    }
    static Alienframe = class {
        static Name = "alienFrame"
        static Iconswf = "sc/ui.sc"
        static Iconexportname = "battle_card_frame_fame_alien_bg"
        static Banner = "battle_card_frame_fame_alien_ui"
        static Iconontop = "fame_big_tier_7"
        static Tier = 7
        static Frametype = "Fame"
        static Unlockedbyfame = "Alien1"
        static Delaymilliseconds = 900
        static Descriptiontid = "TID_BATTLE_CARD_NAME_ALIEN_FAME"
        static RowID = 14
    }
    static Battlecardframerankedbronzebg2 = class {
        static Name = "battle_card_frame_ranked_bronze_bg_2"
        static Iconswf = "sc/ui.sc"
        static Iconexportname = "battle_card_frame_ranked_bronze_bg_2"
        static Iconexportnamefront = "battle_card_frame_ranked_bronze_front_2"
        static Iconexportnamelevels = "battle_card_frame_ranked_bronze_levels_2"
        static Banner = "battle_card_frame_ranked_bronze_2025_ui"
        static Tier = 1
        static Season = 2
        static Frametype = "Ranked"
        static Delaymilliseconds = 200
        static Descriptiontid = "TID_BATTLE_CARD_NAME_BRONZE_2025"
        static RowID = 15
    }
    static Battlecardframerankedsilverbg2 = class {
        static Name = "battle_card_frame_ranked_silver_bg_2"
        static Iconswf = "sc/ui.sc"
        static Iconexportname = "battle_card_frame_ranked_silver_bg_2"
        static Iconexportnamefront = "battle_card_frame_ranked_silver_front_2"
        static Iconexportnamelevels = "battle_card_frame_ranked_silver_levels_2"
        static Banner = "battle_card_frame_ranked_silver_2025_ui"
        static Tier = 2
        static Season = 2
        static Frametype = "Ranked"
        static Delaymilliseconds = 200
        static Descriptiontid = "TID_BATTLE_CARD_NAME_SILVER_2025"
        static RowID = 16
    }
    static Battlecardframerankedgoldbg2 = class {
        static Name = "battle_card_frame_ranked_gold_bg_2"
        static Iconswf = "sc/ui.sc"
        static Iconexportname = "battle_card_frame_ranked_gold_bg_2"
        static Iconexportnamefront = "battle_card_frame_ranked_gold_front_2"
        static Iconexportnamelevels = "battle_card_frame_ranked_gold_levels_2"
        static Banner = "battle_card_frame_ranked_gold_2025_ui"
        static Tier = 3
        static Season = 2
        static Frametype = "Ranked"
        static Delaymilliseconds = 200
        static Descriptiontid = "TID_BATTLE_CARD_NAME_GOLD_2025"
        static RowID = 17
    }
    static Battlecardframerankeddiamondbg2 = class {
        static Name = "battle_card_frame_ranked_diamond_bg_2"
        static Iconswf = "sc/ui.sc"
        static Iconexportname = "battle_card_frame_ranked_diamond_bg_2"
        static Iconexportnamefront = "battle_card_frame_ranked_diamond_front_2"
        static Iconexportnamelevels = "battle_card_frame_ranked_diamond_levels_2"
        static Banner = "battle_card_frame_ranked_diamond_2025_ui"
        static Tier = 4
        static Season = 2
        static Frametype = "Ranked"
        static Delaymilliseconds = 200
        static Descriptiontid = "TID_BATTLE_CARD_NAME_DIAMOND_2025"
        static RowID = 18
    }
    static Battlecardframerankedmythicbg2 = class {
        static Name = "battle_card_frame_ranked_mythic_bg_2"
        static Iconswf = "sc/ui.sc"
        static Iconexportname = "battle_card_frame_ranked_mythic_bg_2"
        static Iconexportnamefront = "battle_card_frame_ranked_mythic_front_2"
        static Iconexportnamelevels = "battle_card_frame_ranked_mythic_levels_2"
        static Banner = "battle_card_frame_ranked_mythic_2025_ui"
        static Tier = 5
        static Season = 2
        static Frametype = "Ranked"
        static Delaymilliseconds = 200
        static Descriptiontid = "TID_BATTLE_CARD_NAME_MYTHIC_2025"
        static RowID = 19
    }
    static Battlecardframerankedlegendarybg2 = class {
        static Name = "battle_card_frame_ranked_legendary_bg_2"
        static Iconswf = "sc/ui.sc"
        static Iconexportname = "battle_card_frame_ranked_legendary_bg_2"
        static Iconexportnamefront = "battle_card_frame_ranked_legendary_front_2"
        static Iconexportnamelevels = "battle_card_frame_ranked_legendary_levels_2"
        static Banner = "battle_card_frame_ranked_legendary_2025_ui"
        static Tier = 6
        static Season = 2
        static Frametype = "Ranked"
        static Delaymilliseconds = 200
        static Descriptiontid = "TID_BATTLE_CARD_NAME_LEGENDARY_2025"
        static RowID = 20
    }
    static Battlecardframerankedmastersbg2 = class {
        static Name = "battle_card_frame_ranked_masters_bg_2"
        static Iconswf = "sc/ui.sc"
        static Iconexportname = "battle_card_frame_ranked_masters_bg_2"
        static Iconexportnamefront = "battle_card_frame_ranked_masters_front_2"
        static Iconexportnamelevels = "battle_card_frame_ranked_masters_levels_2"
        static Banner = "battle_card_frame_ranked_masters_2025_ui"
        static Tier = 7
        static Season = 2
        static Frametype = "Ranked"
        static Delaymilliseconds = 200
        static Descriptiontid = "TID_BATTLE_CARD_NAME_MASTERS_2025"
        static RowID = 21
    }
    static Battlecardframerankedprobg2 = class {
        static Name = "battle_card_frame_ranked_pro_bg_2"
        static Iconswf = "sc/ui.sc"
        static Iconexportname = "battle_card_frame_ranked_pro_bg_2"
        static Iconexportnamefront = "battle_card_frame_ranked_pro_front_2"
        static Iconexportnamelevels = "battle_card_frame_ranked_pro_levels_2"
        static Banner = "battle_card_frame_ranked_pro_2025_ui"
        static Tier = 8
        static Season = 2
        static Frametype = "Ranked"
        static Delaymilliseconds = 200
        static Descriptiontid = "TID_BATTLE_CARD_NAME_PRO_2025"
        static RowID = 22
    }
    static Recordsframelevel1 = class {
        static Name = "records_frame_level_1"
        static Iconswf = "sc/ui_achievements.sc"
        static Iconexportname = "battle_card_frame_records_tier1_bg"
        static Banner = "battle_card_frame_records_tier1_ui"
        static Iconontop = "battle_card_frame_records_tier1_levels"
        static Tier = 1
        static Frametype = "Records"
        static Delaymilliseconds = 200
        static Descriptiontid = "TID_RECORD_CARD_NAME_LEVEL_1"
        static RowID = 23
    }
    static Recordsframelevel2 = class {
        static Name = "records_frame_level_2"
        static Iconswf = "sc/ui_achievements.sc"
        static Iconexportname = "battle_card_frame_records_tier2_bg"
        static Banner = "battle_card_frame_records_tier2_ui"
        static Iconontop = "battle_card_frame_records_tier2_levels"
        static Tier = 2
        static Frametype = "Records"
        static Delaymilliseconds = 200
        static Descriptiontid = "TID_RECORD_CARD_NAME_LEVEL_2"
        static RowID = 24
    }
    static Recordsframelevel3 = class {
        static Name = "records_frame_level_3"
        static Iconswf = "sc/ui_achievements.sc"
        static Iconexportname = "battle_card_frame_records_tier3_bg"
        static Banner = "battle_card_frame_records_tier3_ui"
        static Iconontop = "battle_card_frame_records_tier3_levels"
        static Tier = 3
        static Frametype = "Records"
        static Delaymilliseconds = 200
        static Descriptiontid = "TID_RECORD_CARD_NAME_LEVEL_3"
        static RowID = 25
    }
    static Recordsframelevel4 = class {
        static Name = "records_frame_level_4"
        static Iconswf = "sc/ui_achievements.sc"
        static Iconexportname = "battle_card_frame_records_tier4_bg"
        static Banner = "battle_card_frame_records_tier4_ui"
        static Iconontop = "battle_card_frame_records_tier4_levels"
        static Tier = 4
        static Frametype = "Records"
        static Delaymilliseconds = 200
        static Descriptiontid = "TID_RECORD_CARD_NAME_LEVEL_4"
        static RowID = 26
    }
    static Recordsframelevel5 = class {
        static Name = "records_frame_level_5"
        static Iconswf = "sc/ui_achievements.sc"
        static Iconexportname = "battle_card_frame_records_tier5_bg"
        static Banner = "battle_card_frame_records_tier5_ui"
        static Iconontop = "battle_card_frame_records_tier5_levels"
        static Tier = 5
        static Frametype = "Records"
        static Delaymilliseconds = 200
        static Descriptiontid = "TID_RECORD_CARD_NAME_LEVEL_5"
        static RowID = 27
    }
    static Recordsframelevel6 = class {
        static Name = "records_frame_level_6"
        static Iconswf = "sc/ui_achievements.sc"
        static Iconexportname = "battle_card_frame_records_tier6_bg"
        static Banner = "battle_card_frame_records_tier6_ui"
        static Iconontop = "battle_card_frame_records_tier6_levels"
        static Tier = 6
        static Frametype = "Records"
        static Delaymilliseconds = 200
        static Descriptiontid = "TID_RECORD_CARD_NAME_LEVEL_6"
        static RowID = 28
    }
    static Recordsframelevel7 = class {
        static Name = "records_frame_level_7"
        static Iconswf = "sc/ui_achievements.sc"
        static Iconexportname = "battle_card_frame_records_tier7_bg"
        static Banner = "battle_card_frame_records_tier7_ui"
        static Iconontop = "battle_card_frame_records_tier7_levels"
        static Tier = 7
        static Frametype = "Records"
        static Delaymilliseconds = 200
        static Descriptiontid = "TID_RECORD_CARD_NAME_LEVEL_7"
        static RowID = 29
    }
    static Recordsframelevel8 = class {
        static Name = "records_frame_level_8"
        static Iconswf = "sc/ui_achievements.sc"
        static Iconexportname = "battle_card_frame_records_tier8_bg"
        static Banner = "battle_card_frame_records_tier8_ui"
        static Iconontop = "battle_card_frame_records_tier8_levels"
        static Tier = 8
        static Frametype = "Records"
        static Delaymilliseconds = 200
        static Descriptiontid = "TID_RECORD_CARD_NAME_LEVEL_8"
        static RowID = 30
    }
    static Recordsframelevel9 = class {
        static Name = "records_frame_level_9"
        static Iconswf = "sc/ui_achievements.sc"
        static Iconexportname = "battle_card_frame_records_tier9_bg"
        static Banner = "battle_card_frame_records_tier9_ui"
        static Iconontop = "battle_card_frame_records_tier9_levels"
        static Tier = 9
        static Frametype = "Records"
        static Delaymilliseconds = 200
        static Descriptiontid = "TID_RECORD_CARD_NAME_LEVEL_9"
        static RowID = 31
    }
    static Recordsframelevel10 = class {
        static Name = "records_frame_level_10"
        static Iconswf = "sc/ui_achievements.sc"
        static Iconexportname = "battle_card_frame_records_tier10_bg"
        static Banner = "battle_card_frame_records_tier10_ui"
        static Iconontop = "battle_card_frame_records_tier10_levels"
        static Tier = 10
        static Frametype = "Records"
        static Delaymilliseconds = 200
        static Descriptiontid = "TID_RECORD_CARD_NAME_LEVEL_10"
        static RowID = 32
    }
    static Recordsframelevel11 = class {
        static Name = "records_frame_level_11"
        static Iconswf = "sc/ui_achievements.sc"
        static Iconexportname = "battle_card_frame_records_tier11_bg"
        static Banner = "battle_card_frame_records_tier11_ui"
        static Iconontop = "battle_card_frame_records_tier11_levels"
        static Tier = 11
        static Frametype = "Records"
        static Delaymilliseconds = 200
        static Descriptiontid = "TID_RECORD_CARD_NAME_LEVEL_11"
        static RowID = 33
    }
    static Recordsframelevel12 = class {
        static Name = "records_frame_level_12"
        static Iconswf = "sc/ui_achievements.sc"
        static Iconexportname = "battle_card_frame_records_tier12_bg"
        static Banner = "battle_card_frame_records_tier12_ui"
        static Iconontop = "battle_card_frame_records_tier12_levels"
        static Tier = 12
        static Frametype = "Records"
        static Delaymilliseconds = 200
        static Descriptiontid = "TID_RECORD_CARD_NAME_LEVEL_12"
        static RowID = 34
    }
}

export default Playerframes;