class Rankedranks {
    static BronzeI = class {
        static Name = "Bronze I"
        static Rank = 1
        static Minelo = 0
        static Maxelo = 249
        static Requiredbrawlerlevel = 9
        static Requiredbrawlercount = 3
        static Tid = "TID_RANKED_BRONZE_I"
        static Hexcolor = "0xFF9900"
        static Framelabel = "bronze"
        static Rankicontextfield = "rank_bronze_text"
        static Rankicontid = "TID_PLAYER_RANK_TIER_0"
        static Competitivegroup = 1
        static Competitiveicon = "rank_icon_animated_01"
        static Competitivebackground = "bgr_competitive_bronze"
        static Sound = "Bronze_Rank_1_JIngle"
        static RowID = 1
    }
    static BronzeIi = class {
        static Name = "Bronze II"
        static Rank = 2
        static Minelo = 250
        static Maxelo = 499
        static Requiredbrawlerlevel = 9
        static Requiredbrawlercount = 3
        static Pointsrewardamount = 200
        static Tid = "TID_RANKED_BRONZE_II"
        static Hexcolor = "0xFF9900"
        static Framelabel = "bronze"
        static Rankicontextfield = "rank_bronze_text"
        static Rankicontid = "TID_PLAYER_RANK_TIER_1"
        static Competitivegroup = 1
        static Competitiveicon = "rank_icon_animated_01"
        static Competitivebackground = "bgr_competitive_bronze"
        static Hasframereward = true
        static Sound = "Bronze_Rank_2_JIngle"
        static RowID = 2
    }
    static BronzeIii = class {
        static Name = "Bronze III"
        static Rank = 3
        static Minelo = 500
        static Maxelo = 749
        static Requiredbrawlerlevel = 9
        static Requiredbrawlercount = 3
        static Pointsrewardamount = 200
        static Tid = "TID_RANKED_BRONZE_III"
        static Hexcolor = "0xFF9900"
        static Framelabel = "bronze"
        static Rankicontextfield = "rank_bronze_text"
        static Rankicontid = "TID_PLAYER_RANK_TIER_2"
        static Competitivegroup = 1
        static Competitiveicon = "rank_icon_animated_01"
        static Competitivebackground = "bgr_competitive_bronze"
        static Sound = "Bronze_Rank_3_JIngle"
        static RowID = 3
    }
    static SilverI = class {
        static Name = "Silver I"
        static Rank = 4
        static Minelo = 750
        static Maxelo = 999
        static Requiredbrawlerlevel = 9
        static Requiredbrawlercount = 3
        static Pointsrewardamount = 200
        static Tid = "TID_RANKED_SILVER_I"
        static Hexcolor = "0xC9C6F1"
        static Framelabel = "silver"
        static Rankicontextfield = "rank_silver_text"
        static Rankicontid = "TID_PLAYER_RANK_TIER_0"
        static Competitivegroup = 2
        static Competitiveicon = "rank_icon_animated_02"
        static Competitivebackground = "bgr_competitive_silver"
        static Hasframereward = true
        static Sound = "Silver_Rank_1_JIngle"
        static RowID = 4
    }
    static SilverIi = class {
        static Name = "Silver II"
        static Rank = 5
        static Minelo = 1000
        static Maxelo = 1249
        static Requiredbrawlerlevel = 9
        static Requiredbrawlercount = 3
        static Pointsrewardamount = 200
        static Tid = "TID_RANKED_SILVER_II"
        static Hexcolor = "0xC9C6F1"
        static Framelabel = "silver"
        static Rankicontextfield = "rank_silver_text"
        static Rankicontid = "TID_PLAYER_RANK_TIER_1"
        static Competitivegroup = 2
        static Competitiveicon = "rank_icon_animated_02"
        static Competitivebackground = "bgr_competitive_silver"
        static Sound = "Silver_Rank_2_JIngle"
        static RowID = 5
    }
    static SilverIii = class {
        static Name = "Silver III"
        static Rank = 6
        static Minelo = 1250
        static Maxelo = 1499
        static Requiredbrawlerlevel = 9
        static Requiredbrawlercount = 3
        static Pointsrewardamount = 200
        static Tid = "TID_RANKED_SILVER_III"
        static Hexcolor = "0xC9C6F1"
        static Framelabel = "silver"
        static Rankicontextfield = "rank_silver_text"
        static Rankicontid = "TID_PLAYER_RANK_TIER_2"
        static Competitivegroup = 2
        static Competitiveicon = "rank_icon_animated_02"
        static Competitivebackground = "bgr_competitive_silver"
        static Sound = "Silver_Rank_3_JIngle"
        static RowID = 6
    }
    static GoldI = class {
        static Name = "Gold I"
        static Rank = 7
        static Minelo = 1500
        static Maxelo = 1999
        static Requiredbrawlerlevel = 9
        static Requiredbrawlercount = 3
        static Pointsrewardamount = 200
        static Tid = "TID_RANKED_GOLD_I"
        static Hexcolor = "0xFFEF49"
        static Framelabel = "gold"
        static Rankicontextfield = "rank_gold_text"
        static Rankicontid = "TID_PLAYER_RANK_TIER_0"
        static Competitivegroup = 3
        static Competitiveicon = "rank_icon_animated_03"
        static Competitivebackground = "bgr_competitive_gold"
        static Hasframereward = true
        static Sound = "Gold_Rank_1_Jingle"
        static RowID = 7
    }
    static GoldIi = class {
        static Name = "Gold II"
        static Rank = 8
        static Minelo = 2000
        static Maxelo = 2499
        static Requiredbrawlerlevel = 9
        static Requiredbrawlercount = 3
        static Pointsrewardamount = 200
        static Tid = "TID_RANKED_GOLD_II"
        static Hexcolor = "0xFFEF49"
        static Framelabel = "gold"
        static Rankicontextfield = "rank_gold_text"
        static Rankicontid = "TID_PLAYER_RANK_TIER_1"
        static Competitivegroup = 3
        static Competitiveicon = "rank_icon_animated_03"
        static Competitivebackground = "bgr_competitive_gold"
        static Sound = "Gold_Rank_2_Jingle"
        static RowID = 8
    }
    static GoldIii = class {
        static Name = "Gold III"
        static Rank = 9
        static Minelo = 2500
        static Maxelo = 2999
        static Requiredbrawlerlevel = 9
        static Requiredbrawlercount = 3
        static Pointsrewardamount = 200
        static Tid = "TID_RANKED_GOLD_III"
        static Hexcolor = "0xFFEF49"
        static Framelabel = "gold"
        static Rankicontextfield = "rank_gold_text"
        static Rankicontid = "TID_PLAYER_RANK_TIER_2"
        static Competitivegroup = 3
        static Competitiveicon = "rank_icon_animated_03"
        static Competitivebackground = "bgr_competitive_gold"
        static Sound = "Gold_Rank_3_Jingle"
        static RowID = 9
    }
    static DiamondI = class {
        static Name = "Diamond I"
        static Rank = 10
        static Minelo = 3000
        static Maxelo = 3499
        static Requiredbrawlerlevel = 9
        static Requiredbrawlercount = 9
        static Pointsrewardamount = 200
        static Tid = "TID_RANKED_DIAMOND_I"
        static Hexcolor = "0x33FFFF"
        static Framelabel = "diamond"
        static Rankicontextfield = "rank_diamond_text"
        static Rankicontid = "TID_PLAYER_RANK_TIER_0"
        static Competitivegroup = 4
        static Competitiveicon = "rank_icon_animated_04"
        static Competitivebackground = "bgr_competitive_diamond"
        static Hasframereward = true
        static Sound = "Diamond_Rank_1_Jingle"
        static Formattooltipcontext = 3
        static Framelabeltooltip = "diamond"
        static Tidtooltip = "TID_RANKED_DIAMOND_FORMAT_TOOLTIP"
        static RowID = 10
    }
    static DiamondIi = class {
        static Name = "Diamond II"
        static Rank = 11
        static Minelo = 3500
        static Maxelo = 3999
        static Requiredbrawlerlevel = 9
        static Requiredbrawlercount = 9
        static Pointsrewardamount = 200
        static Tid = "TID_RANKED_DIAMOND_II"
        static Hexcolor = "0x33FFFF"
        static Framelabel = "diamond"
        static Rankicontextfield = "rank_diamond_text"
        static Rankicontid = "TID_PLAYER_RANK_TIER_1"
        static Competitivegroup = 4
        static Competitiveicon = "rank_icon_animated_04"
        static Competitivebackground = "bgr_competitive_diamond"
        static Sound = "Diamond_Rank_2_Jingle"
        static RowID = 11
    }
    static DiamondIii = class {
        static Name = "Diamond III"
        static Rank = 12
        static Minelo = 4000
        static Maxelo = 4499
        static Requiredbrawlerlevel = 9
        static Requiredbrawlercount = 9
        static Pointsrewardamount = 200
        static Tid = "TID_RANKED_DIAMOND_III"
        static Hexcolor = "0x33FFFF"
        static Framelabel = "diamond"
        static Rankicontextfield = "rank_diamond_text"
        static Rankicontid = "TID_PLAYER_RANK_TIER_2"
        static Competitivegroup = 4
        static Competitiveicon = "rank_icon_animated_04"
        static Competitivebackground = "bgr_competitive_diamond"
        static Sound = "Diamond_Rank_3_Jingle"
        static RowID = 12
    }
    static MythicI = class {
        static Name = "Mythic I"
        static Rank = 13
        static Minelo = 4500
        static Maxelo = 4999
        static Requiredbrawlerlevel = 11
        static Requiredbrawlercount = 12
        static Pointsrewardamount = 200
        static Tid = "TID_RANKED_MYTHIC_I"
        static Hexcolor = "0xFF00FF"
        static Framelabel = "mythic"
        static Rankicontextfield = "rank_mythic_text"
        static Rankicontid = "TID_PLAYER_RANK_TIER_0"
        static Competitivegroup = 5
        static Competitiveicon = "rank_icon_animated_05"
        static Competitivebackground = "bgr_competitive_mythic"
        static Hasframereward = true
        static Sound = "Mythic_Rank_1_Jingle"
        static Formattooltipcontext = 4
        static Framelabeltooltip = "mythic"
        static Tidtooltip = "TID_RANKED_MYTHIC_FORMAT_TOOLTIP"
        static RowID = 13
    }
    static MythicIi = class {
        static Name = "Mythic II"
        static Rank = 14
        static Minelo = 5000
        static Maxelo = 5499
        static Requiredbrawlerlevel = 11
        static Requiredbrawlercount = 12
        static Pointsrewardamount = 200
        static Tid = "TID_RANKED_MYTHIC_II"
        static Hexcolor = "0xFF00FF"
        static Framelabel = "mythic"
        static Rankicontextfield = "rank_mythic_text"
        static Rankicontid = "TID_PLAYER_RANK_TIER_1"
        static Competitivegroup = 5
        static Competitiveicon = "rank_icon_animated_05"
        static Competitivebackground = "bgr_competitive_mythic"
        static Sound = "Mythic_Rank_2_Jingle"
        static RowID = 14
    }
    static MythicIii = class {
        static Name = "Mythic III"
        static Rank = 15
        static Minelo = 5500
        static Maxelo = 5999
        static Requiredbrawlerlevel = 11
        static Requiredbrawlercount = 12
        static Pointsrewardamount = 200
        static Tid = "TID_RANKED_MYTHIC_III"
        static Hexcolor = "0xFF00FF"
        static Framelabel = "mythic"
        static Rankicontextfield = "rank_mythic_text"
        static Rankicontid = "TID_PLAYER_RANK_TIER_2"
        static Competitivegroup = 5
        static Competitiveicon = "rank_icon_animated_05"
        static Competitivebackground = "bgr_competitive_mythic"
        static Sound = "Mythic_Rank_3_Jingle"
        static RowID = 15
    }
    static LegendaryI = class {
        static Name = "Legendary I"
        static Rank = 16
        static Minelo = 6000
        static Maxelo = 6749
        static Requiredbrawlerlevel = 11
        static Requiredbrawlercount = 12
        static Pointsrewardamount = 200
        static Tid = "TID_RANKED_LEGENDARY_I"
        static Hexcolor = "0xF75363"
        static Framelabel = "legendary"
        static Rankicontextfield = "rank_legendary_text"
        static Rankicontid = "TID_PLAYER_RANK_TIER_0"
        static Competitivegroup = 6
        static Competitiveicon = "rank_icon_animated_06"
        static Competitivebackground = "bgr_competitive_legendary"
        static Hasframereward = true
        static Sound = "Legendary_Rank_1_Jingle"
        static RowID = 16
    }
    static LegendaryIi = class {
        static Name = "Legendary II"
        static Rank = 17
        static Minelo = 6750
        static Maxelo = 7499
        static Requiredbrawlerlevel = 11
        static Requiredbrawlercount = 12
        static Pointsrewardamount = 200
        static Tid = "TID_RANKED_LEGENDARY_II"
        static Hexcolor = "0xF75363"
        static Framelabel = "legendary"
        static Rankicontextfield = "rank_legendary_text"
        static Rankicontid = "TID_PLAYER_RANK_TIER_1"
        static Competitivegroup = 6
        static Competitiveicon = "rank_icon_animated_06"
        static Competitivebackground = "bgr_competitive_legendary"
        static Sound = "Legendary_Rank_2_Jingle"
        static RowID = 17
    }
    static LegendaryIii = class {
        static Name = "Legendary III"
        static Rank = 18
        static Minelo = 7500
        static Maxelo = 8249
        static Requiredbrawlerlevel = 11
        static Requiredbrawlercount = 12
        static Pointsrewardamount = 200
        static Tid = "TID_RANKED_LEGENDARY_III"
        static Hexcolor = "0xF75363"
        static Framelabel = "legendary"
        static Rankicontextfield = "rank_legendary_text"
        static Rankicontid = "TID_PLAYER_RANK_TIER_2"
        static Competitivegroup = 6
        static Competitiveicon = "rank_icon_animated_06"
        static Competitivebackground = "bgr_competitive_legendary"
        static Sound = "Legendary_Rank_3_Jingle"
        static RowID = 18
    }
    static MastersI = class {
        static Name = "Masters I"
        static Rank = 19
        static Minelo = 8250
        static Maxelo = 9249
        static Requiredbrawlerlevel = 11
        static Requiredbrawlercount = 12
        static Pointsrewardamount = 200
        static Tid = "TID_RANKED_MASTERS_I"
        static Hexcolor = "0xFFFFFF"
        static Framelabel = "masters"
        static Rankicontextfield = "rank_masters_text"
        static Rankicontid = "TID_PLAYER_RANK_TIER_0"
        static Competitivegroup = 7
        static Competitiveicon = "rank_icon_animated_07"
        static Competitivebackground = "bgr_competitive_masters"
        static Hasframereward = true
        static Sound = "Masters_Rank_1_Jingle"
        static RowID = 19
    }
    static MastersIi = class {
        static Name = "Masters II"
        static Rank = 20
        static Minelo = 9250
        static Maxelo = 10249
        static Requiredbrawlerlevel = 11
        static Requiredbrawlercount = 12
        static Pointsrewardamount = 200
        static Tid = "TID_RANKED_MASTERS_II"
        static Hexcolor = "0xFFFFFF"
        static Framelabel = "masters"
        static Rankicontextfield = "rank_masters_text"
        static Rankicontid = "TID_PLAYER_RANK_TIER_1"
        static Competitivegroup = 7
        static Competitiveicon = "rank_icon_animated_07"
        static Competitivebackground = "bgr_competitive_masters"
        static Sound = "Masters_Rank_2_Jingle"
        static RowID = 20
    }
    static MastersIii = class {
        static Name = "Masters III"
        static Rank = 21
        static Minelo = 10250
        static Maxelo = 11249
        static Requiredbrawlerlevel = 11
        static Requiredbrawlercount = 12
        static Pointsrewardamount = 200
        static Tid = "TID_RANKED_MASTERS_III"
        static Hexcolor = "0xFFFFFF"
        static Framelabel = "masters"
        static Rankicontextfield = "rank_masters_text"
        static Rankicontid = "TID_PLAYER_RANK_TIER_2"
        static Competitivegroup = 7
        static Competitiveicon = "rank_icon_animated_07"
        static Competitivebackground = "bgr_competitive_masters"
        static Sound = "Masters_Rank_3_Jingle"
        static RowID = 21
    }
    static Pro = class {
        static Name = "Pro"
        static Rank = 22
        static Minelo = 11250
        static Requiredbrawlerlevel = 11
        static Requiredbrawlercount = 12
        static Pointsrewardamount = 200
        static Tid = "TID_RANKED_PRO"
        static Hexcolor = "0xFFFFFF"
        static Framelabel = "pro"
        static Competitivegroup = 8
        static Competitiveicon = "rank_icon_animated_08"
        static Competitivebackground = "bgr_competitive_pro"
        static Hasframereward = true
        static Sound = "Pro_Rank_1_Jingle"
        static Showglobalrank = true
        static RowID = 22
    }
}

export default Rankedranks;