class Tiles {
    static Open = class {
        static Name = "Open"
        static Tilecode = "."
        static Shadowscalex = 100
        static Shadowscaley = 60
        static Shadowx = -10
        static Shadowy = 60
        static Shadowskew = 25
        static Mapeditorvisible = true
        static Mapeditorvisualmode = 1
        static RowID = 1
    }
    static Wall1 = class {
        static Name = "Wall1"
        static Tilecode = "M"
        static Blocksmovement = true
        static Blocksprojectiles = true
        static Isdestructible = true
        static Isdestructibleovertime = true
        static Baseexportname = "wall1"
        static Baseexplosioneffect = "wall1_explo"
        static Basehiteffect = "wall1_hit"
        static Hashitanim = true
        static Shadowscalex = 100
        static Shadowscaley = 60
        static Shadowx = -10
        static Shadowy = 60
        static Shadowskew = 25
        static Mapeditorvisible = true
        static Mapeditorvisualmode = 1
        static RowID = 2
    }
    static Wall2 = class {
        static Name = "Wall2"
        static Tilecode = "X"
        static Blocksmovement = true
        static Blocksprojectiles = true
        static Isdestructible = true
        static Isdestructibleovertime = true
        static Baseexportname = "wall2"
        static Baseexplosioneffect = "wall2_explo"
        static Basehiteffect = "wall2_hit"
        static Sortoffset = -1
        static Hashitanim = true
        static Shadowscalex = 100
        static Shadowscaley = 60
        static Shadowx = -10
        static Shadowy = 60
        static Shadowskew = 25
        static Mapeditorvisible = true
        static Mapeditorvisualmode = 1
        static RowID = 3
    }
    static Crate = class {
        static Name = "Crate"
        static Tilecode = "Y"
        static Blocksmovement = true
        static Blocksprojectiles = true
        static Isdestructible = true
        static Isdestructibleovertime = true
        static Baseexportname = "crate"
        static Baseexplosioneffect = "crate_explo"
        static Basehiteffect = "crate_hit"
        static Hashitanim = true
        static Shadowscalex = 100
        static Shadowscaley = 60
        static Shadowx = -10
        static Shadowy = 60
        static Shadowskew = 25
        static Mapeditorvisible = true
        static Mapeditorvisualmode = 1
        static RowID = 4
    }
    static Barrel = class {
        static Name = "Barrel"
        static Tilecode = "C"
        static Blocksmovement = true
        static Blocksprojectiles = true
        static Isdestructible = true
        static Isdestructibleovertime = true
        static Baseexportname = "barrel"
        static Baseexplosioneffect = "barrel_explo"
        static Basehiteffect = "barrel_hit"
        static Hashitanim = true
        static Shadowscalex = 100
        static Shadowscaley = 60
        static Shadowx = -10
        static Shadowy = 60
        static Shadowskew = 25
        static Mapeditorvisible = true
        static Mapeditorvisualmode = 1
        static RowID = 5
    }
    static Decodestructible = class {
        static Name = "DecoDestructible"
        static Tilecode = "D"
        static Isdestructiblenormalweapon = true
        static Isdestructibleovertime = true
        static Baseexportname = "clutter"
        static Hashitanim = true
        static Shadowscalex = 100
        static Shadowscaley = 60
        static Shadowx = -10
        static Shadowy = 60
        static Shadowskew = 25
        static Mapeditorvisible = true
        static Mapeditorvisualmode = 1
        static RowID = 6
    }
    static Indestructible = class {
        static Name = "Indestructible"
        static Tilecode = "I"
        static Blocksmovement = true
        static Blocksprojectiles = true
        static Isdestructibleovertime = true
        static Baseexportname = "indestructible"
        static Baseexplosioneffect = "indestructible_explo"
        static Basehiteffect = "indestructable_hit"
        static Sortoffset = 1
        static Hashitanim = true
        static Shadowscalex = 100
        static Shadowscaley = 60
        static Shadowx = -10
        static Shadowy = 60
        static Shadowskew = 25
        static Mapeditorvisualmode = 1
        static RowID = 7
    }
    static Forest = class {
        static Name = "Forest"
        static Tilecode = "F"
        static Isdestructible = true
        static Isdestructibleovertime = true
        static Isforest = true
        static Baseexportname = "grass"
        static Baseexplosioneffect = "grass_explo_yellow"
        static Basehiteffect = "grass_hit_yellow"
        static Sortoffset = -1
        static Hashitanim = true
        static Haswindanim = true
        static Shadowscalex = 100
        static Shadowscaley = 60
        static Shadowx = -10
        static Shadowy = 60
        static Shadowskew = 25
        static Mapeditorvisible = true
        static Mapeditorvisualmode = 1
        static RowID = 8
    }
    static Respawningforest = class {
        static Name = "RespawningForest"
        static Tilecode = "R"
        static Isdestructible = true
        static Isdestructibleovertime = true
        static Isforest = true
        static Baseexportname = "grass"
        static Baseexplosioneffect = "grass_explo"
        static Basehiteffect = "grass_hit"
        static Sortoffset = -1
        static Hashitanim = true
        static Haswindanim = true
        static Shadowscalex = 100
        static Shadowscaley = 60
        static Shadowx = -10
        static Shadowy = 60
        static Shadowskew = 25
        static Mapeditorvisualmode = 1
        static RowID = 9
    }
    static Water = class {
        static Name = "Water"
        static Tilecode = "W"
        static Blocksmovement = true
        static Baseexportname = "water_tile"
        static Shadowscalex = 100
        static Shadowscaley = 60
        static Shadowx = -10
        static Shadowy = 60
        static Shadowskew = 25
        static Mapeditorvisible = true
        static Mapeditorvisualmode = 4
        static Mapeditorconnected = true
        static RowID = 10
    }
    static Themed = class {
        static Name = "Themed"
        static Tilecode = "T"
        static Blocksmovement = true
        static Blocksprojectiles = true
        static Isdestructible = true
        static Isdestructibleovertime = true
        static Baseexportname = "themed"
        static Baseexplosioneffect = "themed_explo"
        static Basehiteffect = "themed_hit"
        static Sortoffset = -1
        static Hashitanim = true
        static Shadowscalex = 100
        static Shadowscaley = 60
        static Shadowx = -10
        static Shadowy = 60
        static Shadowskew = 25
        static Mapeditorvisible = true
        static Mapeditorvisualmode = 1
        static RowID = 11
    }
    static Invisiblewater = class {
        static Name = "InvisibleWater"
        static Tilecode = "V"
        static Blocksmovement = true
        static Shadowscalex = 100
        static Shadowscaley = 60
        static Shadowx = -10
        static Shadowy = 60
        static Shadowskew = 25
        static Mapeditorvisualmode = 1
        static RowID = 12
    }
    static Fragile = class {
        static Name = "Fragile"
        static Tilecode = "B"
        static Blocksmovement = true
        static Blocksprojectiles = true
        static Isdestructible = true
        static Isdestructiblenormalweapon = true
        static Isdestructibleovertime = true
        static Baseexportname = "fragile"
        static Baseexplosioneffect = "fragile_explo"
        static Hashitanim = true
        static Shadowscalex = 100
        static Shadowscaley = 60
        static Shadowx = -10
        static Shadowy = 60
        static Shadowskew = 25
        static Mapeditorvisible = true
        static Mapeditorvisualmode = 1
        static RowID = 13
    }
    static Fence = class {
        static Name = "Fence"
        static Tilecode = "N"
        static Blocksmovement = true
        static Blocksprojectiles = true
        static Isdestructible = true
        static Isdestructibleovertime = true
        static Baseexportname = "fence_tile"
        static Baseexplosioneffect = "fence_explo"
        static Basehiteffect = "fence_hit"
        static Shadowscalex = 100
        static Shadowscaley = 60
        static Shadowx = -10
        static Shadowy = 30
        static Shadowskew = 25
        static Mapeditorvisible = true
        static Mapeditorvisualmode = 1
        static Mapeditorconnected = true
        static RowID = 14
    }
    static Invisibleindestructible = class {
        static Name = "InvisibleIndestructible"
        static Tilecode = "J"
        static Blocksmovement = true
        static Blocksprojectiles = true
        static Shadowscalex = 100
        static Shadowscaley = 60
        static Shadowx = -10
        static Shadowy = 60
        static Shadowskew = 25
        static Mapeditorvisualmode = 1
        static RowID = 15
    }
    static Wallywall = class {
        static Name = "WallyWall"
        static Tilecode = "-"
        static Dynamiccode = 1
        static Blocksmovement = true
        static Blocksprojectiles = true
        static Isdestructible = true
        static Isdestructibleovertime = true
        static Baseexportname = "custom"
        static Baseexplosioneffect = "sprout_def_wall_explo"
        static Basehiteffect = "sprout_def_wall_hit"
        static Hashitanim = true
        static Shadowscalex = 100
        static Shadowscaley = 60
        static Shadowx = -10
        static Shadowy = 60
        static Shadowskew = 25
        static Lifetime = 200
        static Customscw = "sc3d/wally_wall.scw"
        static Custommesh = "wally_wall"
        static Customanglestep = 90
        static Mapeditorvisualmode = 1
        static RowID = 16
    }
    static Wallyfillerwall = class {
        static Name = "WallyFillerWall"
        static Tilecode = "-"
        static Dynamiccode = 2
        static Blocksmovement = true
        static Blocksprojectiles = true
        static Isdestructible = true
        static Isdestructibleovertime = true
        static Baseexportname = "custom"
        static Baseexplosioneffect = "sprout_def_wall_explo"
        static Basehiteffect = "sprout_def_wall_hit"
        static Hashitanim = true
        static Shadowscalex = 100
        static Shadowscaley = 60
        static Shadowx = -10
        static Shadowy = 60
        static Shadowskew = 25
        static Lifetime = 200
        static Customscw = "sc3d/wally_wall.scw"
        static Custommesh = "wally_wall_filler"
        static Customanglestep = 90
        static Mapeditorvisualmode = 1
        static RowID = 17
    }
    static Extrabush = class {
        static Name = "ExtraBush"
        static Tilecode = "-"
        static Dynamiccode = 3
        static Isdestructible = true
        static Isdestructibleovertime = true
        static Isforest = true
        static Baseexportname = "grass"
        static Baseexplosioneffect = "grass_explo_yellow"
        static Basehiteffect = "grass_hit_yellow"
        static Sortoffset = -1
        static Hashitanim = true
        static Haswindanim = true
        static Shadowscalex = 100
        static Shadowscaley = 60
        static Shadowx = -10
        static Shadowy = 60
        static Shadowskew = 25
        static Mapeditorvisualmode = 1
        static Spawneffect = "grass_explo"
        static RowID = 18
    }
    static Ropefence = class {
        static Name = "RopeFence"
        static Tilecode = "a"
        static Blocksmovement = true
        static Isdestructible = true
        static Isdestructibleovertime = true
        static Baseexportname = "rope_fence_pole"
        static Baseexplosioneffect = "rope_explo"
        static Shadowscalex = 100
        static Shadowscaley = 60
        static Shadowx = -10
        static Shadowy = 60
        static Shadowskew = 25
        static Mapeditorvisible = true
        static Mapeditorvisualmode = 2
        static Mapeditorconnected = true
        static RowID = 19
    }
    static Payloadtrack = class {
        static Name = "PayloadTrack"
        static Tilecode = "b"
        static Restoreafterdynamicoverlap = true
        static Baseexportname = "payload_track"
        static Shadowscalex = 100
        static Shadowscaley = 60
        static Shadowx = -10
        static Shadowy = 60
        static Shadowskew = 25
        static Mapeditorvisualmode = 1
        static RowID = 20
    }
    static Wallymoonwall = class {
        static Name = "WallyMoonWall"
        static Tilecode = "-"
        static Dynamiccode = 4
        static Blocksmovement = true
        static Blocksprojectiles = true
        static Isdestructible = true
        static Isdestructibleovertime = true
        static Baseexportname = "custom"
        static Baseexplosioneffect = "sprout_002_wall_explo_satellite"
        static Basehiteffect = "sprout_002_wall_hit"
        static Hashitanim = true
        static Shadowscalex = 100
        static Shadowscaley = 60
        static Shadowx = -10
        static Shadowy = 60
        static Shadowskew = 25
        static Lifetime = 200
        static Customscw = "sc3d/wally_wall_moon.scw"
        static Custommesh = "wally_wall"
        static Customanglestep = 90
        static Mapeditorvisualmode = 1
        static RowID = 21
    }
    static Wallymoonfillerwall = class {
        static Name = "WallyMoonFillerWall"
        static Tilecode = "-"
        static Dynamiccode = 5
        static Blocksmovement = true
        static Blocksprojectiles = true
        static Isdestructible = true
        static Isdestructibleovertime = true
        static Baseexportname = "custom"
        static Baseexplosioneffect = "sprout_002_wall_explo"
        static Basehiteffect = "sprout_002_wall_hit"
        static Hashitanim = true
        static Shadowscalex = 100
        static Shadowscaley = 60
        static Shadowx = -10
        static Shadowy = 60
        static Shadowskew = 25
        static Lifetime = 200
        static Customscw = "sc3d/wally_wall_moon.scw"
        static Custommesh = "wally_wall_filler"
        static Customanglestep = 90
        static Mapeditorvisualmode = 1
        static RowID = 22
    }
    static Spawnpoint1 = class {
        static Name = "SpawnPoint1"
        static Tilecode = "."
        static Baseexportname = "custom"
        static Customscw = "sc3d/spawn_point_blue.scw"
        static Mapeditorvisible = true
        static Mapeditorvisualmode = 1
        static RowID = 23
    }
    static Spawnpoint2 = class {
        static Name = "SpawnPoint2"
        static Tilecode = "."
        static Baseexportname = "custom"
        static Customscw = "sc3d/spawn_point_red.scw"
        static Mapeditorvisible = true
        static Mapeditorvisualmode = 1
        static RowID = 24
    }
    static Respawnpoint1 = class {
        static Name = "ReSpawnPoint1"
        static Tilecode = "."
        static Baseexportname = "custom"
        static Customscw = "sc3d/respawn_point_blue.scw"
        static Mapeditorvisible = true
        static Mapeditorvisualmode = 1
        static RowID = 25
    }
    static Respawnpoint2 = class {
        static Name = "ReSpawnPoint2"
        static Tilecode = "."
        static Baseexportname = "custom"
        static Customscw = "sc3d/respawn_point_red.scw"
        static Mapeditorvisible = true
        static Mapeditorvisualmode = 1
        static RowID = 26
    }
    static Powerupcrate = class {
        static Name = "PowerupCrate"
        static Tilecode = "."
        static Baseexportname = "custom"
        static Customscw = "sc3d/crate_powerup.scw"
        static Mapeditorvisible = true
        static Mapeditorvisualmode = 1
        static RowID = 27
    }
    static Base = class {
        static Name = "Base"
        static Tilecode = "."
        static Baseexportname = "custom"
        static Customscw = "sc3d/heist_safe.scw"
        static Mapeditorvisible = true
        static Mapeditorvisualmode = 1
        static RowID = 28
    }
    static Springboard = class {
        static Name = "SpringBoard"
        static Tilecode = "."
        static Baseexportname = "custom"
        static Customscw = "sc3d/spring_board.scw"
        static Mapeditorvisible = true
        static Mapeditorvisualmode = 1
        static RowID = 29
    }
    static Teleport1 = class {
        static Name = "Teleport1"
        static Tilecode = "."
        static Baseexportname = "custom"
        static Customscw = "sc3d/teleport_tile_geo.glb"
        static Mapeditorvisible = true
        static Mapeditorvisualmode = 1
        static RowID = 30
    }
    static Teleport2 = class {
        static Name = "Teleport2"
        static Tilecode = "."
        static Baseexportname = "custom"
        static Customscw = "sc3d/teleport_tile_2_geo.glb"
        static Mapeditorvisible = true
        static Mapeditorvisualmode = 1
        static RowID = 31
    }
    static Teleport3 = class {
        static Name = "Teleport3"
        static Tilecode = "."
        static Baseexportname = "custom"
        static Customscw = "sc3d/teleport_tile_3_geo.glb"
        static Mapeditorvisible = true
        static Mapeditorvisualmode = 1
        static RowID = 32
    }
    static Teleport4 = class {
        static Name = "Teleport4"
        static Tilecode = "."
        static Baseexportname = "custom"
        static Customscw = "sc3d/teleport_tile_4_geo.glb"
        static Mapeditorvisible = true
        static Mapeditorvisualmode = 1
        static RowID = 33
    }
    static Siegebolt = class {
        static Name = "SiegeBolt"
        static Tilecode = "."
        static Baseexportname = "custom"
        static Customscw = "sc3d/editor_icon_siege_bolt.scw"
        static Mapeditorvisible = true
        static Mapeditorvisualmode = 1
        static RowID = 34
    }
    static Damage = class {
        static Name = "Damage"
        static Tilecode = "x"
        static Damage = 100
        static Restoreafterdynamicoverlap = true
        static Baseexportname = "custom"
        static Customscw = "sc3d/poison_tile_geo.glb"
        static Mapeditorvisible = true
        static Mapeditorvisualmode = 1
        static RowID = 35
    }
    static Healing = class {
        static Name = "Healing"
        static Tilecode = "."
        static Baseexportname = "custom"
        static Customscw = "sc3d/healing_tile_geo.glb"
        static Mapeditorvisible = true
        static Mapeditorvisualmode = 1
        static RowID = 36
    }
    static Slow = class {
        static Name = "Slow"
        static Tilecode = "z"
        static Speedchange = -300
        static Restoreafterdynamicoverlap = true
        static Baseexportname = "custom"
        static Customscw = "sc3d/slowdown_tile_geo.glb"
        static Mapeditorvisible = true
        static Mapeditorvisualmode = 1
        static RowID = 37
    }
    static Fast = class {
        static Name = "Fast"
        static Tilecode = "w"
        static Speedchange = 300
        static Restoreafterdynamicoverlap = true
        static Baseexportname = "custom"
        static Customscw = "sc3d/speedup_tile_geo.glb"
        static Mapeditorvisible = true
        static Mapeditorvisualmode = 1
        static RowID = 38
    }
    static Intervaldamage = class {
        static Name = "IntervalDamage"
        static Tilecode = "v"
        static Restoreafterdynamicoverlap = true
        static Baseexportname = "custom"
        static Customscw = "sc3d/damage_tile_geo.glb"
        static Mapeditorvisible = true
        static Mapeditorvisualmode = 1
        static RowID = 39
    }
    static Wallyprinceredwall = class {
        static Name = "WallyPrinceRedWall"
        static Tilecode = "-"
        static Dynamiccode = 6
        static Blocksmovement = true
        static Blocksprojectiles = true
        static Isdestructible = true
        static Isdestructibleovertime = true
        static Baseexportname = "custom"
        static Baseexplosioneffect = "sprout_003_wall_explo_chroma"
        static Basehiteffect = "sprout_003_wall_hit_chroma"
        static Hashitanim = true
        static Shadowscalex = 100
        static Shadowscaley = 60
        static Shadowx = -10
        static Shadowy = 60
        static Shadowskew = 25
        static Lifetime = 200
        static Customscw = "sc3d/wally_wall_prince.scw"
        static Custommesh = "wally_wall"
        static Customanglestep = 0
        static Mapeditorvisualmode = 1
        static RowID = 40
    }
    static Wallyprinceredfillerwall = class {
        static Name = "WallyPrinceRedFillerWall"
        static Tilecode = "-"
        static Dynamiccode = 7
        static Blocksmovement = true
        static Blocksprojectiles = true
        static Isdestructible = true
        static Isdestructibleovertime = true
        static Baseexportname = "custom"
        static Baseexplosioneffect = "sprout_003_wall_explo_chroma"
        static Basehiteffect = "sprout_003_wall_hit_chroma"
        static Hashitanim = true
        static Shadowscalex = 100
        static Shadowscaley = 60
        static Shadowx = -10
        static Shadowy = 60
        static Shadowskew = 25
        static Lifetime = 200
        static Customscw = "sc3d/wally_wall_prince.scw"
        static Custommesh = "wally_wall_filler"
        static Customanglestep = 90
        static Mapeditorvisualmode = 1
        static RowID = 41
    }
    static Wallyprincegreenwall = class {
        static Name = "WallyPrinceGreenWall"
        static Tilecode = "-"
        static Dynamiccode = 8
        static Blocksmovement = true
        static Blocksprojectiles = true
        static Isdestructible = true
        static Isdestructibleovertime = true
        static Baseexportname = "custom"
        static Baseexplosioneffect = "sprout_003_wall_explo"
        static Basehiteffect = "sprout_003_wall_hit"
        static Hashitanim = true
        static Shadowscalex = 100
        static Shadowscaley = 60
        static Shadowx = -10
        static Shadowy = 60
        static Shadowskew = 25
        static Lifetime = 200
        static Customscw = "sc3d/wally_wall_prince_2.scw"
        static Custommesh = "wally_wall"
        static Customanglestep = 0
        static Mapeditorvisualmode = 1
        static RowID = 42
    }
    static Wallyprincegreenfillerwall = class {
        static Name = "WallyPrinceGreenFillerWall"
        static Tilecode = "-"
        static Dynamiccode = 9
        static Blocksmovement = true
        static Blocksprojectiles = true
        static Isdestructible = true
        static Isdestructibleovertime = true
        static Baseexportname = "custom"
        static Baseexplosioneffect = "sprout_003_wall_explo"
        static Basehiteffect = "sprout_003_wall_hit"
        static Hashitanim = true
        static Shadowscalex = 100
        static Shadowscaley = 60
        static Shadowx = -10
        static Shadowy = 60
        static Shadowskew = 25
        static Lifetime = 200
        static Customscw = "sc3d/wally_wall_prince_2.scw"
        static Custommesh = "wally_wall_filler"
        static Customanglestep = 90
        static Mapeditorvisualmode = 1
        static RowID = 43
    }
    static Wallyweirdwall = class {
        static Name = "WallyWeirdWall"
        static Tilecode = "-"
        static Dynamiccode = 10
        static Blocksmovement = true
        static Blocksprojectiles = true
        static Isdestructible = true
        static Isdestructibleovertime = true
        static Baseexportname = "custom"
        static Baseexplosioneffect = "sprout_004_wall_explosion"
        static Basehiteffect = "sprout_004_wall_hit"
        static Hashitanim = true
        static Shadowscalex = 100
        static Shadowscaley = 60
        static Shadowx = -10
        static Shadowy = 60
        static Shadowskew = 25
        static Lifetime = 200
        static Customscw = "sc3d/wally_wall_weird.scw"
        static Custommesh = "wally_wall"
        static Customanglestep = 0
        static Mapeditorvisualmode = 1
        static RowID = 44
    }
    static Wallyweirdfillerwall = class {
        static Name = "WallyWeirdFillerWall"
        static Tilecode = "-"
        static Dynamiccode = 11
        static Blocksmovement = true
        static Blocksprojectiles = true
        static Isdestructible = true
        static Isdestructibleovertime = true
        static Baseexportname = "custom"
        static Baseexplosioneffect = "sprout_004_wall_explosion"
        static Basehiteffect = "sprout_004_wall_hit"
        static Hashitanim = true
        static Shadowscalex = 100
        static Shadowscaley = 60
        static Shadowx = -10
        static Shadowy = 60
        static Shadowskew = 25
        static Lifetime = 200
        static Customscw = "sc3d/wally_wall_weird.scw"
        static Custommesh = "wally_wall_filler"
        static Customanglestep = 90
        static Mapeditorvisualmode = 1
        static RowID = 45
    }
    static Bouncer = class {
        static Name = "Bouncer"
        static Tilecode = "o"
        static Blocksmovement = true
        static Blocksprojectiles = true
        static Isdestructible = true
        static Isdestructibleovertime = true
        static Isbouncer = true
        static Baseexportname = "bouncer_tile"
        static Baseexplosioneffect = "wall1_explo"
        static Basehiteffect = "wall1_hit"
        static Hashitanim = true
        static Shadowscalex = 100
        static Shadowscaley = 60
        static Shadowx = -10
        static Shadowy = 60
        static Shadowskew = 25
        static Mapeditorvisualmode = 1
        static RowID = 46
    }
    static Indestructiblefence = class {
        static Name = "IndestructibleFence"
        static Tilecode = "E"
        static Blocksmovement = true
        static Blocksprojectiles = true
        static Baseexportname = "indestructible_fence_tile"
        static Baseexplosioneffect = "indestructible_explo_fx"
        static Basehiteffect = "indestructable_hit"
        static Sortoffset = 1
        static Shadowscalex = 100
        static Shadowscaley = 60
        static Shadowx = -10
        static Shadowy = 60
        static Shadowskew = 25
        static Mapeditorvisualmode = 1
        static Mapeditorconnected = true
        static RowID = 47
    }
    static Snow = class {
        static Name = "Snow"
        static Tilecode = "S"
        static Speedchange = -150
        static Baseexportname = "snow_tile"
        static RowID = 48
    }
    static Ice = class {
        static Name = "Ice"
        static Tilecode = "q"
        static Baseexportname = "ice_tile"
        static RowID = 49
    }
    static Indestructibledeco1 = class {
        static Name = "IndestructibleDeco1"
        static Tilecode = "È"
        static Baseexportname = "indestructible_deco1"
        static Baseexplosioneffect = "indestructible_explo_fx"
        static Basehiteffect = "indestructable_hit"
        static Sortoffset = 1
        static Shadowscalex = 100
        static Shadowscaley = 60
        static Shadowx = -10
        static Shadowy = 60
        static Shadowskew = 25
        static Mapeditorvisualmode = 1
        static Mapeditorconnected = true
        static RowID = 50
    }
    static Indestructibledeco2 = class {
        static Name = "IndestructibleDeco2"
        static Tilecode = "É"
        static Baseexportname = "indestructible_deco2"
        static Baseexplosioneffect = "indestructible_explo_fx"
        static Basehiteffect = "indestructable_hit"
        static Sortoffset = 1
        static Shadowscalex = 100
        static Shadowscaley = 60
        static Shadowx = -10
        static Shadowy = 60
        static Shadowskew = 25
        static Mapeditorvisualmode = 1
        static Mapeditorconnected = true
        static RowID = 51
    }
    static Indestructibledeco3 = class {
        static Name = "IndestructibleDeco3"
        static Tilecode = "Ê"
        static Baseexportname = "indestructible_deco3"
        static Baseexplosioneffect = "indestructible_explo_fx"
        static Basehiteffect = "indestructable_hit"
        static Sortoffset = 1
        static Shadowscalex = 100
        static Shadowscaley = 60
        static Shadowx = -10
        static Shadowy = 60
        static Shadowskew = 25
        static Mapeditorvisualmode = 1
        static Mapeditorconnected = true
        static RowID = 52
    }
    static Indestructibledeco4 = class {
        static Name = "IndestructibleDeco4"
        static Tilecode = "Ë"
        static Baseexportname = "indestructible_deco4"
        static Baseexplosioneffect = "indestructible_explo_fx"
        static Basehiteffect = "indestructable_hit"
        static Sortoffset = 1
        static Shadowscalex = 100
        static Shadowscaley = 60
        static Shadowx = -10
        static Shadowy = 60
        static Shadowskew = 25
        static Mapeditorvisualmode = 1
        static Mapeditorconnected = true
        static RowID = 53
    }
    static Damageable1 = class {
        static Name = "Damageable1"
        static Tilecode = "À"
        static Dynamiccode = 12
        static Blocksmovement = true
        static Blocksprojectiles = true
        static Isdestructibleovertime = true
        static Health = 6000
        static Healthstates = 4
        static Baseexportname = "damageable1"
        static Baseexplosioneffect = "godzilla_env_score"
        static Basehiteffect = "godzilla_env_hit"
        static Hashitanim = true
        static Shadowscalex = 100
        static Shadowscaley = 60
        static Shadowx = -10
        static Shadowy = 60
        static Shadowskew = 25
        static Mapeditorvisualmode = 1
        static RowID = 54
    }
    static Damageable2 = class {
        static Name = "Damageable2"
        static Tilecode = "Á"
        static Dynamiccode = 13
        static Blocksmovement = true
        static Blocksprojectiles = true
        static Isdestructibleovertime = true
        static Health = 6000
        static Healthstates = 4
        static Baseexportname = "damageable2"
        static Baseexplosioneffect = "godzilla_env_score"
        static Basehiteffect = "godzilla_env_hit"
        static Hashitanim = true
        static Shadowscalex = 100
        static Shadowscaley = 60
        static Shadowx = -10
        static Shadowy = 60
        static Shadowskew = 25
        static Mapeditorvisualmode = 1
        static RowID = 55
    }
    static Damageable3 = class {
        static Name = "Damageable3"
        static Tilecode = "Â"
        static Dynamiccode = 14
        static Blocksmovement = true
        static Blocksprojectiles = true
        static Isdestructibleovertime = true
        static Health = 6000
        static Healthstates = 4
        static Baseexportname = "damageable3"
        static Baseexplosioneffect = "godzilla_env_score"
        static Basehiteffect = "godzilla_env_hit"
        static Hashitanim = true
        static Shadowscalex = 100
        static Shadowscaley = 60
        static Shadowx = -10
        static Shadowy = 60
        static Shadowskew = 25
        static Mapeditorvisualmode = 1
        static RowID = 56
    }
    static Damageable4 = class {
        static Name = "Damageable4"
        static Tilecode = "Ã"
        static Dynamiccode = 15
        static Blocksmovement = true
        static Blocksprojectiles = true
        static Isdestructibleovertime = true
        static Health = 6000
        static Healthstates = 4
        static Baseexportname = "damageable4"
        static Baseexplosioneffect = "godzilla_env_score"
        static Basehiteffect = "godzilla_env_hit"
        static Hashitanim = true
        static Shadowscalex = 100
        static Shadowscaley = 60
        static Shadowx = -10
        static Shadowy = 60
        static Shadowskew = 25
        static Mapeditorvisualmode = 1
        static RowID = 57
    }
    static Wallydeepseawall = class {
        static Name = "WallyDeepseaWall"
        static Tilecode = "-"
        static Dynamiccode = 16
        static Blocksmovement = true
        static Blocksprojectiles = true
        static Isdestructible = true
        static Isdestructibleovertime = true
        static Baseexportname = "custom"
        static Baseexplosioneffect = "sprout_005_wall_explo"
        static Basehiteffect = "sprout_005_wall_hit"
        static Hashitanim = true
        static Shadowscalex = 100
        static Shadowscaley = 60
        static Shadowx = -10
        static Shadowy = 60
        static Shadowskew = 25
        static Lifetime = 200
        static Customscw = "sc3d/wally_wall_deepsea.glb"
        static Custommesh = "wally_wall"
        static Customanglestep = 0
        static Mapeditorvisualmode = 1
        static RowID = 58
    }
    static Wallydeepseafillerwall = class {
        static Name = "WallyDeepseaFillerWall"
        static Tilecode = "-"
        static Dynamiccode = 17
        static Blocksmovement = true
        static Blocksprojectiles = true
        static Isdestructible = true
        static Isdestructibleovertime = true
        static Baseexportname = "custom"
        static Baseexplosioneffect = "sprout_005_wall_explo"
        static Basehiteffect = "sprout_005_wall_hit"
        static Hashitanim = true
        static Shadowscalex = 100
        static Shadowscaley = 60
        static Shadowx = -10
        static Shadowy = 60
        static Shadowskew = 25
        static Lifetime = 200
        static Customscw = "sc3d/wally_wall_deepsea.glb"
        static Custommesh = "wally_wall_filler"
        static Customanglestep = 90
        static Mapeditorvisualmode = 1
        static RowID = 59
    }
    static Wallybathwall = class {
        static Name = "WallyBathWall"
        static Tilecode = "-"
        static Dynamiccode = 21
        static Blocksmovement = true
        static Blocksprojectiles = true
        static Isdestructible = true
        static Isdestructibleovertime = true
        static Baseexportname = "custom"
        static Baseexplosioneffect = "sprout_006_wall_explo"
        static Basehiteffect = "sprout_006_wall_hit"
        static Hashitanim = true
        static Shadowscalex = 100
        static Shadowscaley = 60
        static Shadowx = -10
        static Shadowy = 60
        static Shadowskew = 25
        static Lifetime = 200
        static Customscw = "sc3d/wally_wall_bath.glb"
        static Custommesh = "wally_wall"
        static Customanglestep = 0
        static Mapeditorvisualmode = 1
        static RowID = 60
    }
    static Wallybathfillerwall = class {
        static Name = "WallyBathFillerWall"
        static Tilecode = "-"
        static Dynamiccode = 22
        static Blocksmovement = true
        static Blocksprojectiles = true
        static Isdestructible = true
        static Isdestructibleovertime = true
        static Baseexportname = "custom"
        static Baseexplosioneffect = "sprout_006_wall_explo"
        static Basehiteffect = "sprout_006_wall_hit"
        static Hashitanim = true
        static Shadowscalex = 100
        static Shadowscaley = 60
        static Shadowx = -10
        static Shadowy = 60
        static Shadowskew = 25
        static Lifetime = 200
        static Customscw = "sc3d/wally_wall_bath.glb"
        static Custommesh = "wally_wall_filler"
        static Customanglestep = 90
        static Mapeditorvisualmode = 1
        static RowID = 61
    }
    static Meeplewalldefault = class {
        static Name = "MeepleWallDefault"
        static Tilecode = "-"
        static Dynamiccode = 18
        static Blocksmovement = true
        static Blocksprojectiles = true
        static Isdestructible = true
        static Isdestructibleovertime = false
        static Baseexportname = "custom"
        static Baseexplosioneffect = "meeple_def_atk_gadget_explo"
        static Basehiteffect = "wall1_hit"
        static Hashitanim = true
        static Lifetime = 80
        static Customscw = "sc3d/dice01.glb"
        static Customanglestep = 90
        static Mapeditorvisualmode = 1
        static Spawneffect = "meeple_def_atk_gadget_spawn"
        static RowID = 62
    }
    static Meeplewalldefault2 = class {
        static Name = "MeepleWallDefault2"
        static Tilecode = "-"
        static Dynamiccode = 19
        static Blocksmovement = true
        static Blocksprojectiles = true
        static Isdestructible = true
        static Isdestructibleovertime = false
        static Baseexportname = "custom"
        static Baseexplosioneffect = "meeple_def_atk_gadget_explo"
        static Basehiteffect = "wall1_hit"
        static Hashitanim = true
        static Lifetime = 80
        static Customscw = "sc3d/dice02.glb"
        static Customanglestep = 90
        static Mapeditorvisualmode = 1
        static Spawneffect = "meeple_def_atk_gadget_spawn"
        static RowID = 63
    }
    static Meeplewalldefault3 = class {
        static Name = "MeepleWallDefault3"
        static Tilecode = "-"
        static Dynamiccode = 20
        static Blocksmovement = true
        static Blocksprojectiles = true
        static Isdestructible = true
        static Isdestructibleovertime = false
        static Baseexportname = "custom"
        static Baseexplosioneffect = "meeple_def_atk_gadget_explo"
        static Basehiteffect = "wall1_hit"
        static Hashitanim = true
        static Lifetime = 80
        static Customscw = "sc3d/dice03.glb"
        static Customanglestep = 90
        static Mapeditorvisualmode = 1
        static Spawneffect = "meeple_def_atk_gadget_spawn"
        static RowID = 64
    }
    static Arenaconnector = class {
        static Name = "ArenaConnector"
        static Tilecode = "("
        static Restoreafterdynamicoverlap = true
        static Baseexportname = "custom"
        static Shadowscalex = 100
        static Shadowscaley = 60
        static Shadowx = -10
        static Shadowy = 60
        static Shadowskew = 25
        static Customscw = "sc3d/moba_connector_geo.glb"
        static Mapeditorvisualmode = 1
        static RowID = 65
    }
    static Outoflinewall = class {
        static Name = "OutOfLineWall"
        static Tilecode = "-"
        static Dynamiccode = 23
        static Blocksmovement = true
        static Blocksprojectiles = true
        static Isdestructible = true
        static Isdestructibleovertime = false
        static Baseexportname = "custom"
        static Baseexplosioneffect = "meeple_def_atk_gadget_explo"
        static Basehiteffect = "wall1_hit"
        static Hashitanim = true
        static Lifetime = 80
        static Customscw = "sc3d/subway_skill_hurdle_01.glb"
        static Customanglestep = 90
        static Mapeditorvisualmode = 1
        static Spawneffect = "surbway_hurdle_idle"
        static RowID = 66
    }
    static Outoflinewalllvl3 = class {
        static Name = "OutOfLineWall_lvl3"
        static Tilecode = "-"
        static Dynamiccode = 24
        static Blocksmovement = true
        static Blocksprojectiles = true
        static Isdestructible = true
        static Isdestructibleovertime = false
        static Baseexportname = "custom"
        static Baseexplosioneffect = "meeple_def_atk_gadget_explo"
        static Basehiteffect = "wall1_hit"
        static Hashitanim = true
        static Lifetime = 120
        static Customscw = "sc3d/subway_skill_hurdle_01.glb"
        static Customanglestep = 90
        static Mapeditorvisualmode = 1
        static Spawneffect = "surbway_hurdle_idle"
        static RowID = 67
    }
}

export default Tiles;