class Bppurchasepopup {
    static Season8 = class {
        static Name = "season8"
        static Season = 7
        static Heroarea1 = "ShotgunGirlPrincess"
        static Heroarea2 = "KnightDefault"
        static Heroarea3 = "KnightNinja"
        static Framename = "8"
        static RowID = 1
    }
    static Season9 = class {
        static Name = "season9"
        static Season = 8
        static Heroarea1 = "BullDudeTerminator"
        static Heroarea2 = "DuplicatorDefault"
        static Heroarea3 = "DuplicatorChola"
        static Framename = "9"
        static RowID = 2
    }
    static Season10 = class {
        static Name = "season10"
        static Season = 9
        static Heroarea1 = "RosaBP"
        static Heroarea2 = "KickerDudeDefault"
        static Heroarea3 = "KickerDudeFurious"
        static Framename = "10"
        static RowID = 3
    }
    static Season11 = class {
        static Name = "season11"
        static Season = 10
        static Heroarea1 = "TrickshotDudeFirefly"
        static Heroarea2 = "FleaDefault"
        static Heroarea3 = "FleaSpaceCactus"
        static Framename = "11"
        static RowID = 4
    }
    static Season12 = class {
        static Name = "season12"
        static Season = 11
        static Heroarea1 = "WhirlwindBiker"
        static Heroarea2 = "JetpackGirlDefault"
        static Heroarea3 = "JetpackGirlValkyrie"
        static Framename = "12"
        static RowID = 5
    }
    static Season13 = class {
        static Name = "season13"
        static Season = 12
        static Heroarea1 = "GunslingerPaintball"
        static Heroarea2 = "SilencerDefault"
        static Heroarea3 = "SilencerPharaoh"
        static Framename = "13"
        static RowID = 6
    }
    static Season14 = class {
        static Name = "season14"
        static Season = 13
        static Heroarea1 = "DeadMariachiOutlaw"
        static Heroarea2 = "WeaponThrowerDefault"
        static Heroarea3 = "WeaponThrowerEmperor"
        static Framename = "14"
        static RowID = 7
    }
    static Season15 = class {
        static Name = "season15"
        static Season = 14
        static Heroarea1 = "ArtilleryDudeZombie"
        static Heroarea2 = "ShieldTankDefault"
        static Heroarea3 = "ShieldTankChainsaw"
        static Framename = "15"
        static RowID = 8
    }
    static Season16 = class {
        static Name = "season16"
        static Season = 15
        static Heroarea1 = "ShamanGummybear"
        static Heroarea2 = "BeamerDefault"
        static Heroarea3 = "BeamerLavaQueen"
        static Framename = "16"
        static RowID = 9
    }
    static Season17 = class {
        static Name = "season17"
        static Season = 16
        static Heroarea1 = "LuchadorButler"
        static Heroarea2 = "SplitterDefault"
        static Heroarea3 = "SplitterCultist"
        static Framename = "17"
        static RowID = 10
    }
    static Season18 = class {
        static Name = "season18"
        static Season = 17
        static Heroarea2 = "MaisieDefault"
        static Heroarea3 = "MaisieSnake"
        static Framename = "18"
        static RowID = 11
    }
    static Season19 = class {
        static Name = "season19"
        static Season = 18
        static Heroarea2 = "DuelistDefault"
        static Heroarea3 = "DuelistBrain"
        static Framename = "19"
        static RowID = 12
    }
    static Season20 = class {
        static Name = "season20"
        static Season = 19
        static Heroarea2 = "CookerDefault"
        static Heroarea3 = "CookerDeepsea"
        static Framename = "20"
        static RowID = 13
    }
    static Season21 = class {
        static Name = "season21"
        static Season = 20
        static Heroarea2 = "CocoonerDefault"
        static Heroarea3 = "CocoonerRosie"
        static Framename = "21"
        static Skin = "CocoonerRosie"
        static Pin = "emoji_cotton_candy"
        static Icon = "player_icon_bp_circus"
        static Spray = "spray_sad_clown"
        static Multiplier = 13
        static RowID = 14
    }
    static Season22 = class {
        static Name = "season22"
        static Season = 21
        static Heroarea1 = "Percenteranime"
        static Heroarea2 = "PercenteranimeChromaYellow"
        static Heroarea3 = "PercenteranimeChromaGreen"
        static Framename = "22"
        static Skin = "Percenteranime"
        static Skinchroma = "PercenteranimeChromaYellow"
        static Pin = "emoji_skulltoon"
        static Icon = "player_icon_bp_cartoon"
        static Spray = "spray_cartoon_cloud"
        static Animcover = "SIGNATURE"
        static Animskin = "HAPPY"
        static Animchromas = "HAPPY"
        static Jingle = "sfx/brawly_toonz_loading_01.ogg"
        static Multiplier = 18
        static Plusmultiplier = 20
        static RowID = 15
    }
    static Season23 = class {
        static Name = "season23"
        static Season = 22
        static Heroarea1 = "AttacherBoxer"
        static Heroarea2 = "AttacherBoxerChromaDarkpaw"
        static Heroarea3 = "AttacherBoxerChromaGoldpaw"
        static Framename = "23"
        static Skin = "AttacherBoxer"
        static Skinchroma = "AttacherBoxerChromaDarkpaw"
        static Pin = "emoji_dragon"
        static Icon = "player_icon_bp_dragon"
        static Spray = "spray_lny_dragon"
        static Animcover = "SIGNATURE"
        static Animskin = "HAPPY"
        static Animchromas = "HAPPY"
        static Jingle = "sfx/brawl_fighting_load_01.ogg"
        static Multiplier = 18
        static Plusmultiplier = 20
        static RowID = 16
    }
    static Season24 = class {
        static Name = "season24"
        static Season = 23
        static Heroarea1 = "ShotgunGirlDancer"
        static Heroarea2 = "ShotgunGirlDancerBlue"
        static Heroarea3 = "ShotgunGirlDancerPurple"
        static Framename = "24"
        static Skin = "ShotgunGirlDancer"
        static Skinchroma = "ShotgunGirlDancerBlue"
        static Pin = "emoji_sandclock"
        static Icon = "player_icon_bp_sandsoftime"
        static Spray = "spray_sandsoftime"
        static Animcover = "SIGNATURE"
        static Animskin = "HAPPY"
        static Animchromas = "HAPPY"
        static Multiplier = 18
        static Plusmultiplier = 20
        static RowID = 17
    }
    static Season25 = class {
        static Name = "season25"
        static Season = 24
        static Heroarea1 = "RopeDudeFenrir"
        static Heroarea2 = "RopeDudeFenrirRed"
        static Heroarea3 = "RopeDudeFenrirBlack"
        static Framename = "25"
        static Skin = "RopeDudeFenrir"
        static Skinchroma = "RopeDudeFenrirRed"
        static Pin = "emoji_skull_ragnarock"
        static Icon = "player_icon_bp_ragnarok"
        static Spray = "spray_ragnarok"
        static Animcover = "SIGNATURE"
        static Animskin = "HAPPY"
        static Animchromas = "HAPPY"
        static Multiplier = 18
        static Plusmultiplier = 20
        static RowID = 18
    }
    static Season26 = class {
        static Name = "season26"
        static Season = 25
        static Heroarea1 = "ClusterBombDudeGodzilla"
        static Heroarea2 = "ClusterBombDudeGodzillaGold"
        static Heroarea3 = "ClusterBombDudeGodzillaDark"
        static Framename = "26"
        static Skin = "ClusterBombDudeGodzilla"
        static Skinchroma = "ClusterBombDudeGodzillaGold"
        static Pin = "emoji_godzilla_egg"
        static Icon = "player_icon_bp_godzilla"
        static Spray = "spray_bp_godzilla"
        static Animcover = "SIGNATURE"
        static Animskin = "HAPPY"
        static Animchromas = "HAPPY"
        static Multiplier = 18
        static Plusmultiplier = 20
        static RowID = 19
    }
    static Season27 = class {
        static Name = "season27"
        static Season = 26
        static Heroarea1 = "RocketGirlVirus"
        static Heroarea2 = "RocketGirlVirusRGB"
        static Heroarea3 = "RocketGirlVirusGold"
        static Framename = "27"
        static Skin = "RocketGirlVirus"
        static Skinchroma = "RocketGirlVirusGold"
        static Pin = "emoji_hacker"
        static Icon = "player_icon_bp_hackers"
        static Spray = "spray_bp_hackers"
        static Animcover = "SIGNATURE"
        static Animskin = "HAPPY"
        static Animchromas = "HAPPY"
        static Multiplier = 18
        static Plusmultiplier = 20
        static RowID = 20
    }
    static Season28 = class {
        static Name = "season28"
        static Season = 27
        static Heroarea1 = "MummyGreek"
        static Heroarea2 = "MummyGreekRed"
        static Heroarea3 = "MummyGreekBlue"
        static Framename = "28"
        static Skin = "MummyGreek"
        static Skinchroma = "MummyGreekRed"
        static Pin = "emoji_bp_greek"
        static Icon = "player_icon_bp_olympic"
        static Spray = "spray_bp_olympic"
        static Animcover = "SIGNATURE"
        static Animskin = "HAPPY"
        static Animchromas = "HAPPY"
        static Jingle = "sfx/brawlympus_loading_01.ogg"
        static Multiplier = 18
        static Plusmultiplier = 20
        static RowID = 21
    }
    static Season29 = class {
        static Name = "season29"
        static Season = 28
        static Heroarea1 = "SandstormDeepsea"
        static Heroarea2 = "SandstormDeepseaPurple"
        static Heroarea3 = "SandstormDeepseaYellow"
        static Framename = "29"
        static Skin = "SandstormDeepsea"
        static Skinchroma = "SandstormDeepseaPurple"
        static Pin = "emoji_bp_deep"
        static Icon = "player_icon_bp_deepsea"
        static Spray = "spray_bp_deepsea"
        static Animcover = "SIGNATURE"
        static Animskin = "HAPPY"
        static Animchromas = "HAPPY"
        static Jingle = "sfx/brawl_underwater_load_01.ogg"
        static Multiplier = 18
        static Plusmultiplier = 20
        static RowID = 22
    }
    static Season30 = class {
        static Name = "season30"
        static Season = 29
        static Heroarea1 = "UndertakerSB"
        static Heroarea2 = "UndertakerSBPink"
        static Heroarea3 = "UndertakerSBBlue"
        static Framename = "30"
        static Skin = "UndertakerSB"
        static Skinchroma = "UndertakerSBPink"
        static Pin = "emoji_bp_spongebob"
        static Icon = "player_icon_bp_sb"
        static Spray = "spray_bp_sb"
        static Animcover = "SIGNATURE"
        static Animskin = "HAPPY"
        static Animchromas = "HAPPY"
        static Multiplier = 18
        static Plusmultiplier = 20
        static RowID = 23
    }
    static Season31 = class {
        static Name = "season31"
        static Season = 30
        static Heroarea1 = "PowerLevelerOnceupon"
        static Heroarea2 = "PowerLevelerOnceupon_Red"
        static Heroarea3 = "PowerLevelerOnceupon_Gold"
        static Framename = "31"
        static Skin = "PowerLevelerOnceupon"
        static Skinchroma = "PowerLevelerOnceupon_Gold"
        static Pin = "emoji_bp_darkonceupon"
        static Icon = "player_icon_bp_darkonceupon"
        static Spray = "spray_bp_darkonce"
        static Animcover = "SIGNATURE"
        static Animskin = "HAPPY"
        static Animchromas = "HAPPY"
        static Multiplier = 18
        static Plusmultiplier = 20
        static RowID = 24
    }
    static Season32 = class {
        static Name = "season32"
        static Season = 31
        static Heroarea1 = "TwinsAngel"
        static Heroarea2 = "TwinsAngelChroma1"
        static Heroarea3 = "TwinsAngelChroma2"
        static Framename = "32"
        static Skin = "TwinsAngel"
        static Skinchroma = "TwinsAngelChroma1"
        static Pin = "emoji_bp_cursed"
        static Icon = "player_icon_bp_angelsdemons"
        static Spray = "spray_bp_angelsdemons"
        static Animcover = "SIGNATURE"
        static Animskin = "HAPPY"
        static Animchromas = "HAPPY"
        static Multiplier = 18
        static Plusmultiplier = 20
        static RowID = 25
    }
    static Season33 = class {
        static Name = "season33"
        static Season = 32
        static Heroarea1 = "MaisieToon"
        static Heroarea2 = "MaisieToonChroma1"
        static Heroarea3 = "MaisieToonChroma2"
        static Framename = "33"
        static Skin = "MaisieToon"
        static Skinchroma = "MaisieToonChroma1"
        static Pin = "emoji_bp_toon"
        static Icon = "player_icon_bp_toons2"
        static Spray = "spray_bp_toons2"
        static Animcover = "SIGNATURE"
        static Animskin = "HAPPY"
        static Animchromas = "HAPPY"
        static Multiplier = 18
        static Plusmultiplier = 20
        static RowID = 26
    }
    static Season34 = class {
        static Name = "season34"
        static Season = 33
        static Heroarea1 = "SamuraiStarrForce"
        static Heroarea2 = "SamuraiStarrForceChroma1"
        static Heroarea3 = "SamuraiStarrForceChroma2"
        static Framename = "34"
        static Skin = "SamuraiStarrForce"
        static Skinchroma = "SamuraiStarrForceChroma1"
        static Pin = "emoji_bp_starrforce"
        static Icon = "player_icon_bp_starrforce"
        static Spray = "spray_bp_starrforce"
        static Animcover = "SIGNATURE"
        static Animskin = "HAPPY"
        static Animchromas = "HAPPY"
        static Multiplier = 18
        static Plusmultiplier = 20
        static RowID = 27
    }
    static Season35 = class {
        static Name = "season35"
        static Season = 34
        static Heroarea1 = "AxeJugglerGoodRandoms"
        static Heroarea2 = "AxeJugglerGoodRandomsChroma1"
        static Heroarea3 = "AxeJugglerGoodRandomsChroma2"
        static Framename = "35"
        static Skin = "AxeJugglerGoodRandoms"
        static Skinchroma = "AxeJugglerGoodRandomsChroma1"
        static Pin = "emoji_bp_goodrandoms"
        static Icon = "player_icon_bp_goodrandoms"
        static Spray = "spray_bp_goodrandoms"
        static Animcover = "SIGNATURE"
        static Animskin = "HAPPY"
        static Animchromas = "HAPPY"
        static Multiplier = 18
        static Plusmultiplier = 20
        static RowID = 28
    }
    static Season36 = class {
        static Name = "season36"
        static Season = 35
        static Heroarea1 = "HammerDudeSandsOfTimes"
        static Heroarea2 = "HammerDudeSandsOfTimesLight"
        static Heroarea3 = "HammerDudeSandsOfTimesDark"
        static Framename = "36"
        static Skin = "HammerDudeSandsOfTimes"
        static Skinchroma = "HammerDudeSandsOfTimesLight"
        static Pin = "emoji_bp_sandsoftime2"
        static Icon = "player_icon_bp_sandsoftime2"
        static Spray = "spray_bp_darksands"
        static Animcover = "SIGNATURE"
        static Animskin = "HAPPY"
        static Animchromas = "HAPPY"
        static Multiplier = 18
        static Plusmultiplier = 20
        static RowID = 29
    }
    static Season37 = class {
        static Name = "season37"
        static Season = 36
        static Heroarea1 = "BaseballVillain"
        static Heroarea2 = "BaseballVillainChromaPink"
        static Heroarea3 = "BaseballVillainChromaBlue"
        static Framename = "37"
        static Skin = "BaseballVillain"
        static Skinchroma = "BaseballVillainChromaPink"
        static Pin = "emoji_bp_superheroes"
        static Icon = "player_icon_bp_super"
        static Spray = "spray_bp_super"
        static Animcover = "SIGNATURE"
        static Animskin = "HAPPY"
        static Animchromas = "HAPPY"
        static Multiplier = 18
        static Plusmultiplier = 20
        static RowID = 30
    }
    static Season38 = class {
        static Name = "season38"
        static Season = 37
        static Heroarea1 = "SniperJapan"
        static Heroarea2 = "SniperJapanChromaBlue"
        static Heroarea3 = "SniperJapanChromaGreen"
        static Framename = "38"
        static Skin = "SniperJapan"
        static Skinchroma = "SniperJapanChromaBlue"
        static Pin = "emoji_bp_feudaljapan"
        static Icon = "player_icon_bp_feudaljapan"
        static Spray = "spray_bp_feudaljapan"
        static Animcover = "SIGNATURE"
        static Animskin = "HAPPY"
        static Animchromas = "HAPPY"
        static Multiplier = 18
        static Plusmultiplier = 20
        static RowID = 31
    }
    static Season39 = class {
        static Name = "season39"
        static Season = 38
        static Heroarea1 = "EnragerKaiju"
        static Heroarea2 = "EnragerKaijuChroma1"
        static Heroarea3 = "EnragerKaijuChroma2"
        static Framename = "39"
        static Skin = "EnragerKaiju"
        static Skinchroma = "EnragerKaijuChroma1"
        static Pin = "emoji_bp_kaiju"
        static Icon = "player_icon_bp_kaiju"
        static Spray = "spray_bp_kaiju"
        static Animcover = "SIGNATURE"
        static Animskin = "HAPPY"
        static Animchromas = "HAPPY"
        static Multiplier = 18
        static Plusmultiplier = 20
        static RowID = 32
    }
    static Season40 = class {
        static Name = "season40"
        static Season = 39
        static Heroarea1 = "UndertakerGreekGod"
        static Heroarea2 = "UndertakerGreekGodChroma1"
        static Heroarea3 = "UndertakerGreekGodChroma2"
        static Framename = "40"
        static Skin = "UndertakerGreekGod"
        static Skinchroma = "UndertakerGreekGodChroma1"
        static Pin = "emoji_bp_darkgreek"
        static Icon = "player_icon_bp_darkgreek"
        static Spray = "spray_bp_greekmortis"
        static Animcover = "SIGNATURE"
        static Animskin = "HAPPY"
        static Animchromas = "HAPPY"
        static Multiplier = 18
        static Plusmultiplier = 20
        static RowID = 33
    }
    static Season41 = class {
        static Name = "season41"
        static Season = 40
        static Heroarea1 = "BowDudeFantasy"
        static Heroarea2 = "BowDudeFantasyChroma1"
        static Heroarea3 = "BowDudeFantasyChroma2"
        static Framename = "41"
        static Skin = "BowDudeFantasy"
        static Skinchroma = "BowDudeFantasyChroma1"
        static Pin = "emoji_bp_fantasy"
        static Icon = "player_icon_bp_fantasy"
        static Spray = "spray_bp_fantasybo"
        static Animcover = "SIGNATURE"
        static Animskin = "HAPPY"
        static Animchromas = "HAPPY"
        static Multiplier = 18
        static Plusmultiplier = 20
        static RowID = 34
    }
    static Season42 = class {
        static Name = "season42"
        static Season = 41
        static Heroarea1 = "MummySurfer"
        static Heroarea2 = "MummySurferChroma1"
        static Heroarea3 = "MummySurferChroma2"
        static Framename = "42"
        static Skin = "MummySurfer"
        static Skinchroma = "MummySurferChroma1"
        static Pin = "emoji_bp_street"
        static Icon = "player_icon_bp_graffiti"
        static Spray = "spray_bp_street"
        static Animcover = "SIGNATURE"
        static Animskin = "HAPPY"
        static Animchromas = "HAPPY"
        static Multiplier = 18
        static Plusmultiplier = 20
        static RowID = 35
    }
    static Season43 = class {
        static Name = "season43"
        static Season = 42
        static Heroarea1 = "CrowBrawloween"
        static Heroarea2 = "CrowBrawloweenRed"
        static Heroarea3 = "CrowBrawloweenWhite"
        static Framename = "43"
        static Skin = "CrowBrawloween"
        static Skinchroma = "CrowBrawloweenRed"
        static Pin = "emoji_bp_brawloween"
        static Icon = "player_icon_bp_brawloween25"
        static Spray = "spray_bp_brawloween25"
        static Animcover = "SIGNATURE"
        static Animskin = "HAPPY"
        static Animchromas = "HAPPY"
        static Multiplier = 18
        static Plusmultiplier = 20
        static RowID = 36
    }
}

export default Bppurchasepopup;