class Fametiers {
    static Global1 = class {
        static Name = "Global1"
        static Fametonext = 2000
        static Group = 1
        static Tid = "TID_FAME_TIER_GLOBAL1"
        static Iconswf = "sc/ui.sc"
        static Iconexportname = "icon_fame_tier_1_1"
        static Iconbigexportname = "fame_big_tier_1"
        static Iconstarsexportname = "fame_stars_tier_1_1"
        static Reward = "globalFrame"
        static Rewardtype = 63
        static RowID = 1
    }
    static Global2 = class {
        static Name = "Global2"
        static Fametonext = 2000
        static Group = 1
        static Tid = "TID_FAME_TIER_GLOBAL2"
        static Iconswf = "sc/ui.sc"
        static Iconexportname = "icon_fame_tier_1_2"
        static Iconbigexportname = "fame_big_tier_1"
        static Iconstarsexportname = "fame_stars_tier_1_2"
        static Reward = "player_icon_fame_earth"
        static Rewardtype = 25
        static RowID = 2
    }
    static Global3 = class {
        static Name = "Global3"
        static Fametonext = 2000
        static Group = 1
        static Tid = "TID_FAME_TIER_GLOBAL3"
        static Iconswf = "sc/ui.sc"
        static Iconexportname = "icon_fame_tier_1_3"
        static Iconbigexportname = "fame_big_tier_1"
        static Iconstarsexportname = "fame_stars_tier_1_3"
        static Reward = "emoji_fame_earth"
        static Rewardtype = 19
        static RowID = 3
    }
    static Lunar1 = class {
        static Name = "Lunar1"
        static Fametonext = 3200
        static Group = 2
        static Tid = "TID_FAME_TIER_LUNAR1"
        static Iconswf = "sc/ui.sc"
        static Iconexportname = "icon_fame_tier_2_1"
        static Iconbigexportname = "fame_big_tier_2"
        static Iconstarsexportname = "fame_stars_tier_2_1"
        static Reward = "lunarFrame"
        static Rewardtype = 63
        static RowID = 4
    }
    static Lunar2 = class {
        static Name = "Lunar2"
        static Fametonext = 3200
        static Group = 2
        static Tid = "TID_FAME_TIER_LUNAR2"
        static Iconswf = "sc/ui.sc"
        static Iconexportname = "icon_fame_tier_2_2"
        static Iconbigexportname = "fame_big_tier_2"
        static Iconstarsexportname = "fame_stars_tier_2_2"
        static Reward = "player_icon_fame_moon"
        static Rewardtype = 25
        static RowID = 5
    }
    static Lunar3 = class {
        static Name = "Lunar3"
        static Fametonext = 3200
        static Group = 2
        static Tid = "TID_FAME_TIER_LUNAR3"
        static Iconswf = "sc/ui.sc"
        static Iconexportname = "icon_fame_tier_2_3"
        static Iconbigexportname = "fame_big_tier_2"
        static Iconstarsexportname = "fame_stars_tier_2_3"
        static Reward = "emoji_fame_moon"
        static Rewardtype = 19
        static RowID = 6
    }
    static Martial1 = class {
        static Name = "Martial1"
        static Fametonext = 4500
        static Group = 3
        static Tid = "TID_FAME_TIER_MARTIAL1"
        static Iconswf = "sc/ui.sc"
        static Iconexportname = "icon_fame_tier_3_1"
        static Iconbigexportname = "fame_big_tier_3"
        static Iconstarsexportname = "fame_stars_tier_3_1"
        static Reward = "martialFrame"
        static Rewardtype = 63
        static RowID = 7
    }
    static Martial2 = class {
        static Name = "Martial2"
        static Fametonext = 4500
        static Group = 3
        static Tid = "TID_FAME_TIER_MARTIAL2"
        static Iconswf = "sc/ui.sc"
        static Iconexportname = "icon_fame_tier_3_2"
        static Iconbigexportname = "fame_big_tier_3"
        static Iconstarsexportname = "fame_stars_tier_3_2"
        static Reward = "player_icon_fame_mars"
        static Rewardtype = 25
        static RowID = 8
    }
    static Martial3 = class {
        static Name = "Martial3"
        static Fametonext = 4500
        static Group = 3
        static Tid = "TID_FAME_TIER_MARTIAL3"
        static Iconswf = "sc/ui.sc"
        static Iconexportname = "icon_fame_tier_3_3"
        static Iconbigexportname = "fame_big_tier_3"
        static Iconstarsexportname = "fame_stars_tier_3_3"
        static Reward = "emoji_fame_mars"
        static Rewardtype = 19
        static RowID = 9
    }
    static Saturnal1 = class {
        static Name = "Saturnal1"
        static Fametonext = 8000
        static Group = 4
        static Tid = "TID_FAME_TIER_SATURNAL1"
        static Iconswf = "sc/ui.sc"
        static Iconexportname = "icon_fame_tier_4_1"
        static Iconbigexportname = "fame_big_tier_4"
        static Iconstarsexportname = "fame_stars_tier_4_1"
        static Reward = "saturnalFrame"
        static Rewardtype = 63
        static RowID = 10
    }
    static Saturnal2 = class {
        static Name = "Saturnal2"
        static Fametonext = 8000
        static Group = 4
        static Tid = "TID_FAME_TIER_SATURNAL2"
        static Iconswf = "sc/ui.sc"
        static Iconexportname = "icon_fame_tier_4_2"
        static Iconbigexportname = "fame_big_tier_4"
        static Iconstarsexportname = "fame_stars_tier_4_2"
        static Reward = "player_icon_fame_saturn"
        static Rewardtype = 25
        static RowID = 11
    }
    static Saturnal3 = class {
        static Name = "Saturnal3"
        static Fametonext = 8000
        static Group = 4
        static Tid = "TID_FAME_TIER_SATURNAL3"
        static Iconswf = "sc/ui.sc"
        static Iconexportname = "icon_fame_tier_4_3"
        static Iconbigexportname = "fame_big_tier_4"
        static Iconstarsexportname = "fame_stars_tier_4_3"
        static Reward = "emoji_fame_saturn"
        static Rewardtype = 19
        static RowID = 12
    }
    static Solar1 = class {
        static Name = "Solar1"
        static Fametonext = 12000
        static Group = 5
        static Tid = "TID_FAME_TIER_SOLAR1"
        static Iconswf = "sc/ui.sc"
        static Iconexportname = "icon_fame_tier_5_1"
        static Iconbigexportname = "fame_big_tier_5"
        static Iconstarsexportname = "fame_stars_tier_5_1"
        static Reward = "solarFrame"
        static Rewardtype = 63
        static RowID = 13
    }
    static Solar2 = class {
        static Name = "Solar2"
        static Fametonext = 12000
        static Group = 5
        static Tid = "TID_FAME_TIER_SOLAR2"
        static Iconswf = "sc/ui.sc"
        static Iconexportname = "icon_fame_tier_5_2"
        static Iconbigexportname = "fame_big_tier_5"
        static Iconstarsexportname = "fame_stars_tier_5_2"
        static Reward = "player_icon_fame_sun"
        static Rewardtype = 25
        static RowID = 14
    }
    static Solar3 = class {
        static Name = "Solar3"
        static Fametonext = 12000
        static Group = 5
        static Tid = "TID_FAME_TIER_SOLAR3"
        static Iconswf = "sc/ui.sc"
        static Iconexportname = "icon_fame_tier_5_3"
        static Iconbigexportname = "fame_big_tier_5"
        static Iconstarsexportname = "fame_stars_tier_5_3"
        static Reward = "emoji_fame_sun"
        static Rewardtype = 19
        static RowID = 15
    }
    static Meteor1 = class {
        static Name = "Meteor1"
        static Fametonext = 20000
        static Group = 6
        static Tid = "TID_FAME_TIER_METEOR1"
        static Iconswf = "sc/ui.sc"
        static Iconexportname = "icon_fame_tier_6_1"
        static Iconbigexportname = "fame_big_tier_6"
        static Iconstarsexportname = "fame_stars_tier_6_1"
        static Reward = "meteorFrame"
        static Rewardtype = 63
        static RowID = 16
    }
    static Meteor2 = class {
        static Name = "Meteor2"
        static Fametonext = 20000
        static Group = 6
        static Tid = "TID_FAME_TIER_METEOR2"
        static Iconswf = "sc/ui.sc"
        static Iconexportname = "icon_fame_tier_6_2"
        static Iconbigexportname = "fame_big_tier_6"
        static Iconstarsexportname = "fame_stars_tier_6_2"
        static Reward = "player_icon_fame_meteor"
        static Rewardtype = 25
        static RowID = 17
    }
    static Meteor3 = class {
        static Name = "Meteor3"
        static Fametonext = 20000
        static Group = 6
        static Tid = "TID_FAME_TIER_METEOR3"
        static Iconswf = "sc/ui.sc"
        static Iconexportname = "icon_fame_tier_6_3"
        static Iconbigexportname = "fame_big_tier_6"
        static Iconstarsexportname = "fame_stars_tier_6_3"
        static Reward = "emoji_fame_meteor"
        static Rewardtype = 19
        static RowID = 18
    }
    static Alien1 = class {
        static Name = "Alien1"
        static Fametonext = 50000
        static Group = 7
        static Tid = "TID_FAME_TIER_ALIEN1"
        static Iconswf = "sc/ui.sc"
        static Iconexportname = "icon_fame_tier_7_1"
        static Iconbigexportname = "fame_big_tier_7"
        static Iconstarsexportname = "fame_stars_tier_7_1"
        static Reward = "alienFrame"
        static Rewardtype = 63
        static RowID = 19
    }
    static Alien2 = class {
        static Name = "Alien2"
        static Fametonext = 50000
        static Group = 7
        static Tid = "TID_FAME_TIER_ALIEN2"
        static Iconswf = "sc/ui.sc"
        static Iconexportname = "icon_fame_tier_7_2"
        static Iconbigexportname = "fame_big_tier_7"
        static Iconstarsexportname = "fame_stars_tier_7_2"
        static Reward = "player_icon_fame_alien"
        static Rewardtype = 25
        static RowID = 20
    }
    static Alien3 = class {
        static Name = "Alien3"
        static Fametonext = 50000
        static Group = 7
        static Tid = "TID_FAME_TIER_ALIEN3"
        static Iconswf = "sc/ui.sc"
        static Iconexportname = "icon_fame_tier_7_3"
        static Iconbigexportname = "fame_big_tier_7"
        static Iconstarsexportname = "fame_stars_tier_7_3"
        static Reward = "emoji_fame_alien"
        static Rewardtype = 19
        static RowID = 21
    }
}

export default Fametiers;