class RandomRewardContainersParser {
    static Data: any[] = [];

    static Init(csvData: any[]) {
        RandomRewardContainersParser.Data = csvData;
    }
    static GetName() { return RandomRewardContainersParser.Data.map(row => row['Name']); }
    static GetTid() { return RandomRewardContainersParser.Data.map(row => row['TID']); }
    static GetTicketsinwingamesdraw() { return RandomRewardContainersParser.Data.map(row => row['TicketsInWinGamesDraw']); }
    static GetTicketsincollabdraw() { return RandomRewardContainersParser.Data.map(row => row['TicketsInCollabDraw']); }
    static GetTicketsinpresentdraw() { return RandomRewardContainersParser.Data.map(row => row['TicketsInPresentDraw']); }
    static GetRarity() { return RandomRewardContainersParser.Data.map(row => row['Rarity']); }
    static GetIsrarityoffercontainer() { return RandomRewardContainersParser.Data.map(row => row['IsRarityOfferContainer']); }
    static GetGrouptype() { return RandomRewardContainersParser.Data.map(row => row['GroupType']); }
    static GetCustomrewards() { return RandomRewardContainersParser.Data.map(row => row['CustomRewards']); }
    static GetIsoverchargedraw() { return RandomRewardContainersParser.Data.map(row => row['IsOverchargeDraw']); }
    static GetIsrankeddraw() { return RandomRewardContainersParser.Data.map(row => row['IsRankedDraw']); }
    static GetCollabid() { return RandomRewardContainersParser.Data.map(row => row['CollabId']); }
    static GetMultidropcount() { return RandomRewardContainersParser.Data.map(row => row['MultiDropCount']); }
    static GetPremiumdrawcountformultidrops() { return RandomRewardContainersParser.Data.map(row => row['PremiumDrawCountForMultiDrops']); }
    static GetScw() { return RandomRewardContainersParser.Data.map(row => row['SCW']); }
    static GetVisualtype() { return RandomRewardContainersParser.Data.map(row => row['VisualType']); }
    static GetTransitionexportname() { return RandomRewardContainersParser.Data.map(row => row['TransitionExportName']); }
    static GetScfilename() { return RandomRewardContainersParser.Data.map(row => row['SCFilename']); }
    static GetTargetclip() { return RandomRewardContainersParser.Data.map(row => row['TargetClip']); }
    static GetSlashesneeded() { return RandomRewardContainersParser.Data.map(row => row['SlashesNeeded']); }
    static GetSlashclaweffect() { return RandomRewardContainersParser.Data.map(row => row['SlashClawEffect']); }
    static GetSlashclawshadow() { return RandomRewardContainersParser.Data.map(row => row['SlashClawShadow']); }
    static GetSlashclawcount() { return RandomRewardContainersParser.Data.map(row => row['SlashClawCount']); }
    static GetSoundslash() { return RandomRewardContainersParser.Data.map(row => row['SoundSlash']); }
    static GetCustombgexportname() { return RandomRewardContainersParser.Data.map(row => row['CustomBgExportName']); }
    static GetBackgroundframelabel() { return RandomRewardContainersParser.Data.map(row => row['BackgroundFrameLabel']); }
    static GetChargeprogressclip() { return RandomRewardContainersParser.Data.map(row => row['ChargeProgressClip']); }
    static GetHoldchargeeffect() { return RandomRewardContainersParser.Data.map(row => row['HoldChargeEffect']); }
    static GetToucheffectfilename() { return RandomRewardContainersParser.Data.map(row => row['TouchEffectFilename']); }
    static GetToucheffectexportname() { return RandomRewardContainersParser.Data.map(row => row['TouchEffectExportName']); }
    static GetTapeffectclip1() { return RandomRewardContainersParser.Data.map(row => row['TapEffectClip1']); }
    static GetTapeffectclip2() { return RandomRewardContainersParser.Data.map(row => row['TapEffectClip2']); }
    static GetTapeffectclip3() { return RandomRewardContainersParser.Data.map(row => row['TapEffectClip3']); }
    static GetTapeffectclipbg() { return RandomRewardContainersParser.Data.map(row => row['TapEffectClipBg']); }
    static GetFinalcontainereffectclip() { return RandomRewardContainersParser.Data.map(row => row['FinalContainerEffectClip']); }
    static GetFinalcontainereffectclipbg() { return RandomRewardContainersParser.Data.map(row => row['FinalContainerEffectClipBg']); }
    static GetOpeningeffectclip() { return RandomRewardContainersParser.Data.map(row => row['OpeningEffectClip']); }
    static GetOpeningeffectclipbg() { return RandomRewardContainersParser.Data.map(row => row['OpeningEffectClipBg']); }
    static GetRewardslefticon() { return RandomRewardContainersParser.Data.map(row => row['RewardsLeftIcon']); }
    static GetOpeninginstruction() { return RandomRewardContainersParser.Data.map(row => row['OpeningInstruction']); }
    static GetIntro3danimstart() { return RandomRewardContainersParser.Data.map(row => row['Intro3DAnimStart']); }
    static GetIntro3danimend() { return RandomRewardContainersParser.Data.map(row => row['Intro3DAnimEnd']); }
    static GetIdle3danimstart() { return RandomRewardContainersParser.Data.map(row => row['Idle3DAnimStart']); }
    static GetIdle3danimend() { return RandomRewardContainersParser.Data.map(row => row['Idle3DAnimEnd']); }
    static GetMiss3danimstart() { return RandomRewardContainersParser.Data.map(row => row['Miss3DAnimStart']); }
    static GetMiss3danimend() { return RandomRewardContainersParser.Data.map(row => row['Miss3DAnimEnd']); }
    static GetUpgrade3danimstart() { return RandomRewardContainersParser.Data.map(row => row['Upgrade3DAnimStart']); }
    static GetUpgrade3danimend() { return RandomRewardContainersParser.Data.map(row => row['Upgrade3DAnimEnd']); }
    static GetOpen3danimstart() { return RandomRewardContainersParser.Data.map(row => row['Open3DAnimStart']); }
    static GetOpen3danimend() { return RandomRewardContainersParser.Data.map(row => row['Open3DAnimEnd']); }
    static GetSoundappear() { return RandomRewardContainersParser.Data.map(row => row['SoundAppear']); }
    static GetSoundcharge() { return RandomRewardContainersParser.Data.map(row => row['SoundCharge']); }
    static GetSoundmiss() { return RandomRewardContainersParser.Data.map(row => row['SoundMiss']); }
    static GetSoundupgrade() { return RandomRewardContainersParser.Data.map(row => row['SoundUpgrade']); }
    static GetSoundreadytoopen() { return RandomRewardContainersParser.Data.map(row => row['SoundReadyToOpen']); }
    static GetSoundreadytoopen2() { return RandomRewardContainersParser.Data.map(row => row['SoundReadyToOpen2']); }
    static GetSoundopen() { return RandomRewardContainersParser.Data.map(row => row['SoundOpen']); }
    static GetFacefilename() { return RandomRewardContainersParser.Data.map(row => row['FaceFileName']); }
    static GetFaceidleexportname() { return RandomRewardContainersParser.Data.map(row => row['FaceIdleExportName']); }
    static GetFaceupgradeexportname() { return RandomRewardContainersParser.Data.map(row => row['FaceUpgradeExportName']); }
    static GetFaceopenexportname() { return RandomRewardContainersParser.Data.map(row => row['FaceOpenExportName']); }
    static GetSoloofferdefaultbgframename() { return RandomRewardContainersParser.Data.map(row => row['SoloOfferDefaultBgFrameName']); }
    static GetSoloofferdefaulttitletid() { return RandomRewardContainersParser.Data.map(row => row['SoloOfferDefaultTitleTID']); }
    static GetRarityframelabel() { return RandomRewardContainersParser.Data.map(row => row['RarityFrameLabel']); }
    static GetAnimationscw() { return RandomRewardContainersParser.Data.map(row => row['AnimationSCW']); }
    static GetPiggytap1() { return RandomRewardContainersParser.Data.map(row => row['PiggyTap1']); }
    static GetPiggytap2() { return RandomRewardContainersParser.Data.map(row => row['PiggyTap2']); }
    static GetPiggytap3() { return RandomRewardContainersParser.Data.map(row => row['PiggyTap3']); }
    static GetPiggytap4() { return RandomRewardContainersParser.Data.map(row => row['PiggyTap4']); }
    static GetPiggytapbackground1() { return RandomRewardContainersParser.Data.map(row => row['PiggyTapBackground1']); }
    static GetPiggytapbackground2() { return RandomRewardContainersParser.Data.map(row => row['PiggyTapBackground2']); }
    static GetPiggytapbackground3() { return RandomRewardContainersParser.Data.map(row => row['PiggyTapBackground3']); }
    static GetPiggytapbackground4() { return RandomRewardContainersParser.Data.map(row => row['PiggyTapBackground4']); }
    static GetPiggytapbackgroundfinal() { return RandomRewardContainersParser.Data.map(row => row['PiggyTapBackgroundFinal']); }
    static GetPiggytapbackgroundfinalbg() { return RandomRewardContainersParser.Data.map(row => row['PiggyTapBackgroundFinalBg']); }
    static GetCustomanimationnames() { return RandomRewardContainersParser.Data.map(row => row['CustomAnimationNames']); }
    static GetCustomanimationstartframes() { return RandomRewardContainersParser.Data.map(row => row['CustomAnimationStartFrames']); }
    static GetCustomanimationendframes() { return RandomRewardContainersParser.Data.map(row => row['CustomAnimationEndFrames']); }
    static GetDescriptionexportname() { return RandomRewardContainersParser.Data.map(row => row['DescriptionExportName']); }
}

export default RandomRewardContainersParser;
